### PR TITLE
[15 min fix] Fixed broken share button on article page.

### LINKED ISSUE #13690: Unable to click on the 3 dots button in the post
**Describe the bug**
Unable to click on the 3 dots button in the post

**To Reproduce**
Open any post on the dev.to and try to click on the three dots on the right-hand side of the page

**Expected behavior**
It should show me the option of share articles and other share options.

**Screenshots**

image

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Chrome Version 90.0.4430.93 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by nickytonline**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Fixed a regression caused by the fix in #13674. The share button on an article page was not opeing the share menu. This is fixed now.

@Zhao-Andy, I don't know when the fleet was last deployed, but if it was deployed after #13764 yesterday, we'll need to push this fix to the fleet.

## Related Tickets & Documents

#13674
Closes #13690

### Desktop

1. Navigate to any article page.
2. Click on the three dot share button below reactions in the article sidebar
3. The share menu opens

### Mobile

1. Navigate to any article page.
2. Click on the three dot share button beside reactions at the bottom of the screen
3. The share menu opens

### UI accessibility concerns?

N/A

## Added tests?

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [x] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

Home Simpson saying "Oh no!"

### CODE REVIEW

File: app/assets/javascripts/initializers/initializeCommentDropdown.js [hunk 1]
```diff
@@ -85,7 +85,7 @@ function initializeCommentDropdown() {
     }
   }
 
-  function initializeCommentEvents(commentsContainer) {
+  function initializeDropDownClick(commentsContainer) {
```
Comment (nickytonline) [inline app/assets/javascripts/initializers/initializeCommentDropdown.js:88]: Renamed this as it also pertains to the post share button.

File: app/assets/javascripts/initializers/initializeCommentDropdown.js [hunk 2]
```diff
@@ -156,14 +156,16 @@ function initializeCommentDropdown() {
...
+  );
 
   // We only want to add an event listener for the click once
-  if (commentsContainer && !commentsContainer.dataset.initialized) {
-    commentsContainer.dataset.initialized = true;
-    commentsContainer.addEventListener(
-      'click',
-      initializeCommentEvents(commentsContainer),
-    );
+  for (const element of [commentsContainer, articleShowMoreButton]) {
```
Comment (nickytonline) [inline app/assets/javascripts/initializers/initializeCommentDropdown.js:164]: Doing the same as before in #13674, but including the post share button too.

File: cypress/integration/articleFlows/postSidebarActions.spec.js [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+        }).then((response) => {
+          cy.visit(response.body.current_state_path);
+        });
+      });
+    });
+  });
+
+  it('should open the share menu for the post', () => {
+    // TODO: Get this working
+    cy.findByRole('button', { name: /^Toggle dropdown menu$/i }).click();
```
Comment (nickytonline) [inline cypress/integration/articleFlows/postSidebarActions.spec.js:22]: The click works but does not open the menu. It works in the app and when you click on it after the test fails. I even tried checking if the event was attached by doing

```
cy.get(
	'button[aria-label="Toggle dropdown menu"][data-initialized="true"]',
).click();
```

instead. Not sure what's up.

**Review by rhymes — APPROVED** [review]
Manually QAed this and it works!

File: app/assets/javascripts/initializers/initializeCommentDropdown.js (hunk 1 above)
Comment (aitchiss) [reply app/assets/javascripts/initializers/initializeCommentDropdown.js:88]: I think we should probably rename the arg too in this case. Also maybe the file name itself should change? I wouldn't expect the post share button to be initialized within `initializeCommentDropdown.js` (probably why we missed this in the first place!) 🤔 

```suggestion
  function initializeDropDownClick(dropdown) {
```

File: cypress/integration/articleFlows/postSidebarActions.spec.js (hunk 3 above)
Comment (aitchiss) [reply cypress/integration/articleFlows/postSidebarActions.spec.js:22]: I had a dig into this, and what's happening is that in the button click handler we:

- add the class "block" to the dropdown, and 
- we attach the clickOutsideListener to the the document....

 **but**  the initial button click event triggers the clickOutsideListener also when we're running in Cypress 🙃  Basically there is something funky going on with the event propagation, and the dropdown is opened and immediately closed all on that toggle button click.

The clickOutsideListener checks for various elements to see whether it should close dropdowns or not, but the `target` it receives on that first button click is the `<path>` element inside the icon svg, which wasn't accounted for in that method.

To be honest, I'm still trying to get my head around it. It doesn't happen during normal usage, and I think it is _something_ to do with how Cypress is actioning that click. 

To fix it we can add another check to the `shouldCloseDropdown` function to make sure the path within the `dropdown-icon` is also ignored:

```js
return !(
      event.target.matches('.dropdown-icon') ||
      event.target.parentElement.classList.contains('dropdown-icon') ||
      event.target.matches('.dropbtn') ||
      event.target.matches('clipboard-copy') ||
      isCopyIconChild ||
      event.target.parentElement.classList.contains('dropdown-link-row')
    );
```

I also noticed though that changing the line in the cypress test to

```js
cy.findByRole('button', { name: /^Toggle dropdown menu$/i }).click({ force: true});
```

also fixes the issue. Further evidence that there's something fundamental about how cypress executes click events that's causing this weirdness.

Comment (nickytonline) [reply cypress/integration/articleFlows/postSidebarActions.spec.js:21]: Thanks for digging. Just up before working out, so I've made your suggested changes and popped this to ready for review.

**Comment by nickytonline** [comment]
@aitchiss, I'll rename this file in a separate PR and potentially the function `initializeCommentDropdown` as it's not related to the bug fix.

**Review by aitchiss — APPROVED** [review]
Tested this locally on desktop and mobile - all looking good with both the share options dropdown and the comment dropdowns 👍

File: app/assets/javascripts/initializers/initializeCommentDropdown.js [hunk 4]
```diff
@@ -156,14 +157,16 @@ function initializeCommentDropdown() {
   }
 
   const commentsContainer = document.getElementById('comment-trees-container');
+  const articleShowMoreButton = document.getElementById(
+    'article-show-more-button',
+  );
```
Comment (Link2Twenty) [inline app/assets/javascripts/initializers/initializeCommentDropdown.js:162]: You could combine your two `getElementById` queries into one `querySelectorAll`, which means you don't have to combine them later too.

```js
const dropDownElements = document.querySelectorAll('#comment-trees-container, #article-show-more-button');

for (const element of dropDownElements ) {
  ...
}
```

Comment (Link2Twenty) [reply app/assets/javascripts/initializers/initializeCommentDropdown.js:162]: Gah, my review was just too late 😅

Comment (nickytonline) [reply app/assets/javascripts/initializers/initializeCommentDropdown.js:162]: Thanks for the review @Link2Twenty! I was being explicit to separate them, but you are right. It could use `querySelectorAll`. I'm just going to let the dust settle in the fix, but if you would like to, feel free to pop up a PR for that change.😎
