### PR TITLE
Unique cross-model-slug check is likely misconfigured

### LINKED ISSUE #19117: Page unique_cross_model_slug seems misconfigured
I noticed while working on #19009 and reviewing #19024 that our `Page` model doesn't seem properly configured for `unique_cross_model_slug`. 

That is to say: when one creates a new page that duplicates a slug from a non-page object (a username, organization or podcast slug, say), `UniqueCrossModelSlugValidator` is fine. However, if one tries to create a page that duplicates a slug from a _page_, `UniqueCrossModelSlugValidator` does not check the other pages. The effect is that we wind up raising a Postgres exception, from attempting to violate the db constraint.

I'm not sure, but it seems as though `UniqueCrossModelSlugValidator` assumes that the model will handle its own uniqueness -- that _may_ be true for other models (I have not rigorously checked), but was _not true_ for pages prior to #19009.

I patched in a [quick-fix](https://github.com/forem/forem/pull/19009/commits/86230b99ad2bc87278d556909864267f871bc4dc) in #19009 but we ought to figure out a proper fix, including tests (and, if properly configured, that quick fix might become unnecessary), and possibly we should consider updating `UniqueCrossModelSlugValidator` to handle "own model" case, as well.

### PR DESCRIPTION
**Pull request by jaw6**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description

Original issue is described in #19117, but to re-cap: 

* I discovered in the process of [adding Page to the API](https://github.com/forem/forem/pull/19009) that the cross-model-slug validator was either not working (did not constrain uniqueness as expected) or mis-configured, or _something_.
* @gorangorun opened [a PR to refactor the cross-model-slug validator](https://github.com/forem/forem/pull/19249) and also [a PR refactoring unique-username generation](https://github.com/forem/forem/pull/19252)
* I caused some confusion by assigning #19117 to myself
* There was some discussion in #19252 (now lost to force-push, it seems) that it might be valuable to extract cross-model uniqueness checking to be more useful in this class
* This PR extracts cross-model slug `exists?` checks, building on the refactored validator from #19249, while attempting to make the cross-model check something that could be used independently of the validator (in, say, a username-generator).

## Related Tickets & Documents

- Closes #19117

## QA Instructions, Screenshots, Recordings

Question for reviewers: Is this "too much 'magic'" ?

## Added/updated tests?

- [x] Yes - gentle refactoring, plus some validation messages changed
- [ ] No, and this is why: 
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [x] This change does not need to be communicated, and this is why not: internal refactoring mostly

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

File: app/validators/cross_model_slug_validator.rb [hunk 1]
```diff
@@ -0,0 +1,39 @@
+##
+# Validates if the give attribute is used across the reserved spaces.
+class CrossModelSlugValidator < ActiveModel::EachValidator
+  FORMAT_REGEX = /\A[0-9a-z\-_]{2,}\z/
```
Comment (gorangorun) [inline app/validators/cross_model_slug_validator.rb:4]: I think we should update this to 
```
/\A[0-9a-z\-_]+\z/
```

File: app/services/users/username_generator.rb [hunk 2]
```diff
@@ -7,46 +7,55 @@
...
-      list.detect { |username| !username_exists?(username) }
+    def filtered_usernames
+      @filtered_usernames ||= usernames.select { |s| s.is_a?(String) && s.present? }
     end
 
-    def username_exists?(username)
-      User.exists?(username: username) ||
-        Organization.exists?(slug: username) ||
-        Page.exists?(slug: username) ||
-        Podcast.exists?(slug: username)
```
Comment (jaw6) [inline app/services/users/username_generator.rb:33]: As discussed [over here](https://github.com/forem/forem/pull/19252/files#r1147814236), refactoring the name generator to use the new cross-model-unique-slug gizmo.

Comment (gorangorun) [reply app/services/users/username_generator.rb:33]: Shouldn't we apply the reserved list validator?

Comment (jaw6) [reply app/services/users/username_generator.rb:33]: Good point! I mean, generator generates before validation, but the generator probably wants to move onto the next attempt if it randomly generates a `ReservedWord`, rather than block user create. I believe the extracted `CrossModelSlug` class is going to be useful elsewhere, so I added it [there](https://github.com/forem/forem/pull/19263/commits/5b6e2233d17224c2505ba82fc8f4d2fefb6e4438) rather than add it to the generator class.

File: spec/system/admin/admin_manages_pages_spec.rb [hunk 3]
```diff
@@ -80,17 +80,20 @@
   describe "when the defaults are overridden" do
     before do
       create(:page,
+             :without_validations, # validations prevent reserved_word "code-of-conduct"
```
Comment (maestromac) [inline spec/system/admin/admin_manages_pages_spec.rb:83]: Appreciate the comments here!

File: app/models/application_record.rb [hunk 4]
```diff
@@ -62,6 +62,12 @@ def self.with_statement_timeout(duration, connection: self.connection)
     connection.execute "SET statement_timeout = #{milliseconds}"
   end
 
+  def self.unique_across_models(attribute, **options)
+    CrossModelSlug.register(self, attribute)
+    validates attribute, presence: true
+    validates attribute, cross_model_slug: true, **options, if: :"#{attribute}_changed?"
+  end
```
Comment (maestromac) [inline app/models/application_record.rb:69]: nit/question: Would it make more sense for this to live as a concern instead? I suppose that's just a pattern I'm more familiar with.

File: app/models/cross_model_slug.rb [hunk 5]
```diff
@@ -0,0 +1,42 @@
...
+
+      value = value.downcase
+
+      # Reserved check may be redundant, but allows this to be used outside of Validator
+      return true if ReservedWords.all.include?(value)
+      return true if value.include?("sitemap-") # https://github.com/forem/forem/pull/6704
+
+      (@registered_models || []).detect do |klass, attribute|
+        klass.exists?({ attribute => value })
+      end
```
Comment (maestromac) [inline app/models/cross_model_slug.rb:39]: I understand that `@registered_models` should have all proper model loaded on boot. Out of curiosity, I tried to check `CrossModelSlug.registered_models` in rails console, but only User model is registered. This got me thinking, would there be a scenario where not all the models were properly registered? I'm thinking in the case of background jobs.

File: app/models/application_record.rb (hunk 4 above)
Comment (jaw6) [reply app/models/application_record.rb:69]: I think either works, and `concerns` would probably be a better fit. I'll move it there. (I am old, I forget `concerns` exists. Rails ... 4 (!) is still very "new" to my old brain. :brain: )

File: app/models/cross_model_slug.rb (hunk 5 above)
Comment (jaw6) [reply app/models/cross_model_slug.rb:39]: So, any `production` environment ought to have `eager_load = true`, which will cause Rails to parse every file in the `eager_load_paths`. In `development` and `test`, `eager_load` is `false`, because Rails prefers to refresh code on every request in development.

```
# with eager-loading **off** / development & test
❯ rails r 'puts CrossModelSlug.registered_models.map(&:first).map(&:to_s)'
[...warnings...]
User

# with eager-loading **on** / production
❯ rails r 'puts CrossModelSlug.registered_models.map(&:first).map(&:to_s)'
[...warnings...]
User
Organization
Page
Podcast
```

(It's somewhat interesting that `User` is already loaded even in development, the implication is that something in the Rails env boot cycle — a gem, an initializer, or routes maybe — references `User` somehow.)

This isn't to say that this is 0% risk:

* We might introduce new environments that aren't `eager_load` (maybe a `staging` environment? or a `asset-build` environment?)
* We might trigger a kind of "false negative" while testing or while QAing in `development` — this issue originally came up while [working on API changes](https://github.com/forem/forem/pull/19009/files/dff9352872f95a4ef17c07c6996d1ad82c538878#diff-92779dbf72cdd79815877e327b5693b0448053945e302d567814c33a5e0a49d1R14), when I noticed I could create multiple Pages with the same slug, that kind of confusion could come up again

(Traditionally, the biggest risk with this kind of class-level macro is creating a "loop" — the interpreter can't load `User` without loading some `Module` that then references `User`, which then references `Module`, ➿ . The "lazy" effect here — registration, using that registration at a later point — does not have _that_ problem.)

Just to be clear: I am a bit conflicted on this `registration` approach — I tend to think the trade-offs are "worth it", but even I think this is dancing very close to "too much".

File: app/models/application_record.rb (hunk 4 above)
Comment (gorangorun) [reply app/models/application_record.rb]: I think this was fine. As far as i know, code should be moved to concern only if it will be used in more than one class/module.

Comment (maestromac) [reply app/models/application_record.rb]: Sorry I should've clarified the concern I'm thinking about is something like this

```ruby
Class User
  includes Slugable
end

Class Article
  includes Slugable
end

module Slugable
  extend ActiveSupport::Concern

  included do
    validates attribute, presence: true
    validates attribute, cross_model_slug: true, **options, if: :"#{attribute}_changed?"
  end
end
```

Comment (jaw6) [reply app/models/application_record.rb]: @maestromac and I wound up chatting about this a bit yesterday. The proposed pseudo-code above doesn't work in this case, because not all of these models use `slug` as the attribute name (`User#username` is the "problem"), that's what made me think a macro would work here. 

I'm pretty open to suggestions on exactly where this lives, but I have a pedantic desire to avoid `include`ing a module who's only job is adding a class-level macro.

File: app/models/application_record.rb [hunk 6]
```diff
@@ -2,6 +2,7 @@ class ApplicationRecord < ActiveRecord::Base
   self.abstract_class = true
 
   include Purgeable
+  extend UniqueAcrossModels
```
Comment (maestromac) [inline app/models/application_record.rb:5]: nit/optional: as we spoke, this wasn't what I was suggesting, but I'll leave it up to you whether to keep or undo this refactor.

File: app/models/cross_model_slug.rb (hunk 5 above)
Comment (maestromac) [reply app/models/cross_model_slug.rb:39]: Hmm, well, the potential for risk here is also giving me a bit of hesitancy. I like clever approaches, but it may be worth just sticking toe the verbose explicit 'registration' to have that peace of mind. I would like to hear others opinion on this.

Comment (lightalloy) [reply app/models/cross_model_slug.rb:39]: I'm not comfortable with "registering", as it brings the risks, I would set up the explicit list of the models, across which the validator works, and so, needs to be checked.

File: app/models/application_record.rb (hunk 6 above)
Comment (lightalloy) [reply app/models/application_record.rb:5]: @maestromac is the approach you had suggested described anywhere? It would be interesting to see.

File: app/models/cross_model_slug.rb (hunk 5 above)
Comment (jaw6) [reply app/models/cross_model_slug.rb]: Removed registration in [82cbb121](https://github.com/forem/forem/pull/19263/commits/82cbb1215c74949714094e10547cf464e302ed35).

File: app/models/cross_model_slug.rb [hunk 7]
```diff
@@ -0,0 +1,37 @@
+#
+# We have a simple top-level route equivalent to `/slug`. Because of this,
+# we want to verify that newly created records don't overlap with a previously-
+# defined `slug` -- in other words, slug values should be unique across all
+# relevant models. Except also, models might use "username" instead of "slug".
+#
+# Models can register with this class to be included in a cross-model-uniqueness
```
Comment (lightalloy) [inline app/models/cross_model_slug.rb:7]: I suppose we should remove "register" terminology from the comments as registration was removed.

File: app/models/application_record.rb (hunk 6 above)
Comment (lightalloy) [reply app/models/application_record.rb:5]: This is shorter, but we only need `UniqueAcrossModels` for 4 models, why extend all of them?

File: app/models/cross_model_slug.rb (hunk 7 above)
Comment (jaw6) [reply app/models/cross_model_slug.rb]: Tried to re-word this in d4f29305f

**Comment by Ridhwana** [comment]
There's already a few reviews going on in this PR so I'll remove myself as a reviewer here.

**Review by maestromac — APPROVED** [review]
LGTM!

**Review by lightalloy — APPROVED** [review]
