### PR TITLE
Fix Search Navigation Disconnect Between URL and Search Input

### LINKED ISSUE #11010: Search input is not in sync with URL in browser when navigating back/forth
**Describe the bug**

When searching for things on DEV, search in the UI works but if we go back and forward in browser history, the search input does not reflect the search term in the URL of the browser.

**To Reproduce**

1. Go to https://dev.to
2. In the search at the top of the page, type in `ruby` and press enter.
3. The URL in the browser will switch to `https://dev.to/search?q=ruby`.
4. Do another search, but this time for `javascript`
5. The URL in the browser will switch to `https://dev.to/search?q=javascript`.
6. Hit the back button of the browser.
7. The URL in the browser will switch to `https://dev.to/search?q=ruby`.
8. If you look at the search term in the search input in the top of the page, it will still say `javascript`.

**Expected behavior**

When navigating back and forth in the browser, the search term, if any in the URL, should always be reflected in the search input.

**Screenshots**

image

See it in action in the Loom video

https://www.loom.com/share/0b6cefcfa85a4cce875f99764c107e64

**Desktop (please complete the following information):**

- OS, version: N/A
- Browser, version: N/A

**Smartphone (please complete the following information):**

- Device: N/A
- OS, version: N/A
- Browser, version: N/A

**Additional context**

I came across this while helping out @ludwiczakpawel with #10424.

### PR DESCRIPTION
**Pull request by nickytonline**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Prior to this PR, when searching for things on DEV, search in the UI worked but if we went back and forward in browser history, the search input would not reflect the search term in the URL of the browser.

## Related Tickets & Documents

Closes #11010

## QA Instructions, Screenshots, Recordings

Before

image

See it in action in the Loom video

https://www.loom.com/share/0b6cefcfa85a4cce875f99764c107e64

After

image

See it in action in the Loom video

https://www.loom.com/share/3fa9e1f9892d480199fb2c48be130dd3

1. Go to https://dev.to
2. In the search at the top of the page, type in `ruby` and press enter.
3. The URL in the browser will switch to `https://dev.to/search?q=ruby`.
4. Do another search, but this time for `javascript`
5. The URL in the browser will switch to `https://dev.to/search?q=javascript`.
6. Hit the back button of the browser.
7. The URL in the browser will switch to `https://dev.to/search?q=ruby`.
8. If you look at the search term in the search input in the top of the page, it will say `ruby`.

## Added tests?

- [x] yes
- [ ] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

A dancing animated skeleton

### CODE REVIEW

File: app/javascript/Search/Search.jsx [hunk 1]
```diff
@@ -51,6 +51,25 @@ export class Search extends Component {
   componentDidMount() {
     this.registerGlobalKeysListener();
     InstantClick.on('change', this.enableSearchPageListener);
+
+    window.onpopstate = () => {
+      // TODO: Consolidate search functionality.
```
Comment (nickytonline) [inline app/javascript/Search/Search.jsx:56]: This is a future TODO out of the scope of this fix.

File: app/javascript/utilities/search/index.js [hunk 2]
```diff
@@ -70,7 +70,7 @@ export function getInitialSearchTerm(querystring) {
     matches !== null && matches.length === 2
       ? decodeURIComponent(matches[1].replace(/\+/g, '%20'))
       : '';
-  const query = filterXSS(rawSearchTerm);
+  const query = filterXSS(rawSearchTerm) || '';
```
Comment (nickytonline) [inline app/javascript/utilities/search/index.js:73]: This fixes an issue where it became a string `"undefined"` instead of just an empty string.

**Review by ludwiczakpawel — APPROVED** [review]
Works as described.

File: app/javascript/Search/Search.jsx [hunk 3]
```diff
@@ -51,6 +51,25 @@ export class Search extends Component {
   componentDidMount() {
     this.registerGlobalKeysListener();
     InstantClick.on('change', this.enableSearchPageListener);
+
+    window.onpopstate = () => {
```
Comment (rhymes) [inline app/javascript/Search/Search.jsx:55]: I always forget, doesn't this override any other `onpopstate` that might there be set? Would it be better with `addEventListener`? Or are we overriding on purpose?

**Review by rhymes — APPROVED** [review]
Works great, left a question :)

File: app/javascript/Search/Search.jsx (hunk 3 above)
Comment (nickytonline) [reply app/javascript/Search/Search.jsx:55]: I looked at the documentation. And that seems to be the way to do it. I did this late last night though. I'll double check, because adding an event listener is what I do usually.

Comment (nickytonline) [reply app/javascript/Search/Search.jsx:55]: Yeah, so it has `addEventListener` for this. Just going to make the change.

Comment (rhymes) [reply app/javascript/Search/Search.jsx:55]: Cool :) It seems it can be done in both ways https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event

Comment (nickytonline) [reply app/javascript/Search/Search.jsx]: This is good to go now @rhymes. I added some tests to verify the event is added and removed.

File: app/javascript/Search/Search.jsx [hunk 4]
```diff
@@ -81,8 +106,9 @@ export class Search extends Component {
     }
   }
 
-  componentDidUnmount() {
+  componentWillUnmount() {
```
Comment (nickytonline) [inline app/javascript/Search/Search.jsx:109]: The wrong [mount lifecycle method](https://reactjs.org/docs/react-component.html#mounting) was being used. `componentDidUnmount` no longer exists. This was never caught after the Preact upgraded.

File: app/javascript/Search/__tests__/Search.test.jsx [hunk 5]
```diff
@@ -9,6 +9,7 @@ describe('<Search />', () => {
     global.filterXSS = jest.fn();
     global.InstantClick = jest.fn(() => ({
       on: jest.fn(),
+      off: jest.fn(),
```
Comment (nickytonline) [inline app/javascript/Search/__tests__/Search.test.jsx:12]: This was missing and never caused issues until I discovered we were using the legacy `componentDidUnmount`.
