### PR TITLE
Fix "Infinity" dashboard analytics by using 2 digits for hardcoded month and day for JS Date

### LINKED ISSUE #13217: Analytics: Infinity time window produces JS error in Safari
I'm trying out the new Analytics feature for my account jaredcwhite on Dev.to. The Week and the Month time windows work fine, but when I select Infinity, I get a "RangeError: Invalid Date" error. The offending code seems to be `toISOString` in this block:

```js
function callAnalyticsAPI(path, date, { organizationId, articleId }, callback) {
  let url = `${path}?start=${date.toISOString().split('T')[0]}`;
```

This is when using Safari for Big Sur, Version 14.0.2 (16610.3.7.1.9)

I logged in with Firefox 87 and Infinity does work there.

### PR DESCRIPTION
**Pull request by jgaskins**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Single-digit months and days are not compliant with the ECMAScript
standard for date strings.

See: https://262.ecma-international.org/11.0/#sec-date-time-string-format

Fixes #13217 

## QA Instructions, Screenshots, Recordings

1. Open Safari
2. Visit https://dev.to/dashboard/analytics
3. Click "Infinity"
4. You should see your metrics since April 1, 2019

### UI accessibility concerns?

None, just a date format fix

## Added tests?

- [ ] Yes
- [x] No, and this is why: If we were accepting arbitrary dates here, I think it would make sense to write a test, but this changes a hardcoded value to match the ECMAScript spec
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [x] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

### CODE REVIEW

**Review by vaidehijoshi — APPROVED** [review]
This works well on Safari now for me! 👍🏽 

I wonder if there is a way for us to use a linter to prevent this kind of thing from accidentally slipping in? Seems like a very easy thing to forget and like something we'd want to keep consistent. Obviously this could be a separate PR if we can figure out how to get the linter to do it (full transparency: I haven't investigated this at all yet, just wanted to leave a note of it here)

File: app/javascript/analytics/dashboard.js [hunk 1]
```diff
@@ -223,7 +223,7 @@ function drawMonthCharts({ organizationId, articleId }) {
 function drawInfinityCharts({ organizationId, articleId }) {
   resetActive(document.getElementById('infinity-button'));
   // April 1st is when the DEV analytics feature went into place
-  const beginningOfTime = new Date('2019-4-1');
+  const beginningOfTime = new Date('2019-04-01');
```
Comment (rhymes) [inline app/javascript/analytics/dashboard.js:226]: now that we're at it, could we switch to numbers, `new Date(2019, 3, 1)`?

> Note: Parsing of date strings with the Date constructor (and Date.parse, they are equivalent) is strongly discouraged due to browser differences and inconsistencies.

from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#several_ways_to_create_a_date_object

also https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date for details on usage (the month is zero indexed for example)

**Review by rhymes — COMMENTED** [review]
Great find @jgaskins!

@vaidehijoshi there's a plugin that disallows the deprecated habit of passing strings to the `Date()` constructor: https://github.com/msobas/eslint-plugin-date-timezone/blob/main/docs/rules/no-date-from-string.md

We could also write our own eslint plugin, [doesn't seem super difficult :D](https://github.com/HeavenSky/eslint-plugin-date/blob/master/src/rules/no-new-date-without-args.js)

File: app/javascript/analytics/dashboard.js (hunk 1 above)
Comment (jgaskins) [reply app/javascript/analytics/dashboard.js:226]: > the month is zero indexed

This is actually the reason I didn't use the numbers[1]. I understand why months are zero-indexed, but given the number of times I've seen devs try to "helpfully" fix a month in a JS date constructor because they think it's a typo, even when there was a comment right above it (I can _especially_ imagine this during Hacktoberfest with all the drive-by PRs), I'm just not sure it's worth it.

If we were accepting user input, I think it might be worth using this constructor instead of trying to fill out an ISO8601/RFC3339 datetime string ourselves. But since the date is harcoded and unlikely to change, and conforms to the standard outlined in the ECMAScript standard linked in the PR description, we're probably in a pretty safe spot.

I'm also wondering if we need this to be a specific date. Do we know what happens if we just use `new Date(0)`?

---

[1] It reminds me of [this slide](https://talks.chastell.net/wrocloverb-2014-lt/#2) from a talk a friend of mine gave a while back:

new Date(2014, 3, 16) in Java returns April 16, 3914

Comment (rhymes) [reply app/javascript/analytics/dashboard.js:226]: We can still add a comment, that will fix everything 🤣 

Can't wait for `Temporal` to land in browsers https://tc39.es/proposal-temporal/docs/index.html

Comment (aitchiss) [reply app/javascript/analytics/dashboard.js:226]: ha! [I have been bitten by the zero indexed months so many times](https://twitter.com/s_aitchison/status/1252585923495235584) 🙈

**Review by aitchiss — APPROVED** [review]
Looks good to me -  tested locally in safari and all OK 👍

File: app/javascript/analytics/dashboard.js (hunk 1 above)
Comment (jgaskins) [reply app/javascript/analytics/dashboard.js:226]: lol [same](https://twitter.com/jamie_gaskins/status/622076331895861248)!

**Comment by jgaskins** [comment]
@rhymes How're you feeling about the change without using the numbers?

**Review by rhymes — APPROVED** [review]
Let's do this!
