### PR TITLE
Pass options correctly to chart.js on articles#stats

### LINKED ISSUE #17433: ticks for y-axis in Charts should be integer
**Describe the bug**

ticks for y-axis in Charts should be integer.

**To Reproduce**
n/a

**Expected behavior**
As all numbers in y-axis are integer, ".0" is not required at ticks in y-axis.

**Screenshots**
See above.

This looks like a regression from #3102 for almost three years.

### PR DESCRIPTION
**Pull request by tnir**
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>

## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Bug Fix

## Description
Pass options correctly to chart.js on (frontend of) `articles#stats` to remove unnecessary ticks (after the decimal point) and grid lines on y-axis to revert #2037's intention after #3102.

This would lead changes mainly on stats for articles with less 10 pageview per day in specific spans (in 7 days or 30 days).

## Related Tickets & Documents

- Closes #17433
- Relates to #3102 (cause of regression)
- Original implementation: #2037
- Docs on upstream (chart.js 3.7.1)
   - Axes: https://chartjs.org/docs/3.7.1/axes/
   - Point configuration: https://www.chartjs.org/docs/3.7.1/configuration/elements.html#point-configuration

## QA Instructions, Screenshots, Recordings

| before | after |
|-|-|
|  | user_slug_stats_after |

## Added/updated tests?

- [x] I need help with writing tests

### CODE REVIEW

File: app/javascript/analytics/dashboard.js [hunk 1]
```diff
@@ -45,15 +45,23 @@ function writeCards(data, timeRangeLabel) {
...
+    elements: {
+      point: {
+        // The default is 3: https://www.chartjs.org/docs/latest/configuration/elements.html#point-configuration
+        radius: showPoints ? 3 : 0,
+      },
+    },
+    scales: {
+      y: {
+        type: 'linear',
+        suggestedMin: 0,
```
Comment (aitchiss) [inline app/javascript/analytics/dashboard.js:58]:
```suggestion
       min: 0,
```
Maybe we should change this to the more prescriptive `min`? - `suggestedMin` works great when the data is more than just 0, but I noticed when the data is all zeroes, we still see a negative value in the axis:
axis goes to minus 1

**Review by aitchiss — APPROVED** [review]
Definitely an improvement - thank you! I've left one non-blocking suggestion - I'll leave it to you to let me know what you think before we merge this 🙂

File: app/javascript/analytics/dashboard.js (hunk 1 above)
Comment (tnir) [reply app/javascript/analytics/dashboard.js:58]: @aitchiss Thanks. While I noticed it when I worked on this, this `drawChart` function looks generic and would take dataset arguments with negative integers in the future. Not sure what the original intention is #2037, but would be safe to me (who is new to Forem) if we keep this unchanged 😀

Comment (aitchiss) [reply app/javascript/analytics/dashboard.js:58]: That makes sense!

Comment (tnir) [reply app/javascript/analytics/dashboard.js:58]: note: this looks like a kind of bug to me. A further test bed is just prepared: https://codepen.io/tnir/pen/bGLdPOO

Comment (tnir) [reply app/javascript/analytics/dashboard.js:58]: note: this looks like a kind of bug to me. A further test bed is just prepared: https://codepen.io/tnir/pen/bGLdPOO
