### PR TITLE
Use the rss item's url when handling relative image links 

### LINKED ISSUE #15488: RSS Feed is not Imported
I created a new post on my webpage and tried importing it to dev.to; my feed is valid according to <a href="https://validator.w3.org/feed/check.cgi?url=http%3A//kaylumah.nl/feed.xml">[Valid Atom 1.0]</a>

**To Reproduce**

Use https://dev.to/settings/extensions to import feed

**Expected behavior**

New feed item is imported

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

I've tried manipulating the rss feed items and wrapping content in CDATA makes it appear, but breaks all snippets (so that might be issue on my end)

### PR DESCRIPTION
**Pull request by djuber**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

When we get image links with local, absolute paths (like ``) we're using the `@feed.url` to find the base url to attach that path to. However, the source of `@feed.url` makes some assumptions about the meaning and content of `<link>` tags in the feed that don't necessarily apply to atom feeds.

Looking at https://developeronfire.com/rss.xml (a podcast rss feed) it's clear the last link (not the two atom10:link's but the unadorned rss `<link>`) could point to a base path for the items, but there's no reason to believe that this is true generally (that the blog post index is not on /blog/, which breaks our assumptions about the way to build absolute paths from relative ones).

For rss, https://web.resource.org/rss/1.0/spec#s5.3.2 the url should be an html rendering of the channel title (where the feed comes from, not necessarily where items are on that server, not necessarily even the same server as the feed items). For atom, https://validator.w3.org/feed/docs/atom.html#recommendedFeedElements specifies there can be any number of links and it's not clear we should be using _any_ of them for building image paths

This probably should just be using the item's url always to make a
base path for any relative paths (without a hostname), rather than expecting
this from the feed.

## Related Tickets & Documents

Fixes  #15488

## QA Instructions, Screenshots, Recordings

My failing test case was this:

```ruby
user = User.find_by(email: 'admin@admin.local')
user.setting.update(feed_url: 'https://kaylumah.nl/feed.xml')
Feeds::Import.call(users: User.where(id: user.id))
```

This failed to import articles with URI::BadURIError when trying to call URI.join with `""` and `"/path/to/image"`

```
feeds::import::error::URI::BadURIError::{:feeds_import_info=>{:username=>"admin_mcadmin", :feed_url=>"https://kaylumah.nl/feed.xml", :item_count=>6, :error=>"Feeds::Import::CreateArticleError:https://kaylumah.nl/2021/03/27/set-nuget-metadata-via-msbuild.html"}, :error_message=>"both URI are relative"}
```

On main that failed, on this branch it succeeded (because we're not reading the href="" from the last link). 

```ruby
URI.join("", "/")
URI::BadURIError: both URI are relative
```

I pulled a few feed urls at random and once I confirmed the feed itself didn't timeout (url was still valid) I imported them in a loop, and didn't see errors with images or URI building.

```sql
select feed_url from users_settings 
where feed_url not in ('') 
and feed_url is not null 
 order by random() 
limit 20;
```

### UI accessibility concerns?

None, backend only.

## Added/updated tests?

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [x] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Review by jeremyf — APPROVED** [review]

File: app/services/feeds/assemble_article_markdown.rb [hunk 1]
```diff
@@ -31,6 +31,14 @@ def call
 
     private
 
+    def feed_url
+      @feed_url ||=
+        @feed.url.presence ||
```
Comment (djuber) [inline app/services/feeds/assemble_article_markdown.rb:36]: is there a good reason to prefer @feed.url (from links) even if it is present? From what I can tell from https://validator.w3.org/feed/docs/atom.html#recommendedFeedElements ,  that implementation in feedjira is a little optimistic (it just uses the last link that's not the feed itself ?).

File: app/services/feeds/assemble_article_markdown.rb [hunk 2]
```diff
@@ -31,6 +31,13 @@ def call
 
     private
 
+    def base_url
+      @base_url ||=
+        URI.parse(@item.url).then do |uri|
```
Comment (djuber) [inline app/services/feeds/assemble_article_markdown.rb:36]: are there ever rss items without a url?

https://web.resource.org/rss/1.0/spec#s5.5 the RSS spec requires there be a valid uri for each item
https://validator.w3.org/feed/docs/atom.html#requiredEntryElements the atom spec uses id and requires it be a unique URI.

**Review by joshpuetz — CHANGES_REQUESTED** [review]
This seems like a sensible change but I'm curious about testing: do existing test cover this change?

**Review by citizen428 — APPROVED** [review]
