### PR TITLE
Fix successfully passing incorrect tests in actionsPanel.test.js

### LINKED ISSUE #19951: Fix successfully passing incorrect tests in actionsPanel.test.js
There are couple of tests in [this describe block](https://github.com/forem/forem/blob/main/app/javascript/actionsPanel/__tests__/actionsPanel.test.js#L59) which are passing but have been written incorrectly (may need to update production code too). 
Basically we have api-call related code and we are trying to tests them in these tests by mocking them but the results against we are checking them are not part of the API call. That is, if we remove all code related to fetch-mock in this describe block, then also tests pass.

[Video: Describing the issue with the tests](https://www.loom.com/share/7a4e2bfb0e02445981229622c06e7637)
[Video: Describing the issue and suggested solution](https://www.loom.com/share/363f1f2d637f4686a40ea0649c42e605)

### PR DESCRIPTION
**Pull request by joaoGabriel55**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

There are couple of tests in [this describe block](https://github.com/forem/forem/blob/main/app/javascript/actionsPanel/__tests__/actionsPanel.test.js#L59) which are passing but have been written incorrectly (may need to update production code too).
Basically we have api-call related code and we are trying to tests them in these tests by mocking them but the results against we are checking them are not part of the API call. That is, if we remove all code related to fetch-mock in this describe block, then also tests pass.

[Video: Describing the issue with the tests](https://www.loom.com/share/7a4e2bfb0e02445981229622c06e7637)
[Video: Describing the issue and suggested solution](https://www.loom.com/share/363f1f2d637f4686a40ea0649c42e605)

## Related Tickets & Documents

- Related Issue #19951
- Closes #19951

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [axe DevTools](https://www.deque.com/axe/) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

_For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?
_We encourage you to keep the code coverage percentage at 80% and above._

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [optional] What gif best describes this PR or how it makes you feel?

image

### CODE REVIEW

File: app/javascript/actionsPanel/actionsPanel.js [hunk 1]
```diff
@@ -56,30 +57,45 @@ function applyReactedClass(category) {
...
+    initialButtonsState[button.getAttribute('data-category')] =
+      classList.contains('reacted');
+  });
+
+  const rollbackReactionButtonsState = () => {
+    reactionButtons.forEach(({ classList, dataset }) => {
+      if (initialButtonsState[dataset.category]) classList.add('reacted');
+      else classList.remove('reacted');
+    });
+  };
```
Comment (maestromac) [inline app/javascript/actionsPanel/actionsPanel.js:77]: Nice addition!

**Review by maestromac — APPROVED** [review]
LGTM Thank you for this!
