### PR TITLE
Restore marking notifications as read via InstantClick

### LINKED ISSUE #19337: notifications/reads not always being fetched when visiting notification center
**Describe the bug**

It appears that when I visit notification center lately, most of the time the notification is not clearing for me.

**To Reproduce**

- Visit home page when you have a notification
- Open dev tools
- Click into `/notifications` and observe that `/reads` is not being fetched as it should

**Expected behavior**

This endpoint should fetch and the notifications should clear.

**Additional context**

This may have been caused here:

https://github.com/forem/forem/pull/19124

I believe I am also seeing this behavior on the loading of the "shield" icon on posts when clicking in from the home page. Seems this may be related to how the code now listens for page changes.

### PR DESCRIPTION
**Pull request by jaw6**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

If one navigates directly to `/notifications`, there's a background XHR to `/reads` (which marks notifications as read). If one clicks to this page via the "bell icon", there's no XHR to `/reads`.

## Related Tickets & Documents

- Closes #19337

## QA Instructions, Screenshots, Recordings

* Navigate to `/notifications` by clicking on the "bell icon"
* Observe that there is a request to `/reads` (via either `log/development.log` or browser console/network)

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: meh, InstantClick 
- [ ] I need help with writing tests

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

`cc` @benhalpern @lboogie04

### CODE REVIEW

**Review by Ridhwana — APPROVED** [review]

**Review by maestromac — APPROVED** [review]

File: app/javascript/packs/baseInitializers.js [hunk 1]
```diff
@@ -8,7 +8,10 @@ import {
 
 initializeCommentDate();
 initializeCommentPreview();
-initializeNotifications();
+
```
Comment (benhalpern) [inline app/javascript/packs/baseInitializers.js:11]:
```suggestion
initializeNotifications();

```

I believe this also needs to be called on the initial load _in addition_ to InstantClick

**Review by benhalpern — APPROVED** [review]
Committed a small adjustment, and all looks good.
