### PR TITLE
Fix articles counts based on display rules

### LINKED ISSUE #20621: Fix displayed article comment counts (take into account comments hidden after the author is assigned `spam`)
**Describe the bug**

Article comment counts are not updating when comment authors are being applied with the `spam` role.

**To Reproduce**

- Find an article with multiple comments
- Apply `spam` role to one of the comment authors
- Wait for any caches to be invalidated
- Comment is hidden, but comment count remains the same.

**Expected behavior**

The comment count should show the number of visible comments on the article (i.e. not counting those from users applied with `spam`).

**Screenshots**

image

**Additional context**

- We may not want to update the actual comment count, but dynamically calculate the actual number of displayed comments.

### PR DESCRIPTION
**Pull request by lightalloy**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Fixed number of comment counts on the article page.
The count includes displayed comments, comments displayed as "deleted" and "hidden by user" (as it was before).
The count doesn't include comments that are not displayed at all (childless comments with score below hiding threshold).

First, I planned to have a separate count for signed out users (we hide all negative comments and their children), but abandoned this idea because it's hard to impement and is kind of misleading: we hide some other comments from signed out users anyway and have a notice "some comments are only displayed to signed in users", so it should be obvious that the count may include such comments.

## Concerns:
- comments counts in feed is not changed (I would do it as a separate pr, I suppose it will require storing smth like "displayed_comments_count" instead of counting each time)
- count is based on `comments_count` by counter_culture which is counted separately (maybe we should actually count to be sure 🌚, I will think about it while working on the next step described in the first concern)

## Related Tickets & Documents
- Related issue #20621

## Added/updated tests?
- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

### CODE REVIEW

File: app/models/comment.rb [hunk 1]
```diff
@@ -88,6 +88,7 @@ class Comment < ApplicationRecord
 
   scope :eager_load_serialized_data, -> { includes(:user, :commentable) }
   scope :good_quality, -> { where("score > ?", LOW_QUALITY_THRESHOLD) }
+  scope :hidden_by_score, -> { where("score <= ?", HIDE_THRESHOLD) }
```
Comment (maestromac) [inline app/models/comment.rb:91]: I think `below_score_threshold` is a more fitting name but look like this method isn't used anywhere?

**Review by maestromac — APPROVED** [review]
LGTM!

File: app/models/comment.rb (hunk 1 above)
Comment (lightalloy) [reply app/models/comment.rb:91]: Yeah, I made a lot of iterations before the final solution, so kept it unintentionally, will remove.

**Review by benhalpern — APPROVED** [review]
