### PR TITLE
[15 minute fix] Fixed issue with member navigation button only working after full page loads but not InstantClick page transitions

### LINKED ISSUE #13399: Using enter key on desktop or touch on mobile only opens the member menu every second time
**Describe the bug**

The member navigation menu does not always open when using keyboard navigation via the ENTER key or touch on mobile.

I think this might be related to changes made in #12753

See

https://github.com/forem/forem/blob/b66da2b4a61e50261b03cdbd016486c63040ff29/app/javascript/topNavigation/utilities.js#L21-L42

**To Reproduce**

1. Using touch on mobile, or the ENTER key after having focused on your avatar in the top menu, the member navigation menu will open and close as expected.
2. Navigate to a new page. It no longer opens.
3. Navigate to another page. It's working again as expected.
 
**Expected behavior**

The member navigation menu should always be able to open/close.

**Screenshots**

https://user-images.githubusercontent.com/833231/114740505-e6fbc380-9d17-11eb-986b-8ff4a7dd264a.mp4

**Desktop (please complete the following information):**

- OS, version: N/A
- Browser, version: N/A

**Smartphone (please complete the following information):**

- Device: N/A
- OS, version: N/A
- Browser, version: N/A

**Additional context**

### PR DESCRIPTION
**Pull request by nickytonline**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Fixes an issue where you could only open the member navigation menu on the initial load of the sire and only on every second page load.

## Related Tickets & Documents

Close #13399

## QA Instructions, Screenshots, Recordings

Keyboard navigation and then it shows mousing over.

https://user-images.githubusercontent.com/833231/115334329-36ebe780-a169-11eb-8c14-128325830168.mp4

### Keyboard navigation

1. Load the site, http://localhost:3000
2. Use the tab key to give focus to the avatar of the logged on user in the top navigation.
3. Press <kbd>ENTER</kbd>.
4. The member navigation menu opens.
5. Press <kbd>ESC</kbd> to close the member navigation menu.
6. Press <kbd>SHIFT</kbd> + <kbd>TAB</kbd> to five focus to the notifications icon and press <kbd>ENTER</kbd> to load the notifications page.
7. Repeat steps 1-4 and the member navigation menu should open still.

### Touch on mobile

1. Follow the same steps as the Keyboard navigation section, except use touch.
2. Navigating to different pages in the site and then clicking on the logged on user's avatar will always open the member navigation menu.

If you need help testing on mobile, speak to @nickytonline , @aitchiss, or @fdoxyz.

### UI accessibility concerns?

Fixes an accessbility issue where the user could no longer navigate to the member navigation menu when switching pages via InstantClick using keyboard navigation or touch (mobile).

## Added tests?

- [ ] Yes
- [x] No, and this is why: This issue only occurs via keyboard navigation or on mobile and I'm not sure if this makes sense as an end to end test. Still contemplating...
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [x] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

A Guinea pig from the movie Animal Crackers saying "Aha! I've got it!"

### CODE REVIEW

File: app/javascript/packs/base.jsx [hunk 1]
```diff
@@ -96,15 +96,17 @@ function initializeNav() {
...
-  const memberMenu = document.getElementById('crayons-header__menu');
-  const menuNavButton = document.getElementById('member-menu-button');
   const moreMenus = [...document.getElementsByClassName('js-nav-more-trigger')];
 
   setCurrentPageIconLink(currentPage, getPageEntries());
   initializeMobileMenu(menuTriggers, moreMenus);
-  initializeTouchDevice(memberMenu, menuNavButton);
 }
 
+const memberMenu = document.getElementById('crayons-header__menu');
```
Comment (nickytonline) [inline app/javascript/packs/base.jsx:105]: So the fix is to only run `initializeTouchDevice` when the page loads. When it was always being  loaded via InstantClick page changes, it kept adding event listeners each time to the member navigation button which is what caused the bug and also was attaching _n_ events where the number of pages navigated to was _n_.

Comment (aitchiss) [reply app/javascript/packs/base.jsx:105]: we have this in `initializeTouchDevice`:

```js
// Use a named function instead of anonymous so duplicate event handlers are discarded
        menuNavButton.addEventListener('click', (_event) => {
          toggleHeaderMenu(memberTopMenu, menuNavButton);
        });
```

I guess it wasn't ignoring duplicates as we _are_ using an anonymous function as the event listener. In any case, the way you've fixed it makes more sense to me, by only initializing once. But let's remove that comment on line 62 as well?

**Review by aitchiss — COMMENTED** [review]
I tested this on android 11.0 and all looks good. I noticed a small issue on desktop though:

- Using either keyboard or mouse, open the menu by clicking the profile image
- Click a link in the menu (keyboard or mouse)
- New page loads but menu doesn't dismiss

Mouse:

https://user-images.githubusercontent.com/20773163/114839698-fc332980-9dcd-11eb-9f0b-ed794d4a73b9.mp4

Keyboard:

https://user-images.githubusercontent.com/20773163/114839715-01907400-9dce-11eb-816b-3be430eb782f.mp4

**Comment by nickytonline** [comment]
> I tested this on android 11.0 and all looks good. I noticed a small issue on desktop though:
> 
> 
> 
> - Using either keyboard or mouse, open the menu by clicking the profile image
> 
> - Click a link in the menu (keyboard or mouse)
> 
> - New page loads but menu doesn't dismiss
> 

I got into the weeds and forgot to test actually clicking stuff in the menu. 🙈

**Review by nickytonline — COMMENTED** [review]
@fdoxyz and @aitchiss, I've reworked this a bit more and now it's in a good state. I've retested on desktop, and iPhone, plus accessibility checks, e.g. `aria-expanded` state.

Note: @aitchiss, the way it's implemented, it toggles `aria-expanded` on mouseover/mouseout.

**Comment by nickytonline** [comment]
> I tested this on android 11.0 and all looks good. I noticed a small issue on desktop though:
> 
> * Using either keyboard or mouse, open the menu by clicking the profile image
> * Click a link in the menu (keyboard or mouse)
> * New page loads but menu doesn't dismiss
> 

This is all fixed @aitchiss.

File: app/javascript/topNavigation/__tests__/utilities.test.js [hunk 2]
```diff
@@ -142,10 +142,10 @@ describe('top navigation utilitities', () => {
     });
   });
 
-  describe('initializeTouchDevice', () => {
+  describe('initializeMemberMenu', () => {
     const initialMenuHTML = `
       <div class="crayons-header__menu" id="crayons-header__menu" data-testid="menu-dropdown">
-        <button type="button" class="crayons-header__menu__trigger" id="member-menu-button" aria-label="Navigation menu">
+        <button type="button" class="crayons-header__menu__trigger" id="member-menu-button" aria-expanded="false" aria-label="Navigation menu">
```
Comment (nickytonline) [inline app/javascript/topNavigation/__tests__/utilities.test.js:148]: The `aria-expanded` attribute needs to start off as `"false"` in the markup, like in the real app.

This should be converted to an E2E tests as mentioned, but I will do this at a later time as the tests are still relatively decent.

File: app/views/layouts/_top_bar.html.erb [hunk 3]
```diff
@@ -49,7 +49,7 @@
         </a>
 
         <div class="crayons-header__menu" id="crayons-header__menu">
-          <button type="button" class="crayons-header__menu__trigger" id="member-menu-button" aria-label="Navigation menu">
+          <button type="button" class="crayons-header__menu__trigger" id="member-menu-button" aria-label="Navigation menu" aria-expanded="false">
```
Comment (nickytonline) [inline app/views/layouts/_top_bar.html.erb:52]: `aria-expanded` needs to start off as `"false"`. From there, interactions from JS take over.

File: app/javascript/topNavigation/utilities.js [hunk 4]
```diff
@@ -1,107 +1,103 @@
...
+      menuNavButton.setAttribute('aria-expanded', 'true');
+    });
+  } else {
+    memberTopMenu.addEventListener('mouseover', (_event) => {
+      classList.add('desktop');
+      openHeaderMenu(memberTopMenu, menuNavButton);
+    });
+    memberTopMenu.addEventListener('mouseout', (_event) => {
       closeHeaderMenu(memberTopMenu, menuNavButton);
+    });
```
Comment (aitchiss) [inline app/javascript/topNavigation/utilities.js:77]: One thing I noticed while testing this on desktop, is that if I open the menu with the keyboard, then move my mouse so that it moves over and away from the menu, it collapses the menu again:

https://user-images.githubusercontent.com/20773163/115363488-6d058780-a1ba-11eb-9d0b-e9586f05e739.mp4

When this happens, the menuNavButton isn't refocused on close. I think probably we only want to close the menu on 'mouseout' if it wasn't opened by keyboard... or at a minimum make sure the the menuNavButton is refocused when it does close.

I also noticed that I can no longer click the menuNavButton on desktop and have the menu stay visible until I click an option or away from it (only works on hover now). Are we comfortable losing that feature? I'm not sure I have a strong opinion on it, but it is different than the previous functionality.

**Review by aitchiss — COMMENTED** [review]
A couple of questions around the new implementation. I tested this on android 11.0 as well, and it mostly works as expected - just one small edge case where if I:

- Go to any page other than the home page
- Open the menu
- Click the logo in the top bar to navigate home
- Route changes but menu doesn't close

**Comment by nickytonline** [comment]
> A couple of questions around the new implementation. I tested this on android 11.0 as well, and it mostly works as expected - just one small edge case where if I:
> 
> 
> 
> - Go to any page other than the home page
> 
> - Open the menu
> 
> - Click the logo in the top bar to navigate home
> 
> - Route changes but menu doesn't close
> 
> 

I'll check this out. Thanks for testing!

File: app/javascript/topNavigation/utilities.js (hunk 4 above)
Comment (nickytonline) [reply app/javascript/topNavigation/utilities.js:77]: > One thing I noticed while testing this on desktop, is that if I open the menu with the keyboard, then move my mouse so that it moves over and away from the menu, it collapses the menu again:
> 
> 
> 
> https://user-images.githubusercontent.com/20773163/115363488-6d058780-a1ba-11eb-9d0b-e9586f05e739.mp4
> 
> 
> 
> When this happens, the menuNavButton isn't refocused on close. I think probably we only want to close the menu on 'mouseout' if it wasn't opened by keyboard... or at a minimum make sure the the menuNavButton is refocused when it does close.
> 
> 
> 
> I also noticed that I can no longer click the menuNavButton on desktop and have the menu stay visible until I click an option or away from it (only works on hover now). Are we comfortable losing that feature? I'm not sure I have a strong opinion on it, but it is different than the previous functionality.

Definitely not comfortable losing that feature. I'll take a peek at this too.

Comment (nickytonline) [reply app/javascript/topNavigation/utilities.js:78]: This has been fixed. I actually noticed that in production we do not focus on the menu nav button after clicking on a link in the menu or losing focus on the menu.

**Comment by nickytonline** [comment]
> > A couple of questions around the new implementation. I tested this on android 11.0 as well, and it mostly works as expected - just one small edge case where if I:
> > 
> > * Go to any page other than the home page
> > * Open the menu
> > * Click the logo in the top bar to navigate home
> > * Route changes but menu doesn't close
> 
> I'll check this out. Thanks for testing!

Alright, this is sorted out now as well. Let me know if anything else pops up.

**Comment by fdoxyz** [comment]
I gave this a try on mobile browser and mobile app but wasn't able to open the menu at all. Maybe something changed and could also be reflected in the failing Cypress spec.

Also note that I wasn't able to use the menu on Chrome for Desktop via Devtools mobile view. I saw this error but it feels unrelated:

Screen Shot 2021-04-20 at 16 37 34

**Comment by nickytonline** [comment]
> I gave this a try on mobile browser and mobile app but wasn't able to open the menu at all. Maybe something changed which could also be reflected in the failing Cypress spec.
> 
> Also note that I wasn't able to use the menu on Chrome for Desktop via Devtools mobile view. I saw this error but it feels unrelated:
> 
> Screen Shot 2021-04-20 at 16 37 34

Hmm. I'll take a peek to see what's up.

**Review by fdoxyz — APPROVED** [review]
It's working great for me now. Thanks a lot for the refactor here 🙌 

I tested on iOS + Android + Chrome on macOS. Also played around with the keyboard and felt like it was working well, but I'll probably defer to @aitchiss any final call on that regard.

**Comment by aitchiss** [comment]
Noticed a couple of strange things...

1. I still can't leave the menu open if I mouse away from it. 

In the current live site, if I'm using a mouse, I can either hover the menu (in which case it disappears when I move the mouse away), or I can click the menuNavButton and the menu stays open regardless of where my mouse goes (until I click away, click a link, or click the menuNavButton again).

Live site:

https://user-images.githubusercontent.com/20773163/115529026-76f6bb80-a28a-11eb-96b4-e94e584b960c.mp4

Current PR:

https://user-images.githubusercontent.com/20773163/115529087-84ac4100-a28a-11eb-80d7-4aa4528848bd.mp4

2. The menuNavButton seems to be stealing focus from the search bar. It works OK if I use the keyboard to navigate to it, but if I click the search bar, it immediately loses focus. The focus is transferred to the menuNavButton -

https://user-images.githubusercontent.com/20773163/115529270-aad1e100-a28a-11eb-8e6f-a6047c937603.mp4

**Comment by nickytonline** [comment]
> Noticed a couple of strange things...
> 
> 1. I still can't leave the menu open if I mouse away from it.
> 
> In the current live site, if I'm using a mouse, I can either hover the menu (in which case it disappears when I move the mouse away), or I can click the menuNavButton and the menu stays open regardless of where my mouse goes (until I click away, click a link, or click the menuNavButton again).
> 
> Live site:
> 
>  CleanShot.2021-04-21.at.10.14.49.mp4 
> Current PR:
> 
>  CleanShot.2021-04-21.at.10.09.56.mp4 
> 1. The menuNavButton seems to be stealing focus from the search bar. It works OK if I use the keyboard to navigate to it, but if I click the search bar, it immediately loses focus. The focus is transferred to the menuNavButton -
> 
>  CleanShot.2021-04-21.at.10.12.03.mp4

I know what's going on with #2, will look into #1.

**Review by rhymes — COMMENTED** [review]
The QA steps work!

There's one tiny detail that I noticed:

after "shift tab" to go back from the closed avatar menu and the notification icon, when I press enter, the notification page opens but then it selects the avatar menu.


https://user-images.githubusercontent.com/146201/115549601-1dea5000-a2a9-11eb-9518-6421a2466ee6.mov

**Comment by nickytonline** [comment]
> The QA steps work!
> 
> 
> 
> There's one tiny detail that I noticed:
> 
> 
> 
> after "shift tab" to go back from the closed avatar menu and the notification icon, when I press enter, the notification page opens but then it selects the avatar menu.
>


@rhymes, i have a fix coming, that I'll post later today. Thanks for reviewing!

**Comment by nickytonline** [comment]
Alright, everything should hopefully be sorted now @aitchiss. Feel free to take this for a spin again when you have a second. Thanks!

**Comment by fdoxyz** [comment]
Just for confirmation, I just ran this again on Android + iOS and everything still looking from this end 👍

**Review by aitchiss — APPROVED** [review]
All looking good to me! 🙌
