### PR TITLE
Fix bug: Unable to unfollow topics

### LINKED ISSUE #19517: Unable to unfollow topics
Unable to "unfollow" tags.
Clicking the *Following* button does apparently unfollow a tag, but then, if I refresh the page, tags I unfollowed are still there.

### PR DESCRIPTION
**Pull request by jaw6**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Unfollowing tags isn't working as expected. The problem turns out to be with caching.

## Related Tickets & Documents

- Closes #19517 

## QA Instructions, Screenshots, Recordings

`rails dev:cache`

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: jest hates me
- [ ] I need help with writing tests

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

File: app/controllers/follows_controller.rb [hunk 1]
```diff
@@ -108,10 +110,19 @@ def follow(followable, need_notification: false)
     I18n.t("follows_controller.already_followed")
   end
 
+
+  def clear_followed_tag_caches
+    # Clear the followed_tags model cache, which is nested inside the async_info cache
+    Rails.cache.delete("#{current_user.cache_key}-#{current_user.last_followed_at&.rfc3339}/followed_tags")
```
Comment (jaw6) [inline app/controllers/follows_controller.rb:116]: This is the _core_ problem — this cache [lives for most of a day](https://github.com/forem/forem/blob/main/app/decorators/user_decorator.rb#L47), so if it isn't cleared, it will appear for all intents & purposes that the following has not changed.

File: app/javascript/packs/followButtons.js [hunk 2]
```diff
@@ -409,33 +411,38 @@ function initializeNonUserFollowButtons() {
...
-      button.dataset.fetched = true;
-      const initialButtonFollowState = followedTagIds.has(buttonInfo.id)
-        ? 'true'
-        : 'false';
-      updateInitialButtonUI(initialButtonFollowState, button);
-    } else {
-      fetchFollowButtonStatus(button, buttonInfo);
-    }
-  });
+  waitOnBaseData()
```
Comment (jaw6) [inline app/javascript/packs/followButtons.js:414]: So, we also have an odd race-condition type of thing here, where the JavaScript that initializes the `follow button` might finish before the `/async_info/base_data` finishes. When that happens (which, locally, was almost every time), stale data is pulled out of our [browser store cache](https://github.com/forem/forem/blob/main/app/assets/javascripts/utilities/browserStoreCache.js), _before_ that caches is swept by the `async_info` process. A refresh will 'fix' things, but we shouldn't have to refresh twice every time we change our followings. We've had [`waitOnBaseData` for 2+ years](https://github.com/forem/forem/blame/main/app/javascript/utilities/waitOnBaseData.js), but for some reason aren't using it widely. One downside here: we _will_ see a _slightly_ longer delay where _all_ the buttons look like "not following" state, but I don't see a way to fix that without a massive refactor.

**Comment by mirie** [comment]
@Ridhwana / @maestromac can you take a pass on this one?
