### PR TITLE
Revise editor publish logic

### LINKED ISSUE #12349: Revise Publish Logic for a Post
**Describe the bug**

Not a bug per se, but as we discovered in #12288, the publishing logic is a little weird.

From @citizen428 in #12288:

> To be honest, I wasn't quite sure about the rationale around this comment. Should this function touch the `published` state at all?
> 
> This function is used as error callback (`errorCb`) in `submitArticle` (defined in (`app/javascript/article-form/actions.js`):
> 
> ```js
> // If there is an error and the method is POST, we know they are trying to publish.
> errorCb(response, method === 'POST');
> ```
> 
> I do somewhat get the idea behind this, but it (a) doesn't seem to properly take drafts into account and (b) intuitively feels wrong since the article won't in fact be published if it fails validation, even if we set this attribute because it won't save.

And my response:

I agree on both counts. That logic should probably be revisited in another PR.

Also looking at the publish logic

https://github.com/forem/forem/blob/c2c1366a4ddc452f9d7e587d1b930391acbe0c06/app/javascript/article-form/articleForm.jsx#L207-L213

`setState` is not immediate and it's bad practice to mutate state like so `state.published` as there are no guarantees. That should probably be reworked as well.

_Originally posted by @nickytonline in https://github.com/forem/forem/pull/12288#r560278434_

### PR DESCRIPTION
**Pull request by aitchiss**
## What type of PR is this? (check all applicable)

- [X] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This code was working, but as noted in #12349 it was a bit _funky_ and difficult to understand why it was doing certain things.

I've refactored this area so that:

- We don't touch the 'published' state until the outcome of the network request is known 
- If the network request fails, no change needs to be made to the 'published' state (since we didn't optimistically update it in the first place)
- I removed a 'failure callback' that was never passed in to the `submitArticle` function. Instead, I've replaced it with the general error callback which can be used for the same purpose.

I've added Cypress tests to cover the scenarios of draft/publish for new/existing posts with a variety of success/error situations.

## Related Tickets & Documents

Closes #12349

## QA Instructions, Screenshots, Recordings

For the most part this should be captured by the new Cypress tests, but generally we want to make sure that for **both versions** of the editor:

- Publishing a post works
- Saving a draft works
- Errors on publishing a post or saving a draft are handled (e.g. trigger a parsing error by entering an invalid liquid tag like `{% tag %}` in the content

The V2 editor has a slightly different set of submit options for editing a previously saved draft vs published post. Check that:

- when I edit a published post and I trigger an error (as above, or blocking the `/articles` network request in devtools), the button at the bottom of the page is still "Save changes" and not "Publish"
- when I do the same for a previously saved draft and either click "Publish" or "Save draft" (test both), when the request fails, I still see "Publish" / "Save draft" buttons and not "Save changes" 

In all cases we can double check that the user's dashboard shows that a post hasn't been accidentally changed to draft/published when it shouldn't have been

### UI accessibility concerns?

N/A

## Added/updated tests?

- [X] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://admin.forem.com/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [X] This change does not need to be communicated, and this is why not: no change to functionality

## [optional] What gif best describes this PR or how it makes you feel?

Marge Simpson says "I redecorated!"

### CODE REVIEW

**Review by nickytonline — APPROVED** [review]
Thanks for making the change @aitchiss! ✨

File: app/javascript/article-form/actions.js [hunk 1]
```diff
@@ -44,7 +44,7 @@ function processPayload(payload) {
   return neededPayload;
 }
 
-export function submitArticle(payload, clearStorage, errorCb, failureCb) {
+export function submitArticle(payload, clearStorage, successCb, errorCb) {
```
Comment (rhymes) [inline app/javascript/article-form/actions.js:47]: Could these params become keyword arguments? With default empty callbacks, so that it can read something like:

```js
submitArticle({
 payload: blah blah
 onSuccess: () => this.setState({ published: true, submitting: false }),
})
```

so on and so forth.

Comment (nickytonline) [reply app/javascript/article-form/actions.js:47]: Good call @rhymes. I missed that.

Comment (aitchiss) [reply app/javascript/article-form/actions.js:47]: Yeah that would be nicer - I'll do that 👍

**Review by citizen428 — APPROVED** [review]
🚀
