### PR TITLE
Fixing design issues with multiple reactions

### LINKED ISSUE #19008: Multiple reactions V1 - Tracking issue
This issue is tracking a variety of bugs being reported in the [multiple reactions](https://github.com/forem/forem/issues/18808) internal testing. 

### Launch blocking issues:
* [x] Mobile view: Issues with long tap & text select
* [x] Mobile view: Count is blue?
* [x] Mobile view: Padding/margins (@lboogie04)
* [x] Screen ~600px, drawer should be above
* [x] Dark mode: drawer background highlight for active (@rt4914 )
* [ ] `next` `/notifications` needs new icons
* [x] `readinglist` should not toggle drawer button (@rt4914)
* [x] Remove dark circle highlight for drawer button+readinglist (@rt4914)
* [x] Remove `Add Reaction` tooltip [Reference](https://github.com/forem/forem/issues/19008#issuecomment-1404344776) (@rt4914)

guide

### Non-blocking:
* [ ] Drawer could close faster when scrolling?
* [ ] Counter styling mismatch between drawer / comment / readinglist
* [ ] Timing issues on front-end when multiple reactions happen quickly
* [ ] Element alignment on `#index`
* [ ] `#index` colors (needs SVG unique)

`cc` @mirie @anujbhavsar96 @benhalpern @pkfrank 
:link: [Figma v1.1](https://www.figma.com/file/Rl50gxO5BHioRC3nUoRQ7M/Reactions-%E2%9D%A4%EF%B8%8F?node-id=988%3A3192), [feedback](https://www.figma.com/file/Rl50gxO5BHioRC3nUoRQ7M/Reactions-%E2%9D%A4%EF%B8%8F?node-id=807%3A906&t=5uLXPS6f6JnmM5JV-0)

### PR DESCRIPTION
**Pull request by jaw6**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Fixing [issues](https://github.com/forem/forem/issues/19008) we're discovering in the [multiple reactions](#18808) testing. (This was originally intended to address a number of issues, but ran into `notifications` and became mostly about `notifications` in the end, with a couple of minor style tweaks.)

Fixes:

* [x] Long tap on mobile selects text, we'd like it to open the drawer instead
* [x] Mobile view: counter is blue text, because of an Apple bug, force it to be `(text color var)`
* [x] New reactions don't render properly on `/notifications` 

Screen Shot 2023-02-01 at 09 29 35

## Related Tickets & Documents

- Related #18808
- Closes #19008

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: so far, design/front-end tweaks
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [x] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

magnifying

### CODE REVIEW

File: app/decorators/notification_decorator.rb [hunk 1]
```diff
@@ -30,4 +32,103 @@ def milestone_count
...
+      aggregated_data.select { |n| n["created_at"] > 24.hours.ago }
+    end
+  end
+
+  def to_model
+    self
+  end
+
+  def to_partial_path
+    return "notifications/#{notifiable_type.downcase}" unless reaction?
```
Comment (jaw6) [inline app/decorators/notification_decorator.rb:49]: So, there's a lot of changes to `NotificationDecorator`, but this is the key change: I wanted to find a way to introduce the new, multiple reactions view code (behind a feature flag), and the way we were rendering notifications was hard to unravel (sometimes `aggregate`, sometimes `single`, sometimes `article` or `comment` but then _actually_ `aggregate`...). I tried to move the old code to one side (`original` file prefix), but tried to find a less-confusing way to specify which notification partial is being rendered. 

I do think this makes the decorator is a bit more complicated than I'd like, but I'd rather have that than have an overly-complicated view (or, in this case: views), so it felt like the right trade-off to me.

File: app/views/notifications/_notifications_list.html.erb [hunk 2]
```diff
@@ -1,17 +1,8 @@
-<% @notifications.each do |notification| %>
+<% render_each_notification_or_error @notifications, error: "notifications/shared/error" do |notification| %>
   <div
     class="mb-2 spec-notification <%= "unseen" unless notification.read? %>"
     data-notification-id="<%= notification.id %>">
-    <%= render notification.notifiable_type.downcase.to_s, notification: notification %>
-  </div>
-
-  <% rescue => e %>
```
Comment (jaw6) [inline app/views/notifications/_notifications_list.html.erb:8]: Just wanted to note the motivation here: `rescue`ing _all_ errors in this way makes debugging very opaque in this area. (Especially when combined with the layers of partials, it took some time to even discover where this was happening.) I figured I could just disable it temporarily, but I also thought there was a good chance I would accidentally commit that change, so tried to find a more robust solution. Long-term, I think we might want a separate environment flag (`debug?` or something?) but I decided that was beyond the scope of this PR (which was supposed to be setting up the new reactions, not really intended as a `notifications` refactor).

File: app/views/notifications/_original_aggregated_reactions.html.erb [hunk 3]
```diff
@@ -0,0 +1,49 @@
+<%# TODO: change to map of IDs %>
```
Comment (jaw6) [inline app/views/notifications/_original_aggregated_reactions.html.erb:1]: Again, I did _not_ change anything in these `original` partials, just re-located them.

File: app/views/notifications/_reaction.html.erb [hunk 4]
```diff
@@ -1,7 +1,2 @@
 <%# missing cache key %>
-<% siblings = notification.json_data["reaction"]["aggregated_siblings"].select { |n| n["created_at"] > 24.hours.ago } %>
-<% if siblings.length == 0 %>
-  <%= render "single_reaction", notification: notification %>
-<% else %>
-  <%= render "aggregated_reactions", notification: notification, siblings: siblings %>
-<% end %>
+<%= notification.inspect %>
```
Comment (jaw6) [inline app/views/notifications/_reaction.html.erb:2]: I _think_ I should delete this file, but I could use a second set of :eyes:

I don't think this gets called anymore (because it should always become a `aggregate` or `single`) but I had a hard time convincing myself (it's hard to prove a negative?)

File: config/locales/views/reactions/en.yml [hunk 5]
```diff
@@ -14,6 +14,8 @@ en:
         lightbulb: Lightbulb
         raised_hands: Raised hands
         rocket: Rocket
+        exploding-head: Exploding head
```
Comment (jaw6) [inline config/locales/views/reactions/en.yml:17]: This is maybe unnecessary (and certainly will be in the long term) but: if we toggle the feature flag on and back off again (a rollback scenario), reactions in the notifications area will throw translation exceptions. (I _think_ those exceptions are handled more smoothly in production, but I'm not confident of that.)

File: spec/decorators/notification_decorator_spec.rb [hunk 6]
```diff
@@ -74,4 +74,119 @@
       expect(notification.decorate.milestone_count).to eq("64")
     end
   end
+
+  describe "reaction to a article" do
```
Comment (jaw6) [inline spec/decorators/notification_decorator_spec.rb:78]: I made a judgement call here to not test some of the `siblings` / `actors` logic in the decorator. I don't feel great about that - I'd like to have more tests - but it's a lot to setup in tests, that setup is pretty brittle (easy to get false confidence, much harder to get right) and - in my opinion - should be part of a larger refactor, later on.

**Review by Ridhwana — COMMENTED** [review]
@jaw6 I haven't fully reviewed this PR as yet, but before I go further I thought I'd get your thoughts on these two issues that I'm seeing:

- https://www.loom.com/share/1f59e76198b54c0baedaa6db9d722472
- https://www.loom.com/share/ddfbfa1b61974bae8dd9621aa8a43586

**Comment by jaw6** [comment]
> @jaw6 I haven't fully reviewed this PR as yet, but before I go further I thought I'd get your thoughts on these two issues that I'm seeing:
> 
>     * https://www.loom.com/share/1f59e76198b54c0baedaa6db9d722472
> 
>     * https://www.loom.com/share/ddfbfa1b61974bae8dd9621aa8a43586

@Ridhwana Thank you, this is great! It looks like, in the first loom, that `force_unique` isn't working, so I need to figure out what's up there ("works on my machine", but... that's not really an answer). In the second loom, there really _should_ be a visible icon -- and the `heart` should be shown for any `notifications` that are leftover when the feature flag is disabled. You aren't wrong, it's not quite working properly, this is great feedback, thank you!

**Review by Ridhwana — APPROVED** [review]
Looked through the code and tested it loaclly, it works well, thank you @jaw6!

File: app/decorators/notification_decorator.rb (hunk 1 above)
Comment (jaw6) [reply app/decorators/notification_decorator.rb:56]: I attempted to [write a temporary comment here](https://github.com/forem/forem/pull/19020/commits/63beeec7fbef086fcee4226f5d0ed2bedc2c4bfb).

Comment (maestromac) [reply app/decorators/notification_decorator.rb:56]: Love this refactor!

File: app/helpers/notifications_helper.rb [hunk 7]
```diff
@@ -9,8 +9,35 @@ module NotificationsHelper
...
+  end
+
+  def render_each_notification_or_error(notifications, error:, &block)
+    notifications.each do |notification|
+      concat render_notification_or_error(notification, error: error, &block)
+    end
+  end
+
+  def render_notification_or_error(notification, error:)
+    capture { yield(notification) }
```
Comment (maestromac) [inline app/helpers/notifications_helper.rb:35]: TIL!

**Review by maestromac — APPROVED** [review]
This is some top-notch code. LGTM!
