### PR TITLE
Prevent focus stealing caused by dropdown listeners not being cleaned up

### LINKED ISSUE #14030: Dropdown click outside and keyup listeners are not being properly detached
**Describe the bug**

Dropdowns initialized with `initializeDropdown` in `dropdownUtils.js` are intended to detach click outside and keyup listeners when the dropdown is closed. However, this isn't happening as expected, causing additional listeners to continue to be added and active between page views.

For the most part, the impact is minimal apart from creating a strange visual effect where the dropdown button is focused on returning to the page. For screen reader users and user utilising keyboard navigation however, the impact is more critical as focus is stolen, preventing the page change being announced fully and the keyboard focus position being reset properly.

**To Reproduce**

- Go to a post which has comments
- Open and close the dropdown on one of the comments
- Go back to the home page
- Return to the same post
- Notice that if you scroll down to the comment, the dropdown menu button is focused

**Expected behavior**

Click outside and keyup listeners should be removed:

- when the dropdown is closed
- when the user leaves the page (if the dropdown is open when they leave)
- focus shouldn't be 'stolen' when a user arrives back on a page they previously visited

**Screenshots**

https://user-images.githubusercontent.com/20773163/122730780-86868680-d272-11eb-90dc-da486bc980ce.mp4

### PR DESCRIPTION
**Pull request by aitchiss**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Dropdowns initialized with `initializeDropdown` in `dropdownUtils.js` are intended to detach click outside and keyup listeners when the dropdown is closed. However, this isn't happening as expected, causing additional listeners to continue to be added and active between page views.

This behavior can be observed in comments:

https://user-images.githubusercontent.com/20773163/122730780-86868680-d272-11eb-90dc-da486bc980ce.mp4

And also (more impactfully) in profile preview cards:

https://user-images.githubusercontent.com/20773163/122770132-0cb7c280-d29d-11eb-9517-dba7e77a5402.mp4

The behavior causes the preview card button to 'steal focus' on every subsequent article view once you have opened one of the preview dropdowns. Visually, the impact is low, but for screen reader users and users who rely on the keyboard to navigate, it's more impactful.

## Related Tickets & Documents

Fixes #14030 

## QA Instructions, Screenshots, Recordings

The affected dropdowns can be found in the following places:
- The three dots menu on comments
- The three dots "share post" options on the article page
- The author byline on the article page (desktop only)
- The three dots menu on user Dashboard articles list (Stats/Archive post)
- The V2 editor "post options" (cog icon) menu

**In each case we want to check:**

- The dropdown opens and closes as before by mouse or keyboard click
- The dropdown closes with Escape press, Tab outside, or click outside
- Once you have opened and closed a dropdown, if you go to another page and then come back to the page you were testing, the dropdown button does not 'steal focus' (i.e. you can't see the visual focus indicator, and if you press Tab, the highlighted item is at the beginning of the page)
- The dropdown continues to function as before on this new page visit

https://user-images.githubusercontent.com/20773163/122771525-6d93ca80-d29e-11eb-9246-fd2f1b57de27.mp4

### UI accessibility concerns?

This fixes an accessibility flaw. The "focus stealing" effect was having the impact that screen reader users would not hear the page change fully announced, and users relying on keyboard navigation would not find focus in the correct part of the page.

## Added/updated tests?

- [X] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [X] This change does not need to be communicated, and this is why not: This bug has not yet been reported by the community, and is currently not very obvious. It is more obvious in the profile preview cards feature, but at the time of this PR, it has not yet been put live.

### CODE REVIEW

**Review by rhymes — APPROVED** [review]

File: app/javascript/utilities/dropdownUtils.js [hunk 1]
```diff
@@ -177,15 +148,17 @@ export const initializeDropdown = ({
...
     } else {
       openDropdown({
         triggerElementId,
         dropdownContentId,
-        onClose,
       });
       onOpen?.();
+
+      document.addEventListener('keyup', keyUpListener);
+      document.addEventListener('click', clickOutsideListener);
```
Comment (nickytonline) [inline app/javascript/utilities/dropdownUtils.js:161]: Refactor (non-blocking): Consider only adding the event listener once so it does not need to be cleaned up in

```javascript
  const onCloseCleanupActions = () => {
    onClose?.();
    document.removeEventListener('keyup', keyUpListener);
    document.removeEventListener('click', clickOutsideListener);
  };
```


```suggestion
      document.addEventListener('click', clickOutsideListener, { once: true ));
```

**Review by nickytonline — APPROVED** [review]
Looks great @aitchiss. I left a refactoring suggestion. 🚢

File: app/javascript/utilities/dropdownUtils.js (hunk 1 above)
Comment (aitchiss) [reply app/javascript/utilities/dropdownUtils.js:161]: I was looking at this - initially I thought it might be ideal but sometimes we need the event listener to fire more than once - e.g. if a user clicks inside of the dropdown content I think `{ once: true }` would remove the listener, but we'd want it to stay attached 🤔

Comment (nickytonline) [reply app/javascript/utilities/dropdownUtils.js:161]: Ahh, good point. 😎

Comment (aitchiss) [reply app/javascript/utilities/dropdownUtils.js:161]: I really wanted to use it 😂  😭
