### PR TITLE
Let override of ToS and CoC show in onboarding

### LINKED ISSUE #15296: _terms_text.html does not update when /terms is overwritten
**Describe the bug**

When a Forem Admin overwrites the default page `/terms`, they would expect that this would be update the Terms of Use  displayed during the New User Onboarding (on the modal page that new users are requested to confirm they have read and agreed to the Terms, they can click on linked text to view the Terms):
New User Onboarding modal showing link to Terms

However, the Terms displayed during onboarding are pulled from `_terms_text.html` which doesn't update when `/terms` is overwritten, so the updated Terms of Use for the Forem aren't available to a new user before they sign up.

**To Reproduce**

1. Overwrite default `/terms` page on a Forem
2. Navigate to `/onboarding` or sign up as a new user
3. Click on **Terms of Use** link text (as seen in screenshot above)
4. Review **Terms of Use**

**Expected behavior**

The previewed Terms of Use that new users read prior to confirming their sign up match the latest `/terms` text.

**Additional context**

This was reported to us by a Forem Cloud partner who updated their contact email address in the Terms and other pages on their site, due to all Forem Cloud partners defaulting to the same email address. In this situation, it's important but not vitally urgent. 

Typically, this bug might be more problematic if someone has deviated extensively from the default Terms - in which case there could be legal implications for not providing new users with the true Terms of Use that they're consenting to.

### PR DESCRIPTION
**Pull request by jeremyf**
## What type of PR is this? (check all applicable)

- [x] Bug Fix

## Description

Prior to this commit any changes to the terms or code of conduct were
not reflected in the onboarding links.

With this commit, I'm leveraging a newly created method that first
checks if there's a page for the given slug.  If there is, use that
page's copy.

## Related Tickets & Documents

Closes #15296

## QA Instructions, Screenshots, Recordings

To test:

- Overwrite default /terms page on a Forem
- Navigate to /onboarding or sign up as a new user
- Click on Terms of Use link text
- Review Terms of Use

## Added/updated tests?

- [x] Yes

## [Forem core team only] How will this change be communicated?

- [x] I will share this change internally with the appropriate teams

### CODE REVIEW

File: app/models/page.rb [hunk 1]
```diff
@@ -17,6 +21,28 @@ class Page < ApplicationRecord
...
+  #
+  # @todo Do we want to only allow certain slugs?
+  #
+  # rubocop:disable Rails/OutputSafety
+  def self.render_safe_html_for(slug:)
+    page = find_by(slug: slug)
+    if page
+      page.processed_html.html_safe
+    else
+      yield
```
Comment (djuber) [inline app/models/page.rb:41]: ruby style question: this `yield` assumes a block was given.
Does it make sense to add &block to the parameter list (in case I'm too lazy to read your documentation comment immediately before, but smart enough to have looked at the method definition). I don't know that we do that anywhere else.
Should we have any fallback behavior if a block was not given?

Is there an advantage or future use case that passing a block here enables, or are we always going to pass a block calls render on a fixed view identifier? Could we pass a string fallback_view like "coc-text" and call `render fallback_view` directly?

**Review by djuber — APPROVED** [review]

File: app/models/page.rb (hunk 1 above)
Comment (jeremyf) [reply app/models/page.rb:41]: I had done some consideration regarding a fallback option.  I really didn't like any of them.  In part because the model doesn't have the view context, and I'd prefer to not pass that in.

I think we could replace `yield` with `block.call` and document that it's almost certainly expected.

I can add a test stating if we don't find a slug and don't pass a block, we raise an exception.  That seems like a clearer statement of interaction.

Comment (djuber) [reply app/models/page.rb:43]: >  the model doesn't have the view context

ah - you can't _just_ call `render`, we're using the block as a closure to capture the surrounding context. Thanks!

**Review by aitchiss — APPROVED** [review]
Tested locally, and it works great!
