### PR TITLE
[15 minute fix] Remove secondary logo

### LINKED ISSUE #13586: Remove secondary_logo field from SiteConfig and Related Code ✂️
## Summary

Admins are a bit confused when it comes to providing a secondary_logo. We already have a field for providing logo and this one is "secondary" which means it's basically an alternative version of the logo. But admins can't really tell WHY we ask them to provide it and WHERE it would be used. Communities often hardly have one logo, not even mention a secondary one :). For this reason we are removing the secondary_logo as a configurable option and replacing the current use places for it with the regular logo. 

- [ ] Remove secondary_logo field and code
- [ ] Replace all places that use the secondary_logo with main logo (logo_png or logo_svg)
- [ ] Communicate this change via the changelog. 

## Additional Context

It is "inspired" by the the rough [roll out plan for Starter Pack](https://docs.google.com/document/d/1facy0-UXlUPrzpll8TAM-MNjZiwVbO1vepphuE6a-ek/edit).
Product approved stage 0: https://github.com/forem/rfcs/issues/208

### PR DESCRIPTION
**Pull request by citizen428**
## What type of PR is this? (check all applicable)

- [X] Refactor ✂

## Description

I needed a break from my other `SiteConfig` work, so decided to tackle this in between tasks.

## Related Tickets & Documents

Closes #13586

## QA Instructions, Screenshots, Recordings

Specs should be green. Not sure about any manual QA steps but they don't seem necessary.

### UI accessibility concerns?

None

## Added tests?

- [X] Updated existing ones

## [Forem core team only] How will this change be communicated?

- [X] I will share this change in a [Changelog](https://forem.dev/t/changelog) or in a [forem.dev](http://forem.dev) post

### CODE REVIEW

File: app/helpers/application_helper.rb [hunk 1]
```diff
@@ -163,10 +163,6 @@ def logo_svg
     end
   end
 
-  def safe_logo_url(logo)
```
Comment (citizen428) [inline app/helpers/application_helper.rb:166]: This helper was only used to wrap `SiteConfig.secondary_logo` so it can be removed now. All call sites have been changed to directly use `SiteConfig.logo_png`.

File: lib/data_update_scripts/20210430043750_remove_site_config_secondary_logo.rb [hunk 2]
```diff
@@ -0,0 +1,7 @@
+module DataUpdateScripts
+  class RemoveSiteConfigSecondaryLogo
+    def run
+      SiteConfig.destroy_by(var: "secondary_logo_url")
```
Comment (citizen428) [inline lib/data_update_scripts/20210430043750_remove_site_config_secondary_logo.rb:4]: I decided to also remove the variable from the database, no need to keep it around if we're not using it. I can remove this or do it in a later PR if people prefer that but I thought it's unlikely that we'll change our mind and bring `secondary_logo` back any time soon.

**Comment by citizen428** [comment]
There's a failing e2e test that I don't think is related to the changes in this PR. I'm about to sign off for the weekend, I'll pick this up on Monday.

**Review by rhymes — APPROVED** [review]
LGTM!

**Review by juliannatetreault — APPROVED** [review]
👋 👋 👋 `secondary_logo`!
