### PR TITLE
Removed ordering of co-authors by id

### LINKED ISSUE #20152: Issues with Ordering Coauthors
**Describe the bug**

Folks are having issues ordering coauthors for posts. 

It's likely that coauthors must be ordered alphabetically by default and the order in which coauthors are entered doesn't matter. If this is the case, it may not be a bug but just an update we should consider.

**To Reproduce**

0. Write and post a test post as yourself + share it under an org
1. Navigate to your user dashboard - https://dev.to/dashboard
2. Use the drop-down menu to the right of the word "Posts" to select your org
3. Navigate to the article you want to experiment with adding co-authors to and click the `...` menu
4. Use the drop-down menu to re-credit the article's author to X and save
5. Refresh the page
6. Go back to the article's menu and add coauthors. (make sure these are not ordered in alphabetical order; also note: you must type in the coauthors' usernames)

**Expected behavior**

Org managers should be able to credit coauthors in whatever order they desire.

**Videos**

Recreation of Coauthor Ordering Issue (Coauthors are Alphabetically Ordered)

https://www.loom.com/share/ba9b60cd56274a02bb2d7080466f9e34?sid=f86aa59c-1ec4-4ca2-ab81-8a229970d957

Failed Recreation of Coauthor Ordering Issue (Can't Have Multiple Authors in a Series)

https://www.loom.com/share/6efbdc2329dd425db6746e0e44e12183?sid=53f2d483-4f96-4925-ac0f-a86752ce24fc

**Additional context**

At first, when I tried to recreate this issue, I failed because multiple authors cannot author a series together. I have a related request here to allow multiple authors to write in the same series - https://github.com/forem/forem/discussions/15320

A helpful org manager pointed this one out to us. They manage posting blog articles on behalf of their team and are trying to fine-tune things so as to give their teammates appropriate credit.

### PR DESCRIPTION
**Pull request by rt4914**
## What type of PR is this? (check all applicable)

- [x] Refactor

## Related Tickets & Documents

- Closes #20152

## QA Instructions, Screenshots, Recordings

[Problem Video](https://www.loom.com/share/b42c868029c14e20b8539b429870f972)
[Solution Video](https://www.loom.com/share/8af22f3c49b8419ebeef95746cd9aec9?sid=1aec3038-7df0-4854-b679-fcfc7a04f8a8)

**How to test this**?
1. Create an organisation
2. Add 2-3 users with different names in that organisation
3. Now create a post under the organisation.
4. Visit dashboard, on right side see a drop-down with `Personal`, change it to your organisation.
5. Click on 3-dots (overflow-icon) for the post that you created which will open the dropdown
6. Now add these newly created users such that you add the user which you created in last as first followed by the other user.
7. Visit this post and just above the title see that the name of the co-authors is mentioned in the exact same order that you mentioned while adding them.

### UI accessibility checklist

No

_For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?
_We encourage you to keep the code coverage percentage at 80% and above._

- [x] No

### CODE REVIEW

File: app/decorators/article_decorator.rb [hunk 1]
```diff
@@ -102,7 +102,8 @@ def co_authors
   end
 
   def co_author_name_and_path
-    co_authors.map do |user|
+    co_author_ids.map do |id|
+      user = User.select(:name, :username).find(id)
```
Comment (filleduchaos) [inline app/decorators/article_decorator.rb:106]:
```suggestion
    User.select(:name, :username).where(id: co_author_ids).in_order_of(:id, co_author_ids).map do |user|
```

This avoids multiple queries instead of one and also avoids an error/crash if the user has been deleted

You can also just change the `co_authors` method to replace `order` with `in_order_of`

**Review by filleduchaos — CHANGES_REQUESTED** [review]

File: app/decorators/article_decorator.rb (hunk 1 above)
Comment (rt4914) [reply app/decorators/article_decorator.rb:106]: Thanks @filleduchaos Applying this suggestion.

**Review by filleduchaos — APPROVED** [review]
🎉 I checked and it's just a flaky spec failing

**Review by benhalpern — APPROVED** [review]
