### PR TITLE
Patching ERB rendering of the data-info JSON

### LINKED ISSUE #15916: Follow button on profile is not working json parse error
**Describe the bug**

When clicking on follow button is not working because of a json parse error

**To Reproduce**

1. go to https://dev.to/stack-labs?signin=true
2. notice that you have in error in the console because of a json parse error
3. click on follow
4. its not working

**Expected behavior**

We should be able to follow

**Screenshots**

Screen Shot 2022-01-01 at 4 18 36 PM

**Desktop (please complete the following information):**

- OS, version: macbook m1 pro max
- Browser, version: chrome latest

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

### PR DESCRIPTION
**Pull request by jeremyf**
## What type of PR is this? (check all applicable)

- [x] Bug Fix

## Description

**This is a third attempt.  I'm pushing it up to see if anything's substantively changed.  I assume that there are broken specs and want to see what to address.**

Prior to this commit, we were somewhat naively rendering Hash style data
attributes in our ERB templates.  By rendering each hash attribute
separately, we were rendering characters that could break the
javascript (e.g. double hack or backslash `"` or `\`).

By moving to this view_object rendering, we leverage Rails's `to_json`
behavior to ensure properly escaped values.  As part of this exercise, I
generalized the method to allow for other places to benefit from this
behavior.

This generalization also helps ensure that we have a more conformant
rendering (e.g. we should always have an :id, :className, and :name
value in our data-info hash).

_Note: I've updated the user's names for Cypress tests as they are more
likely to catch the particular issue than anything else.  I assume that
I'm going to break some cypress tests and will need some help fixing
them._

Closes #15916, #14704

Supersedes #15983

How to test locally:

Assuming you have seeded database (e.g. `rails db:seed`), checkout the
"main" branch.  Then in `rails console` find a user that's written articles:

```ruby
user = Article.last.user

user.update(name: "\\: #{user.name} \"The Awesomest\"")

user.articles.each(&:save)
```

Now, again on the "main" branch, start your application (e.g.,
`bin/startup`).

Then get a logged in and a logged out browser session going.  Open your
web inspector and open console.  Then go to the local instances homepage
(e.g., http://localhost:3000) and look for JS errors.

On the main branch, you should see an exception around
`JSON.parse(button.data.info)` (assuming that the `user`'s article is
rendered on the homepage).

Then go to the user's page (e.g. https://localhost:3000/:user-slug) and
look for JS parse errors.

On this PR's branch (e.g.,
`jeremyf/take-two-at-resolving-gh-15916`)
you shouldn't see those console errors.

More importantly, the Follow buttons should work.

But realistically, there are lots of places where these follow buttons show up,
so consider that I updated the `./db/seeds.rb` and 
`./spec/support/seeds/seeds_e2e.rb` to include some of the scenarios we've found
in the wild regarding usernames.

## Added/updated tests?

- [x] No, and this is why:

## [Forem core team only] How will this change be communicated?

- [x] I will share this change internally with the appropriate teams

### CODE REVIEW

**Comment by jeremyf** [comment]
Reading Note:  I would say follow my testing instructions, but frankly having wrestled with Cypress, JS, ERB, decorators, etc, I think I'd just trust the tests at this point.

It's certainly fixing things.

File: app/assets/javascripts/utilities/buildArticleHTML.js [hunk 1]
```diff
@@ -32,8 +32,8 @@ function buildArticleHTML(article) {
       currentTag = JSON.parse(container.dataset.params).tag;
     }
     if (article.flare_tag && currentTag !== article.flare_tag.name) {
-      flareTag = `<a href="/t/${article.flare_tag.name}"
```
Comment (jeremyf) [inline app/assets/javascripts/utilities/buildArticleHTML.js:35]: This came along as an auto-correct.  Removing blank spaces.

File: app/assets/javascripts/utilities/buildArticleHTML.js [hunk 2]
```diff
@@ -170,6 +170,8 @@ function buildArticleHTML(article) {
     // We only show profile preview cards for Posts
     var isArticle = article.class_name === 'Article';
 
+    // We need to be able to set the data-info hash attribute with escaped characters.
+    var name = article.user.name.replace(/[\\"']/g, '\\$&');
```
Comment (jeremyf) [inline app/assets/javascripts/utilities/buildArticleHTML.js:174]: This is likely a method that we could extract for re-use.

File: app/view_objects/data_info.rb [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+  # @param name [String]
+  # @param kwargs [Hash] any additional attributes to include in the
+  #        JSON object.  In some cases we include a "style" attribute.
+  #
+  # @return [String] JSON formatted string.
+  #
+  # @example
+  #   > DataInfo.to_json(object: User.first, name: "Duane \"The Rock\" Johnson", id: 1, style: "full")
+  #   => "{\"user_id\":1,\"className\":\"User\",\"style\":\"full\",\"name\":\"Duane \\\"The Rock\\\" Johnson\"}"
+  def self.to_json(object:, id: object.id, class_name: object.class_name, name: object.name, **kwargs)
```
Comment (jeremyf) [inline app/view_objects/data_info.rb:27]: I had thought about `class_name: object.try(:class_name) || object.class.name` but I'm prepared for this to just break.

File: app/decorators/article_decorator.rb [hunk 4]
```diff
@@ -1,6 +1,15 @@
 class ArticleDecorator < ApplicationDecorator
   LONG_MARKDOWN_THRESHOLD = 900
 
+  # @return [String] JSON formatted string.
+  #
+  # @example
+  #   > Article.last.decorate.user_data_info_to_json
+  #   => "{\"user_id\":1,\"className\":\"User\",\"style\":\"full\",\"name\":\"Duane \\\"The Rock\\\" Johnson\"}"
+  def user_data_info_to_json
+    DataInfo.to_json(object: cached_user, class_name: "User", id: user_id, style: "full")
```
Comment (jeremyf) [inline app/decorators/article_decorator.rb:10]: Passing "User" may or may not be necessary.  Depends on what that `cached_user` actual is.  Based on #16083 it's likely an `OpenStruct` or a `Articles::CachedEntity`

File: app/helpers/application_helper.rb [hunk 5]
```diff
@@ -126,12 +121,7 @@ def follow_button(followable, style = "full", classes = "")
       name: :button,
       type: :button,
       data: {
-        info: {
-          id: followable.id,
-          className: followable_type,
-          name: followable_name,
-          style: style
-        }
+        info: DataInfo.to_json(object: followable, className: followable_type, style: style)
```
Comment (jeremyf) [inline app/helpers/application_helper.rb:124]: Technically not necessary, but the `DataInfo.to_json` is helping produce consistent attributes in Rails side code.  So why not re-use it.

File: app/models/users/deleted_user.rb [hunk 6]
```diff
@@ -24,6 +24,13 @@ def self.profile_image_url() = nil
     def self.path() = nil
     def self.tag_line() = nil
 
+    # @return [String]
+    #
+    # @see ApplicationRecord#class_name
+    def self.class_name
```
Comment (jeremyf) [inline app/models/users/deleted_user.rb:30]: Because this doesn't inherit from ApplicationRecord.  Also perhaps technically not needed, but added for completeness.

File: app/views/stories/tagged_articles/index.html.erb [hunk 7]
```diff
@@ -24,7 +24,7 @@
               <button
                 id="user-follow-butt"
                 class="crayons-btn follow-action-button"
-                data-info='{"id":<%= @tag.id %>,"className":"Tag", "name": "<%= @tag.pretty_name || @tag.name %>"}'>
+                data-info='<%= DataInfo.to_json(object: @tag, class_name: "Tag", name: @tag.pretty_name || @tag.name) %>'>
```
Comment (jeremyf) [inline app/views/stories/tagged_articles/index.html.erb:27]: We may be able to get away with not passing "Tag" but I've seen both a `Tag` object and `ActsAsTaggableOn::Tag` object come through in my copious amounts of outside looking in debugging.

File: app/views/tags/index.html.erb [hunk 8]
```diff
@@ -45,7 +45,7 @@
           <div class="mt-auto">
             <button
               class="crayons-btn crayons-btn--secondary follow-action-button"
-              data-info='{"id":<%= tag.id %>,"className":"Tag", "followStyle":"secondary", "name": "<%= tag.name %>"}'>
+              data-info='<%= DataInfo.to_json(object: tag, class_name: "Tag", followStyle: "secondary") %>'>
```
Comment (jeremyf) [inline app/views/tags/index.html.erb:48]: We may be able to get away with not passing "Tag" but I've seen both a Tag object and ActsAsTaggableOn::Tag object come through in my copious amounts of outside looking in debugging.  So I'm erring on the side of keeping the class_name.

File: db/seeds.rb [hunk 9]
```diff
@@ -60,8 +60,10 @@
 
   num_users.times do |i|
     fname = Faker::Name.unique.first_name
-    lname = Faker::Name.unique.last_name
-    name = [fname, lname].join(" ")
+    # Including "\\:/" to help with identifying local issues with
```
Comment (jeremyf) [inline db/seeds.rb:63]: Changing how we build the names.  Let's assume everyone in our tests likes to create a bit antics.

File: spec/support/seeds/seeds_e2e.rb [hunk 10]
```diff
@@ -65,7 +65,7 @@
 
 seeder.create_if_doesnt_exist(User, "email", "trusted-user-1@forem.local") do
   user = User.create!(
-    name: "Trusted User 1",
+    name: "Trusted User 1 \\:/",
```
Comment (jeremyf) [inline spec/support/seeds/seeds_e2e.rb:68]: These changes helped me surface failing tests that only Cypress caught.  Looking at this, I'm considering adding quotes around one of these users.

File: spec/models/application_record_spec.rb [hunk 11]
```diff
@@ -8,6 +8,13 @@
     end
   end
 
+  describe "#class_name" do
```
[the remark this answers is not in the document]
Comment (jeremyf) [reply spec/models/application_record_spec.rb:11]: Yup-ish

File: spec/factories/users.rb [hunk 12]
```diff
@@ -7,7 +7,11 @@
   image_path = Rails.root.join("spec/support/fixtures/images/image1.jpeg")
 
   factory :user do
-    name                         { Faker::Name.name }
+    # Creating a name that has includes double quotes and backslashes.
+    # This way we can see if things are parsing correctly.
+    name do
+      "#{Faker::Name.first_name} \"#{Faker::Name.first_name}\" \\:/ #{Faker::Name.last_name}"
```
[the remark this answers is not in the document]
Comment (citizen428) [reply spec/factories/users.rb:13]: I'd probably have made this a trait so we can use the strange-looking name only in specs that need to specifically test for this behavior.

**Review by citizen428 — APPROVED** [review]

**Comment by jeremyf** [comment]
> I'd probably have made this a trait so we can use the strange-looking name only in specs that need to specifically test for this behavior.

I went with this change specifically to see what might break.  These changes prompted a few fixes in the non-Cypress tests.

**Comment by jgaskins** [comment]
@jeremyf Thank you so much for this. This should fix multiple error notices on Honeybadger that resulted from manual, naive JSON generation. :100:
