### PR TITLE
Ensuring an admin can confirm delete a user's post

### LINKED ISSUE #16461: Admin can't delete posts on Forem
**Describe the bug**

Originally discovered on sandbox Forem but able to replicate on other Forems in the fleet.

If an Admin tries to delete a user's post (either by clicking **Delete** on the Manage page by appending `/manage` to the post URL or by clicking **Delete** on a Draft post in the User Dashboard), the `/delete_confirm` page 404s.

@michael-tharrington confirms that he's able to replicate this issue.

**To Reproduce**

When logged in as Admin:

Either
1. Open the post you want to delete
2. Append `/manage` to the post URL
3. Click **Delete** to see `/delete_confirm` page and 404 error.

Or
1. Open the post you want to delete
2. Click on the "Mod Panel" icon in the reactions bar (shield icon)
3. Click on **Unpublish post** at the bottom of the Mod Panel
4. Navigate to the User Dashboard (`/dashboard/username`)
5. Locate the freshly unpublished post in **Draft** state
6. Click **Delete** to see `/delete_confirm` page and 404 error.

**Expected behavior**

I believe we previously saw a page asking to confirm if we wanted to delete the content, but it's tricky to recall now that we don't seem to be able to access this any more. 

Ideal world behaviour: a confirmation modal appears. When confirmed, Admin is returned to User Dashboard (to visually verify the post is deleted) with a notification that matches the style of those seen by Admins when banishing/deleting users, or unpublishing all of a user's posts.

**Screenshots**

[I was recording a video tutorial when I first came across this, so here's the goofy video.](https://www.loom.com/share/b9e9ff128be2429895f838eb70aa1540) - enjoy 😆

### PR DESCRIPTION
**Pull request by jeremyf**
## What type of PR is this? (check all applicable)

- [x] Bug Fix

## Description

Prior to this commit, the admin could delete the post but were blocked
by the "delete confirm".  The blocker was because we scoped the finding
of an article to the current user.

With this commit, the admin should be able to confirm the deletion of an
article.

## Related Tickets & Documents

Closes #16461

## QA Instructions, Screenshots, Recordings

None.  The tests cover this behavior.

### UI accessibility concerns?

None.

## Added/updated tests?

- [x] Yes

## [Forem core team only] How will this change be communicated?

- [x] I will share this change internally with the appropriate teams

### CODE REVIEW

**Comment by djuber** [comment]
does the `authorize @article` check immediately after the query sufficiently ensure only admin + author can delete the post? 

It looks like the scoped query was there from the beginning (initial commit) - the pundit check was added in a [later pr](https://github.com/forem/dev.to_core/pull/466)

**Review by djuber — APPROVED** [review]

File: spec/requests/articles/articles_destroy_spec.rb [hunk 1]
```diff
@@ -8,30 +8,80 @@
...
+    context "when another user attempts to delete someone's article" do
+      let(:other_user) { create(:user) }
+
+      before { sign_in other_user }
+
+      it "raises a policy error" do
+        article = create(:article, user: user)
+        expect do
+          get "#{article.path}/delete_confirm"
+        end.to raise_error(Pundit::NotAuthorizedError)
```
Comment (djuber) [inline spec/requests/articles/articles_destroy_spec.rb:83]: :100: this was what I was looking for - thanks

**Review by Ridhwana — APPROVED** [review]
