### PR TITLE
Article collection cleanup callback

### LINKED ISSUE #18351: There is no way to delete a series name
**Describe the bug**

Currently, if you create a series title, there's no way to remove it.

**To Reproduce**

1. Go to https://dev.to/new
2. Click on the gear icon beside "save draft"
3. Give your series a title and hit done
4. Save draft
5. Try to figure out how to delete the series title (I couldn't see how to do so from the editor nor the dashboard)

**Expected behavior**

There should be a clear way to delete a series title. 

Perhaps a series should have to be completely unpublished in order to remove the title from the list. Also thinking that maybe there should be a way to delete/rename/manage posts under a series from dashboard > series (i.e. https://dev.to/michaeltharrington/series for me)

**Additional context**

Here's a loom video of me trying to figure out how to remove an unused series name from my list:

https://www.loom.com/share/382b40e78e6f4ac9a341482710be3151

### PR DESCRIPTION
**Pull request by fdocr**
## What type of PR is this? (check all applicable)

- [x] Bug Fix

## Description

Fixes a bug that doesn't allow for series to be removed when empty

## Related Tickets & Documents

- Closes #18351

## QA Instructions, Screenshots, Recordings

1. Boot app locally
2. Create an article (Draft or non-draft shouldn't matter)
3. Assign a new series & save article (it must be the only article in the series)
4. Edit again and remove the series + save
5. Edit the article again and the series name should've been removed
   - This can be seen in the dropdown (series name shouldn't be visible)

### UI accessibility concerns?

None

## Added/updated tests?

- [x] Yes, but failing at the moment

## [Forem core team only] How will this change be communicated?

- [x] I will share this change internally with the appropriate teams

## [optional] What gif best describes this PR or how it makes you feel?

go away

### CODE REVIEW

File: app/models/article.rb [hunk 1]
```diff
@@ -613,6 +614,17 @@ def skip_indexing?
 
   private
 
+  def collection_cleanup
+    # Should only check to cleanup if Article was removed from collection
+    return unless saved_change_to_collection_id? && collection_id.nil?
```
Comment (fdocr) [inline app/models/article.rb:619]: The code works when tested locally, but this method/check is always returning `false` inside tests. I found [this SO answer](https://stackoverflow.com/a/60437898/3462026) that mentions `saved_change_to_collection_id` or `saved_change_to_attribute?(:collection_id)` won't work correctly on `after_save` or `after_update`, so `after_commit` needs to be used due to them being wrapped in a transaction.

I attempted all (strongly believe this but might missed one?) permutations of these options, but without any luck. My guess is that the fact the test is running inside a transaction itself (Rspec does this) makes this always return `false`. Happy to push those changes here if anyone feels like that would be better.

I also attempted to move this test to a system (capybara) spec but also without any luck. Any ideas on how to test this would be very welcome!

Comment (jaw6) [reply app/models/article.rb:619]: Maybe you already tried this, but do you have the same result if you move the check into an `if` proc on the `after_save` itself? 

```ruby
after_save :collection_cleanup, if: proc { |article| article.saved_change_to_collection_id && article.collection_id.nil? }
```

Comment (fdocr) [reply app/models/article.rb:619]: Thank's for the suggestion @jaw6! 🙏🏼 

Mac helped me sort out the failing spec which _seemed to be_ caused by a transient property in article factory ([thread here](https://forem-team.slack.com/archives/C7GE84DEJ/p1663195554524339?thread_ts=1663181073.686099&cid=C7GE84DEJ)). Tests working well now 🙌🏼

**Review by jaw6 — APPROVED** [review]

**Review by joshpuetz — APPROVED** [review]
