### PR TITLE
Snackbar error message in comments image upload

### LINKED ISSUE #18368: Snackbar not visible image upload errors in comment editor
**Describe the bug**

Snackbar not visible image upload errors in comment editor

**To Reproduce**

1. Go to any post/article as logged-in user
2. Go to comment editor area
3. Upload a very big image
4. There will be no visible error.

**Expected behavior**

Error snack bar should be visible similar to what happens when same steps are followed in `Create Post`

**Notes**
- For `Post Editor` the [handleImageFailure](https://github.com/forem/forem/blob/4cddc0bc22ee4d78596f00f510cea9f40796833d/app/javascript/article-form/components/EditorBody.jsx#L51) is getting called and is working correctly
- For `Comment Editor` the  [handleImageFailure](https://github.com/forem/forem/blob/3f6cc95f79d6520cc289a0916904615f394e0222/app/javascript/packs/CommentTextArea/CommentTextArea.jsx#L56) is also getting called but is not working correctly.
- We don't need to worry about the error message as it will be handled by `handleImageFailure` function.
- Just focus on making sure that error message is visible.

### PR DESCRIPTION
**Pull request by fdocr**
## What type of PR is this? (check all applicable)

- [x] Bug Fix

## Description

Error messages coming from image uploads in the comments section & Post editor should now appear as Snackbar items

## Related Tickets & Documents

- Closes #18368

## QA Instructions, Screenshots, Recordings

When uploading a large image you can now see the error message pop up in the Snackbar

https://user-images.githubusercontent.com/6045239/192532667-339787ca-9648-4a9d-88be-8159559aa902.mov

https://user-images.githubusercontent.com/6045239/192532680-dd363790-5ec2-4cd8-a9c9-3ae3301fa0f0.mov

### UI accessibility concerns?

None because the Snackbar component has accessibility features built-in.

## Added/updated tests?

- [x] No, and this is why: Adding a large image fixture (> 25MB) feels like an overkill that would add a lot of dead weight to the repository. I haven't been able to stub these functions to mimic this error. Any suggestions would be appreciated and I'd include them in the PR if any.

## [Forem core team only] How will this change be communicated?

- [x] This change does not need to be communicated, and this is why not: Small bug fix

## [optional] What gif best describes this PR or how it makes you feel?

scooby snack

### CODE REVIEW

File: app/javascript/packs/validateFileInputs.js [hunk 1]
```diff
@@ -36,57 +38,39 @@ const PERMITTED_FILE_TYPES = ['image'];
...
+      addCloseButton: true,
+    });
+  } else {
+    // The Post editor (Toolbar component) doesn't have access to
+    // `top.addSnackbarItem` so we need to check to ensure if it's undefined
+    addSnackbarItem({
+      message: msg,
+      addCloseButton: true,
+    });
+  }
```
Comment (fdocr) [inline app/javascript/packs/validateFileInputs.js:63]: Inline comments explain the tricky situation required to call the `addSnackbarItem` function. Always happy to include tweaks or hear suggestions to make this clearer

File: app/javascript/packs/validateFileInputs.js [hunk 2]
```diff
@@ -36,57 +38,39 @@ const PERMITTED_FILE_TYPES = ['image'];
...
  * Handles errors for files that are too large.
  *
  * @param {object} fileSizeErrorHandler - A custom function to be ran after the default error handling
- * @param {HTMLElement} fileInput - An input form field with type of file
  * @param {number} fileSizeMb - The size of the file in MB
  * @param {?number} maxFileSizeMb - The max file size limit in MB
  */
-function handleFileSizeError(
-  fileSizeErrorHandler,
-  fileInput,
```
Comment (fdocr) [inline app/javascript/packs/validateFileInputs.js:83]: `fileInput` element was passed into these error message callback functions so the `<div>` containing the error would be placed correctly, which is no longer needed since the message is being displayed via the Snackbar. A few occurrences of this throughout the PR

**Review by jaw6 — APPROVED** [review]
Looks good to me :+1:

**Review by maestromac — APPROVED** [review]
LGTM!
