### PR TITLE
Trusted user _can_ use moderator comment

### LINKED ISSUE #20138: Trusted Members Currently Cannot Use Trusted Member Response Templates
**Describe the bug**

Trusted Members are able to access and see Trusted Member Response Templates, but when they try to "send as mod" they receive an error. "Insert" works just fine.

Just to explain the difference:
- "send as mod" allows folks to post the message under Sloan
- "insert" allows folks to send the message as themselves and gives them the opportunity to edit the language of the message

Also, Tag Mods and Admin are able to use Trusted Member Response Templates with "send as mod" without issue.

See both videos below under the Videos section for details.

**To Reproduce**

1. Make sure you're logged into an account with the Trusted Member role (but not an Admin or Tag Mod role)
2. Find a post to leave response template on
3. Scroll down to the comments section & click into the input box as if you were writing a comment.
4. Click on the `...` in the comment's toolbar
5. Click on the icon that looks like a book
6. Select a template and click "Send as Mod"
7. See error. 

**Expected behavior**

Trusted Members should be able to use Trusted Member Response Templates via "send as mod"

**Videos**

Trusted Members Can't Currently Use Trusted Member Response Templates

https://www.loom.com/share/a69076ffb0674718a887fd9b5fa0411d

Tag Mods CAN Use Trusted Member Response Templates

https://www.loom.com/share/4f904b5fb5b544408b5a444797d27bdb

**Additional context**

Shoutout to @devarshishimpi who let me know about this one over our Moderator Discord! Appreciate ya! 🙌

### PR DESCRIPTION
**Pull request by jaw6**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Bug is well described in these videos:

Trusted Members Can't Currently Use Trusted Member Response Templates

https://www.loom.com/share/a69076ffb0674718a887fd9b5fa0411d

Tag Mods CAN Use Trusted Member Response Templates

https://www.loom.com/share/4f904b5fb5b544408b5a444797d27bdb

(And on [the original issue](https://github.com/forem/forem/issues/20138).)

Background:

* I worked on response templates [as one of the first PRs I opened](https://github.com/forem/forem/pull/17978) and did not _really_ understand what I was doing
* Also the feature [changed some time later](https://github.com/forem/forem/pull/18601), further reducing the scope for `trusted user`
* As originally implemented, I'm not entirely sure it ever _actually_ allowed a `trusted user` to comment _as_ a moderator (though the button was there?) — given the confusion at the time and the changes later, I'm not sure _anyone_ fully understood how this was supposed to work at the time.

## Related Tickets & Documents

- Closes #20138

## QA Instructions, Screenshots, Recordings

You'll want a user account that has the `trusted` role, without having any other "elevated" roles (`admin`, etc.) and without being assigned to moderate any individual tags. 

## Added/updated tests?

- [x] Yes
- [ ] No, and this is why:
- [ ] I need help with writing tests

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

`cc` @michael-tharrington and @devarshishimpi who initially reported the bug

### CODE REVIEW

**Comment by mirie** [comment]
cc @michael-tharrington as FYI!

File: app/policies/comment_policy.rb [hunk 1]
```diff
@@ -80,6 +80,10 @@ def permitted_attributes_for_moderator_create
 
   private
 
+  def user_trusted?
+    Authorizer.for(user: user).accesses_mod_response_templates?
+  end
+
```
Comment (filleduchaos) [inline app/policies/comment_policy.rb:86]: I'm a little confused - why not just `user.trusted?` here? Or rather as I understand the implementation of [`accesses_mod_response_templates?`](https://github.com/forem/forem/blob/5ef0f436365339bc8b4ab17641e21b1ab38c7118/app/policies/authorizer.rb#L83) (`has_trusted_role? || any_admin? || super_moderator? || tag_moderator?`) it already covers the other branches of the conditional up in `moderator_create?` here

**Review by filleduchaos — APPROVED** [review]
🎉 I do think the internal/external naming of trusted users/moderators could use some standardizing (or at least making it more explicit whenever we are talking about _tag_ moderators)

File: app/policies/comment_policy.rb (hunk 1 above)
Comment (jaw6) [reply app/policies/comment_policy.rb:86]: It's a good question! There's maybe-sort-of answers here, but I'm **not** particularly convinced this needs to stay — I can see how `trusted?` would simplify this.

* The most basic answer is: I'm [bringing over a similar check in `response_template_policy`](https://github.com/forem/forem/blob/915b3eaca4e70e77943facd3fd8b27f4ae241fe5/app/policies/response_template_policy.rb#L67)
* More significantly: around a year ago, I don't think we _really_ **got** how `trusted users` were _supposed_ to work. (See also: https://github.com/forem/forem/pull/18601) I was brand-new here when I was working on `trusted users -> response templates`, but it wasn't _just_ me: there [was a _lot_ of confusion](https://github.com/forem/forem/pull/17867#discussion_r893461089) about the role at the time.)
* My personal stylistic preference (_especially_ when roles are undergoing a lot of transformation) is to be _very explicit_ about the kinds of permissions being sought/granted, even if they are ultimately derived from a role. This tends to work well with `pundit` (but I think we could do more). (That is: I prefer having views/helpers asking specific questions, like `can_i_do_this_thing?` than scattering `has_role(x) || has_role(y) && not_property(z)` everywhere. When permissions shift, like "trusted users can now access templates", it's easier to change specific questions' answers or introduce new hair-splitting questions than hunt for every `has_role` in the system.)
* Another team (at the time, we had functional teams inside Eng) was working on re-organizing scattered "permission" methods into a (relatively) new class `Authorizer`, so [I added the new method there](https://github.com/forem/forem/blob/915b3eaca4e70e77943facd3fd8b27f4ae241fe5/app/policies/authorizer.rb#L82-L84) — it was awkward, but for better and worse, it felt like a kind-of hybrid between a `Pundit Policy` class and the `rolify` relationship gem. My understanding, at the time, was that we were actively refactoring and reorganizing where permissions (and roles) code lived in the system as well as simultaneously changing some of the roles & permissions.
* We also have had a tendency to aggressively cache role queries, for better and worse, (and the `trusted` role _in particular_ had buggy caching until [rather recently](https://github.com/forem/forem/pull/19275)) — which leads to methods [that equally aggressively route _around_ caching](https://github.com/forem/forem/blob/915b3eaca4e70e77943facd3fd8b27f4ae241fe5/app/policies/authorizer.rb#L86-L101) — being :new: at the time, it wasn't _totally_ clear to me what "sources of truth" we could "trust".
* Due to roles & permissions being in so much flux, it was specifically [unclear at the time](https://github.com/forem/forem/pull/17867#issuecomment-1153595043) whether we could reliably assume "all `admins` are _always_ also `trusted`" (etc.) or if that was only temporarily/accidentally true.

Comment (filleduchaos) [reply app/policies/comment_policy.rb:86]: Oh! I think I wasn't very clear - what I meant was more that it seems like you could replace the implementation of `moderator_create?` (`user_trusted? || user_moderator? || user_any_admin?`) with just `Authorizer.for(user: user).accesses_mod_response_templates?` since it checks for all of those things

File: app/policies/comment_policy.rb [hunk 2]
```diff
@@ -41,7 +41,7 @@ def moderate?
 
   def moderator_create?
     # NOTE: Here, when we say "moderator", we mean "tag_moderator"
-    user_moderator? || user_any_admin?
+    user_trusted? || user_moderator? || user_any_admin?
```
Comment (Ridhwana) [inline app/policies/comment_policy.rb:44]: Maybe this is what PJ meant [here](https://github.com/forem/forem/pull/20158#discussion_r1335862671) We could re-use the `accesses_mod_response_templates?` method (and rename it if need be). 

```suggestion
Authorizer.for(user: user).accesses_mod_response_templates?
```

**Review by Ridhwana — APPROVED** [review]

**Comment by michael-tharrington** [comment]
Y'all rock! Thanks so much for the help on this @jaw6 and @mirie! 🙌

And I agree that referring to these as Trusted User or Trusted Member Response Templates is kinda confusing.

To be clear, we have 2 mod roles — Trusted Members and Tag Moderators — and refer to the two together as just DEV Moderators (or sometimes just "The Mods"). For instance, we have the DEV Moderator Newsletter that goes out to both Trusted Members and Tag Moderators.

2 other tricky things about this:
1. Every Tag Moderator also has the Trusted Member role...
2. We once referred to Trusted Members as Trusted Users but at some point updated the language to be Trusted Members... we didn't necessarily make the change behind the scenes. We've also juggled the phrases "response templates" and "comment templates" interchangeably in places. 

In any case, for the purposes of this convo, ideally, I think I'd prefer to call them Moderator Comment Templates or possibly just Trusted Member Comment Templates. 

Currently, if Mods go to [/settings/extensions](https://dev.to/settings/extensions) we call the whole section Comment Templates and have a subsection called Trusted User Templates. I like keeping Comment Templates unless someone prefers Response Templates, but I'd prefer Moderator Comment Templates > Trusted User Comment Templates.

All this is kinda extra though... I can write up a separate issue for this if we think it's worthy of a change. To be honest, it hasn't been a big deal to me. I just wanted to provide that extra context around the language; it is quite tricky!

**Comment by jaw6** [comment]
> I can write up a separate issue for this if we think it's worthy of a change. To be honest, it hasn't been a big deal to me. I just wanted to provide that extra context around the language; it is quite tricky!

:+1: I think you should write it up as an issue and @mirie and @PhilipHow can prioritize it from there!

**Comment by michael-tharrington** [comment]
Sounds good! I'm gonna think about the language and bring it up with Community to double check that they're on the same page, but will likely write it up soon. Appreciate the guidance @jaw6!
