### PR TITLE
[15 minute fix] Fixed bug with templates not being inserted for comments.

### LINKED ISSUE #13171: Comment templates not inserting as expected
**Describe the bug**
When inserting a moderator template response into a comment (not selecting `Send as Mod`), no text appears in the comment text box. 

When attempting to insert the response again, users are prompted `Are you sure you want to replace your current comment draft?` (there is no current text).

**To Reproduce**
1. Log in as a tag moderator
2. Scroll to the Discussion of any article and create a new comment
3. Select `Templates` 
4. Select a `Moderator` template and click `Insert'

Repeat to view dialogue box

**Expected behavior**
Usually, template text appears in the comment text box, which can be edited or posted as-is.

**Screenshots**
Screenshot 2021-03-29 at 17 11 03
Screenshot 2021-03-29 at 17 11 27
Screenshot 2021-03-29 at 17 11 41

**Desktop (please complete the following information):**

- OS, version: MacOS Mojave 10.14.6
- Browser, version: Chrome Version 89.0.4389.90

**Additional context**
This was first reported by a community moderator and I was able to replicate (see screenshots).

### LINKED ISSUE #13175: Text not clearing after submission of top-level comment
**Describe the bug**

After submitting a top level comment, the text is not cleared away from the composer.

**To Reproduce**

- Visit an article
- Leave tp-level comment
- Observe that text is still in the comment box.

**Expected behavior**

Text should clear upon submission.

### PR DESCRIPTION
**Pull request by nickytonline**
<details>
<summary>Details</summary>

</details>

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Fixes an issue with inserting a canned response for a comment. The mention auto-complete generates two textareas that it toggles between as part of it's inner workings. The first one is hidden by default and this is why it appeared to not insert canned responses.

## Related Tickets & Documents

#13061
Closes #13171
Closes #13175 

## QA Instructions, Screenshots, Recordings

Log in to your local Forem instance as any type of user.

### Creating a User Comment

1. Navigate to an article on your local Forem instance and give focus to the new comment textbox.
2. Add a comment and click the *Submit* button.

image

3. The comment is saved and rendered.

image

### Creating a Canned Response Comment

1. Navigate to http://localhost:3000/settings/extensions
2. Enter a title for the canned response and the canned response you want.

image

3. Click the *Save Template* to save the canned response.
4. The canned responses list will update.

image.

5. Navigate to an article on your local Forem instance and give focus to the new comment textbox. A toolbar below the textbox appears with a *Templates*. Click the *Templates* button to display the list of canned responses.

image

6. Click the *Insert* button for the canned response that was previously created.
7. The canned response is inserted into the comment textbox and the canned responses panel disappears.

image

8. Click the *Submit* button.
9. The canned response is saved as a comment for the article.

image

NOTE: Test this for replies to existing comments as well using the same steps mentioned above.

### UI accessibility concerns?

N/A

## Added tests?

- [x] Yes
- [ ] No, and this is why:
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [x] This change does not need to be communicated, and this is why not: The feature still behaves the same. It's an implementation detail to fix the bug.

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Comment by nickytonline** [comment]
Just adding some tests.

File: app/assets/javascripts/initializers/initializeCommentsPage.js.erb [hunk 1]
```diff
@@ -256,9 +256,17 @@ function handleCommentSubmit(event) {
             var mainCommentsForm = document.getElementById("new_comment");
             mainCommentsForm.classList.remove("submitting");
             mainCommentsForm.classList.remove('preview-open');
-            const textArea = form.getElementsByClassName("comment-textarea")[0];
-            textArea.closest('.comment-form').classList.remove('comment-form--initiated');
-            textArea.value = newComment.comment_template || "";
+
+            const commentInputs = [...form.getElementsByClassName("comment-textarea")]
```
Comment (nickytonline) [inline app/assets/javascripts/initializers/initializeCommentsPage.js.erb:260]: Still not certain if this is the best approach @aitchiss. I was wondering if we can only render one of the textareas instead of both in the `<MentionAutoComplete />` component. I did a quick test, but it looks like it causes rendering issues with layout shifts and fun stuff.

File: app/assets/javascripts/initializers/initializeCommentsPage.js.erb [hunk 2]
```diff
@@ -447,13 +455,21 @@ function handleButtonsActivation(event) {
...
 function validateField(event) {
-  var textarea = event.target.closest('.comment-form').getElementsByClassName('comment-textarea')[0];
-  if (textarea) {
-    var commentField = textarea.value;
-    if (commentField == '') {
-      event.preventDefault();
-    }
+  // Syncing comment textboxes because there is an additional one
+  // generated by the comment mention auto-complete component
+  const textAreas = [...event.target.form.querySelectorAll('.comment-textarea')]
```
Comment (nickytonline) [inline app/assets/javascripts/initializers/initializeCommentsPage.js.erb:460]: Like above, again syncing the two textareas.

File: app/javascript/crayons/MentionAutocompleteTextArea/MentionAutocompleteTextArea.jsx [hunk 3]
```diff
@@ -287,6 +288,7 @@ export const MentionAutocompleteTextArea = ({
           as="textarea"
           autocomplete={false}
           onChange={handleTextInputChange}
+          data-active={hasSearchTerm}
```
Comment (nickytonline) [inline app/javascript/crayons/MentionAutocompleteTextArea/MentionAutocompleteTextArea.jsx:291]: I'm using the `data-active` data attribute instead of the `disabled` attribute as it appeared to cause styling issues and weird behaviour.

File: app/javascript/responseTemplates/responseTemplates.js [hunk 4]
```diff
@@ -126,7 +126,7 @@ function addClickListeners(form) {
   insertButtons.forEach((button) => {
     button.addEventListener('click', (e) => {
       const { content } = e.target.dataset;
-      const textArea = form.getElementsByTagName('textarea')[0];
+      const textArea = form.querySelector('textarea[data-active]');
```
Comment (nickytonline) [inline app/javascript/responseTemplates/responseTemplates.js:129]: Insert the canned response into the currently active textarea that the `<MentionAutoComplete />` component is rendering.

File: app/views/articles/_full_comment_area.html.erb [hunk 5]
```diff
@@ -2,7 +2,7 @@
   <section id="comments" data-updated-at="<%= Time.current %>" class="text-padding mb-4 border-t-1 border-0 border-solid border-base-10">
     <% if @article.show_comments %>
       <header class="relative flex justify-between items-center mb-6">
-        <h2 class="crayons-subtitle-1">Discussion <span class="js-comments-count" data-comments-count="<%= @article.comments_count %>">(<%= @article.comments_count %>)</span> </h2>
+        <h2 class="crayons-subtitle-1">Discussion <span class="js-comments-count" data-comments-count="<%= @article.comments_count %>">(<%= @article.comments_count %>)</span></h2>
```
Comment (nickytonline) [inline app/views/articles/_full_comment_area.html.erb:5]: Remove some trailing white space as it wasn't necessary and it was throwing me off when writing end to end tests.

File: cypress/integration/publishingFlows/commentOnAnArticle.spec.js [hunk 6]
```diff
@@ -0,0 +1,88 @@
...
+        .findByRole('button', { name: /^Submit$/i })
+        .click();
+
+      // Comment was saved so the new comment textbox should be empty.
+      cy.get('@main')
+        .findAllByLabelText('Add a comment to the discussion')
+        .should('be.visible')
+        .should('have.value', '');
+
+      // TODO: Fix query
```
Comment (nickytonline) [inline cypress/integration/publishingFlows/commentOnAnArticle.spec.js:76]: I'm unable to figure out why `cy.get('@main').findByText(/^This is a canned response$/i);` does not work here. I do the same thing in the other test for a non-canned response, i.e. `cy.get('@main').findByText(/^this is a comment$/i);`

File: cypress/support/commands.js [hunk 7]
```diff
@@ -140,3 +140,70 @@ Cypress.Commands.add(
     );
   },
 );
+
+/**
```
Comment (nickytonline) [inline cypress/support/commands.js:144]: This is in this PR, but it is in #13151 with documentation, so merge that first.

**Comment by nickytonline** [comment]
cc: @cmgorton in case you come across any issues logged about canned responses not working.

File: app/assets/javascripts/initializers/initializeCommentsPage.js.erb (hunk 1 above)
Comment (aitchiss) [reply app/assets/javascripts/initializers/initializeCommentsPage.js.erb:260]: Yeah I see what you mean, it feels wrong for this code to have to care about the detail of the autocomplete implementation 🤔 

One thought is that we only need to make sure the value is applied in the 'plain' (non combobox) text area - this is presented at all time the autosuggest isn't in action, and the autosuggest can't be triggered without some kind of `onChange` event, which makes sure it stays in step with whatever the plain text area's current value is.

We could adjust the selector to `form.querySelector('.comment-textarea:not([role=combobox])');` - this will yield only the plain text area for updating and would save having to loop over multiple elements.

File: cypress/integration/publishingFlows/commentOnAnArticle.spec.js [hunk 8]
```diff
@@ -0,0 +1,91 @@
+describe('Comment on an article', () => {
```
Comment (aitchiss) [inline cypress/integration/publishingFlows/commentOnAnArticle.spec.js:1]: we also have a `commentOnArticle` suite of tests under `articleFlows` - we should combine the two

File: cypress/integration/publishingFlows/commentOnAnArticle.spec.js (hunk 6 above)
Comment (aitchiss) [reply cypress/integration/publishingFlows/commentOnAnArticle.spec.js:79]: It's because there's two matching inputs with that text (the visible and the invisible text areas). I think it works in the other test because you've saved the comment first, so the text areas have disappeared

File: cypress/integration/publishingFlows/commentOnAnArticle.spec.js (hunk 8 above)
Comment (nickytonline) [reply cypress/integration/publishingFlows/commentOnAnArticle.spec.js:1]: That makes sense. I realized yesterday when I noticed a test in another PR of mine with the same name failed. 🙃 I'll add the canned responses tests into tour existing test file.

File: app/assets/javascripts/initializers/initializeCommentsPage.js.erb (hunk 1 above)
Comment (nickytonline) [reply app/assets/javascripts/initializers/initializeCommentsPage.js.erb:260]: I'll try that out. Thanks for the suggestion. I think part of the issue might also be that since the attributes are copied, the duplicate textarea is a required field as well. I'll report back. 😅

Comment (aitchiss) [reply app/assets/javascripts/initializers/initializeCommentsPage.js.erb:260]: gah! so many things coming out of the woodwork 😅 I guess we could always override the combobox `required` attribute so it's always `false` 🤔 The 'plain' textarea should be the main source of truth

Comment (nickytonline) [reply app/assets/javascripts/initializers/initializeCommentsPage.js.erb:260]: Actually here looping through all to clear is not that bad. It's below in the `validateField` function that it's potentially an issue. I'll take it for a test drive.

**Comment by nickytonline** [comment]
Code climate is complaining about the file size of a spec, but it's all related tests, so I think it's fine.

File: cypress/integration/articleFlows/commentOnArticle.spec.js [hunk 9]
```diff
@@ -5,265 +5,338 @@ describe('Comment on articles', () => {
...
     cy.get('@user').then((user) => {
       cy.loginUser(user).then(() => {
-        cy.visit('/');
-        cy.findAllByText('Test article').last().click();
+        cy.createArticle({
+          title: 'Test Article',
+          tags: ['beginner', 'ruby', 'go'],
+          content: `This is a test article's contents.`,
+          published: true,
+        }).then((response) => {
```
Comment (aitchiss) [inline cypress/integration/articleFlows/commentOnArticle.spec.js:13]: love this 😎

**Review by aitchiss — APPROVED** [review]
Looks good to me 👍 I've checked locally and all seems well, and I think we have good coverage with the Cypress tests.

As an aside - I did find another issue in the comments area, but I'm not sure it's related to the autocomplete work - I'll do a bit more investigation and raise as a separate issue.

**Review by rhymes — APPROVED** [review]
LGTM!
