### PR TITLE
Fixed save button behavior

### LINKED ISSUE #8167: Save Button doesn't behave as expected
**Describe the bug**

Sometimes the save button text doesn't reflect the status of the article. For example, when the article is saved sometimes the button text reads: `Save`. Other times, the article has been unsaved, but the text reads: `Saved`.

It seems like this has to do with the `onMouseout` action in `SaveButton.jsx`, but I haven't investigated it much beyond that!

**To Reproduce**

1. Click "Save" or "Unsave" on an article
2. Move your mouse off of the button quickly
3. Button text is incorrect, but will update if you mouse over the button.

**Expected behavior**

The button text should reflect the status even if the mouse quickly exits the button.

**Screenshots**

Peek 2020-05-29 13-46

**Desktop (please complete the following information):**

- OS: Ubuntu 
- Browser: Chrome + Firefox (Seems to happen more frequently in Firefox)
- Version:

### PR DESCRIPTION
**Pull request by dengaku12**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
The save button wouldn't update if clicked and then quickly moved your mouse away. Now It is able to handle that. The the button is still a slow to update when you click unsave though. Fixes #8167.
## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?
https://giphy.com/gifs/gintama-kdM3zfq85XSb6
alt_text

### CODE REVIEW

File: app/javascript/articles/components/SaveButton.jsx [hunk 1]
```diff
@@ -8,20 +8,23 @@ export class SaveButton extends Component {
 
     const { isBookmarked } = props;
 
-    this.state = { buttonText: isBookmarked ? 'Saved' : 'Save' };
+    this.state = {
+      buttonText: isBookmarked ? 'Saved' : 'Save',
+      hovering: false,
```
Comment (nickytonline) [inline app/javascript/articles/components/SaveButton.jsx:13]: The `hovering` state property is not necessary. We can leverage native browser events to handle this, i.e. `mouseMove`

File: app/javascript/articles/components/SaveButton.jsx [hunk 2]
```diff
@@ -8,20 +8,23 @@ export class SaveButton extends Component {
...
+    };
   }
 
   render() {
-    const { buttonText } = this.state;
+    //const { hovering } = this.state.hovering;
```
Comment (nickytonline) [inline app/javascript/articles/components/SaveButton.jsx:18]: Remove commented out code.

File: app/javascript/articles/components/SaveButton.jsx [hunk 3]
```diff
@@ -8,20 +8,23 @@ export class SaveButton extends Component {
...
-      this.setState({ buttonText: isBookmarked ? 'Unsave' : 'Save' });
+      this.setState({ hovering: true });
     };
 
     const mouseOut = (_e) => {
-      this.setState({ buttonText: isBookmarked ? 'Saved' : 'Save' });
+      this.setState({ hovering: false });
     };
 
     const handleClick = (_e) => {
```
Comment (nickytonline) [inline app/javascript/articles/components/SaveButton.jsx:30]: A bug was here because I wasn't doing setting the `isBookmarked` component state property

```js
      this.setState({
        buttonText: isBookmarked ? 'Save' : 'Saved',
        isBookmarked: !isBookmarked,
      });
```

File: app/javascript/articles/components/SaveButton.jsx [hunk 4]
```diff
@@ -44,7 +47,13 @@ export class SaveButton extends Component {
...
           onBlur={mouseOut}
         >
-          {buttonText}
+          {this.state.hovering
+            ? isBookmarked
+              ? 'Unsave'
+              : 'Save'
+            : isBookmarked
+            ? 'Saved'
+            : 'Save'}
```
Comment (nickytonline) [inline app/javascript/articles/components/SaveButton.jsx:56]:
```suggestion
          {buttonText}
```

File: app/javascript/articles/components/SaveButton.jsx [hunk 5]
```diff
@@ -8,20 +8,23 @@ export class SaveButton extends Component {
...
 
   render() {
-    const { buttonText } = this.state;
+    //const { hovering } = this.state.hovering;
 
     const { article, isBookmarked, onClick } = this.props;
 
     const mouseOver = (_e) => {
-      this.setState({ buttonText: isBookmarked ? 'Unsave' : 'Save' });
+      this.setState({ hovering: true });
```
Comment (nickytonline) [inline app/javascript/articles/components/SaveButton.jsx:23]:
```suggestion
      this.setState({ buttonText: isBookmarked ? 'Unsave' : 'Save' });
```

File: app/javascript/articles/components/SaveButton.jsx [hunk 6]
```diff
@@ -8,20 +8,23 @@ export class SaveButton extends Component {
...
     };
 
     const mouseOut = (_e) => {
-      this.setState({ buttonText: isBookmarked ? 'Saved' : 'Save' });
+      this.setState({ hovering: false });
```
Comment (nickytonline) [inline app/javascript/articles/components/SaveButton.jsx:27]:
```suggestion
      this.setState({ buttonText: isBookmarked ? 'Saved' : 'Save' });
```

File: app/javascript/articles/components/SaveButton.jsx [hunk 7]
```diff
@@ -8,20 +8,23 @@ export class SaveButton extends Component {
...
+    };
   }
 
   render() {
-    const { buttonText } = this.state;
+    //const { hovering } = this.state.hovering;
 
     const { article, isBookmarked, onClick } = this.props;
 
     const mouseOver = (_e) => {
```
Comment (nickytonline) [inline app/javascript/articles/components/SaveButton.jsx:22]: Use `mouseMove` instead of `mouseOver` so that we can update the `buttonText` component state thanks to the native `mousemove` DOM event.

File: app/javascript/articles/components/SaveButton.jsx (hunk 2 above)
Comment (Zhao-Andy) [inline app/javascript/articles/components/SaveButton.jsx:18]: Ah just noticed this. Did you mean to use or remove this variable?

Comment (dengaku12) [reply app/javascript/articles/components/SaveButton.jsx:18]: Yeah i think they wanna get rid of the hovering state property. Should I just commit all these changes? lol

Comment (Zhao-Andy) [reply app/javascript/articles/components/SaveButton.jsx:18]: I think Nick's suggestions make sense!

File: app/javascript/articles/components/SaveButton.jsx (hunk 3 above)
Comment (dengaku12) [reply app/javascript/articles/components/SaveButton.jsx]: Hey i put your suggestions in the code and I'm getting the same problem we initially had
```
 const handleClick = (_e) => {
      onClick(_e);
      this.setState({ 
        buttonText: isBookmarked ? 'Save' : 'Saved',
        isBookmarked: !isBookmarked
       });
       
    };
```

Comment (dengaku12) [reply app/javascript/articles/components/SaveButton.jsx]: I also tried putting `isBookmarked` outside of `this.setState` by doing 
```
this.setState({ 
        buttonText: isBookmarked ? 'Save' : 'Saved',
       });
isBookmarked = !isBookmarked;
```

Comment (dengaku12) [reply app/javascript/articles/components/SaveButton.jsx]: I got rid of the mouseOver event and replaced it with the mouseMove event too

**Comment by dengaku12** [comment]
Hey, @nickytonline I don't know if you saw my comment on Friday, but I applied your suggestions to my code and I am getting the same original issue. Would i be allowed to introduce the `hovering` property to state again?

**Comment by nickytonline** [comment]
Weird, it works for me fine. For example if you click on the save button it changes the text to `SAVED` (mouse is over the button at this point). As soon as you move the mouse, the text changes to `UNSAVE` because of the mousemove. Is this not what you're exhibiting @dengaku12 ?

**Comment by dengaku12** [comment]
Yeah, when I click on 'save' and then quickly move my mouse it still says 'save'. Only when i move my mouse over the button again will it change to 'saved'. Then when i move the mouse away it says 'unsave' and acts as it should. @nickytonline

**Comment by nickytonline** [comment]
> Yeah, when I click on 'save' and then quickly move my mouse it still says 'save'. Only when i move my mouse over the button again will it change to 'saved'. Then when i move the mouse away it says 'unsave' and acts as it should. @nickytonline

Weird, that's not the behaviour I see. If you click `SAVE`, it changes to `SAVED` and then if you move the mouse it says `UNSAVE`. This is the behaviour I would expect.

**Comment by dengaku12** [comment]
And you're moving the mouse quickly as soon as you click on the button? Maybe it's because I'm using Firefox (they said that the issue happens more on Firefox)

**Comment by dengaku12** [comment]
@nickytonline I pushed the changes. Maybe I did something wrong?

**Comment by dengaku12** [comment]
@nickytonline ^

**Comment by nickytonline** [comment]
@dengaku12, I pulled your changes locally and it is behaving as I would expect it too.

When you click `Save` it gets changed to `Saved` and then if you start to move the mouse it changes to `Unsave`.

works

Are you expecting it to change to `Unsave` right away because the user is hovering over the button? If so, we need the user to see that they saved the article, hence the `Saved` text change to the button and then only on mouse move, do we change it to `Unsave`.

cc: @ludwiczakpawel

**Comment by dengaku12** [comment]
@nickytonline the problem is that when you click on the button and then immediately move the mouse, the button starts to act up a little bit/ You have to hover the mouse over the button again for it to correct itself.
alt text

**Comment by dengaku12** [comment]
@nickytonline ^

**Comment by nickytonline** [comment]
@dengaku12, I don't exhibit the behaviour you are mentioning and I've tested it on Chrome, Firefox and Edge.

These are the scenarios I see happening with the code changes in this branch:

1. Post is not saved so you see **Save** as the text when you hover or stop hovering over the mouse.
1. User clicks the Save button. The text changes to **Saved**. As soon as the user starts to move the mouse, the button text changes to **Unsave**. Note: If you save and move the mouse out quickly like you mentioned, the button text will say **Saved**.
1. If the post is saved, the button text is **Saved**. If you hover over the button, the button text will be **Unsave** and if you move the mouse outside of the button, the button text changes back to **Saved**
1. If the user removes the bookmark, the button text goes from **Unsave** to **Save** and then the scenario is back to point 1.

Also, I tested this with the keyboard and it behaves like the above except it's based on focus and blur.

@Zhao-Andy, can you confirm this is what you exhibit as well?

**Comment by dengaku12** [comment]
@nickytonline, honestly if it works then I think you should merge it

**Comment by dengaku12** [comment]
@nickytonline im writing the test and im having a lot of trouble figuring out how to test the `onClick` handler. Heres what i have so far
```
import { h } from 'preact';
import { render } from '@testing-library/preact';
import { axe } from 'jest-axe';
import { screen } from '@testing-library/dom';
import { SaveButton } from '../SaveButton';

const testArticle = {
    id: 1,
    title: 'An article title',
    path: 'an-article-title-di3',
    publishedAt: '2019-06-22T16:11:10.590Z',
    cachedTagList: 'discuss, javascript, beginners',
    user: {
      articles_count: 1,
      name: 'hello',
    },
};

const mockClick = () => {
    const saveButton = screen.getByText('Save' || 'Unsave' || 'Saved');
    saveButton.click();
}


describe('<SaveButton />', () => {
    it('should have no ally violations', async () => {
        const { container } = render (
            <SaveButton
                article={testArticle}
                isBookMarked={false}
                onClick={mockClick()}
            />,
        );

        const results = await axe(container);
        expect(results).toHaveNoViolations();
    });


})
```

**Comment by Ridhwana** [comment]
Hi @dengaku12, just a headsup that @nickytonline is offline this week but I'm going to look into your question about the test during the course of today/tomorrow morning.

**Comment by dengaku12** [comment]
Ok thanks for ur help :)

**Comment by nickytonline** [comment]
@dengaku12, I'm back from vacation. Just looking into this for you.

**Comment by nickytonline** [comment]
@dengaku12, can you give my user permission to push to your branch? I will post some tests in your PR branch. Thanks!

**Comment by nickytonline** [comment]
@dengaku12, I've included the tests for the component. I'm just going to add some comments explaining how the tests work.

File: app/javascript/articles/components/__tests__/SaveButton.test.jsx [hunk 8]
```diff
@@ -0,0 +1,87 @@
+import { h } from 'preact';
+import { fireEvent, render } from '@testing-library/preact';
+import { axe } from 'jest-axe';
+import { SaveButton } from '../SaveButton';
+
+it('should have no a11y violations', async () => {
```
Comment (nickytonline) [inline app/javascript/articles/components/__tests__/SaveButton.test.jsx:6]: This test is for accessibility violations. Using [jest-axe](https://github.com/nickcolley/jest-axe), it checks to see if the component violates any accessibility issues that jest-axe is aware of. If there are any, the test will fail.

You can read a bit more about it in this post, [Changelog: Frontend Edition](https://dev.to/devteam/changelog-frontend-edition-30l7), which I wrote a while back in regards to the Preact upgrade for Forem.

File: app/javascript/articles/components/__tests__/SaveButton.test.jsx [hunk 9]
```diff
@@ -0,0 +1,87 @@
...
+  const article = { class_name: 'Article', id: 1 };
+  const { container } = render(<SaveButton article={article} />);
+  const results = await axe(container);
+
+  expect(results).toHaveNoViolations();
+});
+
+it('should render button as bookmarked', () => {
```
Comment (nickytonline) [inline app/javascript/articles/components/__tests__/SaveButton.test.jsx:14]: @dengaku12, the next two tests are just checking to see if the correct button text is loading based on whether or not an article is bookmarked.

File: app/javascript/articles/components/__tests__/SaveButton.test.jsx [hunk 10]
```diff
@@ -0,0 +1,87 @@
...
+  const article = { class_name: 'Article', id: 1 };
+  const { queryByText } = render(
+    <SaveButton article={article} isBookmarked={false} />,
+  );
+  const saveButton = queryByText('Save');
+
+  expect(saveButton).not.toBeNull();
+});
+
+it('should bookmark when it previously was not', async () => {
```
Comment (nickytonline) [inline app/javascript/articles/components/__tests__/SaveButton.test.jsx:32]: The only thing that needs a mock here in the next two tests @dengaku12 in regards to clicking the button is the `onClick` prop. Jest has a convenient `jest.fn()` which allows us to do this. For the actual click of the button we want that to be real, which we can do via `.click()`.

File: app/javascript/articles/components/__tests__/SaveButton.test.jsx [hunk 11]
```diff
@@ -0,0 +1,87 @@
...
+
+  const savedButton = getByText('Saved');
+  savedButton.click();
+
+  const saveButton = await findByText('Save');
+
+  expect(saveButton).not.toBeNull();
+});
+
+it('should change text to unbookmark when hovering over button and it is bookmarked', async () => {
```
Comment (nickytonline) [inline app/javascript/articles/components/__tests__/SaveButton.test.jsx:59]: These next two tests test the mousemove change that was made.

**Comment by dengaku12** [comment]
This is all very interesting, @nickytonline thanks for your help. I really appreciate it!

**Review by Ridhwana — APPROVED** [review]

**Comment by nickytonline** [comment]
Thanks so much for the PR @dengaku12!
