### PR TITLE
Hide "Report Abuse" button when User viewing their own Article

### LINKED ISSUE #14658: 'Report Abuse' should not be shown for author of the Post
**Describe the bug**
In posts show page, 'Report Abuse' option is shown to Author of the post. Can we remove this ?

**To Reproduce**

**Expected behavior**

"Report Abuse" should not be shown for author of the Post

**Screenshots**
Screenshot 2021-09-03 at 12 37 51 AM

**Desktop (please complete the following information):**

- OS, version: Not an OS specific bug
- Browser, version: Not a Browser specific bug

**Smartphone (please complete the following information):**

- Device: Not Device specific bug
- OS, version:Not an OS specific bug
- Browser, version: Not a browser specific bug

**Additional context**

### PR DESCRIPTION
**Pull request by FrancisTRAlt**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
This PR address where if the User is viewing their own article, the option to "Report Abuse" will not show to the user.

image

However, if the user looks at other people's post (that the user do not own), it will show the option:

image

_Note that if they are not sign in, the "Report Abuse" button will be visible by default._

This will prevent unnecessary self-report in my opinion because I believe there will be cases where a user will self-report himself either accidentally or intentionally. This will make it harder for the user to self-report.

Additionally, to the issue #14658, it was requested that the footer should remain:

image

## Related Tickets & Documents

- Related Issue #14658
- Closes #14658 

## QA Instructions, Screenshots, Recordings
When you are signed in:

1. View your own post
2. Click the "..." button on the side.
3. You will see that the "Report Abuse" button is not visible.
4. Now, view any article and click the "..." and you will see the option.

When you are not signed in:
- View any article, click the "..." dropdown and you will see the "Report Abuse" button.

## Added/updated tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [x] I need help with writing tests

## What gif best describes this PR or how it makes you feel?

Pikachu

### CODE REVIEW

**Comment by FrancisTRdev** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by FrancisTRdev** [comment]
@benhalpern I produced the same functionality in JavaScript as you requested!

`document.getElementById("ReportButtonAuthor").style.display = "none";`

Let me know if anything!

File: app/assets/javascripts/initializers/initializeBaseUserData.js [hunk 1]
```diff
@@ -18,6 +18,9 @@ function addRelevantButtonsToArticle(user) {
     const scheduled = JSON.parse(articleContainer.dataset.scheduled);
 
     if (parseInt(articleContainer.dataset.authorId, 10) === user.id) {
+
+      document.getElementById("ReportButtonAuthor").style.display = "none"; // Hide the Report button if the Author is viewing its own post
```
Comment (benhalpern) [inline app/assets/javascripts/initializers/initializeBaseUserData.js]:
```suggestion
      const reportButton = document.getElementById("ReportButtonAuthor"); 

if (reportButton) {
  reportButton.style.display = "none"; // Hide the Report button if the Author is viewing its own post
}
```
