### PR TITLE
Ensure Article's `username` method returns a downcased string

### LINKED ISSUE #11690: Fully blocked: 404 when trying to edit/create a post
**Describe the bug**

From the dashboard or the blogpost itself, I can't edit my blogposts anymore. I get a 404:

Screen Shot 2020-12-01 at 16 25 50

It started to happen around last Saturday, I waited to see if the bug would disappear, still here.

I disabled all extensions and cleared the site data, no success.

**To Reproduce**

1. Log in
1. Go to your dashboard
1. pick any blogpost (draft or published) and click "edit"

**Expected behavior**

I should see the editor

**Screenshots**

Screen Shot 2020-12-01 at 16 25 50

**Desktop (please complete the following information):**

* macOS Catalina latest
* chrome latest, all extensions disabled

**Additional context**

I started using "dev-to-get" following the instructions of those blogposts:
-  https://dev.to/maxime1992/manage-your-dev-to-blog-posts-from-a-git-repo-and-use-continuous-deployment-to-auto-publish-update-them-143j
-  https://dev.to/beeman/automate-your-dev-posts-using-github-actions-4hp3

Could that have messed up things?

### PR DESCRIPTION
**Pull request by fdoxyz**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

~A user's posts were inaccessible because the `path` in their articles didn't match the query with the downcase params. This PR updates the way the query is done in Postgres by lowercasing the fields.~

A new approach: Instead of updating the logic in `stories#show` this PR ensures the path is built forcing to lowercase `calculated_path` in `set_caches` (`before_save` callback)

Check out this query (capitalized username): https://dev.to/admin/blazer/queries/303-issue-11690

## Related Tickets & Documents

Closes #11690 

## QA Instructions, Screenshots, Recordings

1. Make your own user have a capitalized username
1. Publish a new Article
1. Check out your newly created Article
1. Edit the same Article and save

None of the above should break the app

### UI accessibility concerns?

N/A

## Added tests?

- [x] Yes

## Added to documentation?

- [ ] [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/)
- [ ] README
- [x] No documentation needed

## Post Deployment tasks

Make sure these links work after the data update script runs:
- http://dev.to/AlbertoFdzM/mongoose-mongodb-and-express-596
- https://dev.to/maxime1992/manage-your-dev-to-blog-posts-from-a-git-repo-and-use-continuous-deployment-to-auto-publish-update-them-143j
- https://dev.to/TomGranot/quick-tip-increase-keyboard-repeat-rate-for-faster-typing-4d8g

Also check that this Blazer query returns 0 rows:
https://dev.to/admin/blazer/queries/304-articles-with-uppercased-characters

## [optional] What gif best describes this PR or how it makes you feel?

sort of the same thing

### CODE REVIEW

File: spec/requests/stories_show_spec.rb [hunk 1]
```diff
@@ -188,6 +188,7 @@
 
     it "handles invalid slug characters" do
       allow(Article).to receive(:find_by).and_raise(ArgumentError)
+      allow(Article).to receive(:where).and_raise(ArgumentError)
```
Comment (fdoxyz) [inline spec/requests/stories_show_spec.rb:191]: We used to only do `find_by` but with the `where` clause introduced this keeps the spec working in the same way. Any feedback here to make sure this case is properly covered is appreciated :)

**Review by Zhao-Andy — APPROVED** [review]
Nice 👍

File: app/models/article.rb [hunk 2]
```diff
@@ -285,9 +285,9 @@ def comments_blob
   end
 
   def username
-    return organization.slug if organization
+    return organization.slug.downcase if organization
 
-    user.username
+    user.username.downcase
```
Comment (vaidehijoshi) [inline app/models/article.rb:290]: Could we add a quick test for this? I think maybe [here](https://github.com/forem/forem/blob/master/spec/models/article_spec.rb#L522-L531) or [here](https://github.com/forem/forem/blob/master/spec/models/user_spec.rb#L440-L452)?

**Comment by citizen428** [comment]
I understand this fix, but our inconsistent handling of username gives me anxiety:

Screenshot_2

E.g. for `/:username` we accept any capitalization and take care of it in the controller, here we fix it in a different way, etc. 

I think the fundamental mistake was downcasing usernames in the first place:

```ruby
# app/models/user.rb
def set_username
  set_temp_username if username.blank?
  self.username = username&.downcase
end
```

IMHO a better practice is not to discard the original user input, but normalizing our queries instead consistently. After this PR got merged we probably should look into long term solutions for this.

**Review by citizen428 — APPROVED** [review]

File: app/models/article.rb [hunk 3]
```diff
@@ -409,7 +409,7 @@ def set_caches
 
     self.cached_user_name = user_name
     self.cached_user_username = user_username
-    self.path = calculated_path
+    self.path = calculated_path.downcase
```
Comment (fdoxyz) [inline app/models/article.rb:412]: Moved the `.downcase` call here (to the `before_save` callback). This way we won't run into upcase usernames slipping through into Article paths.

File: lib/data_update_scripts/20201209134953_touch_articles_with_capitalized_paths.rb [hunk 4]
```diff
@@ -0,0 +1,13 @@
+module DataUpdateScripts
+  class TouchArticlesWithCapitalizedPaths
+    def run
+      offending_articles = Article.where("path != lower(path)")
+
+      # Some log visibility for troubleshooting/monitoring
+      Rails.logger.info("Updating #{offending_articles.count} articles...")
+
+      # touch won't trigger the callbacks so a manual update will do the trick
+      offending_articles.update(updated_at: Time.current)
```
Comment (fdoxyz) [inline lib/data_update_scripts/20201209134953_touch_articles_with_capitalized_paths.rb:10]: Turns out `touch_all` doesn't run the `before_save` callbacks (only `before_touch` and others), which is how we're intending to fix the problem.

The idea is that if the logic is correct (fix introduced to `app/models/article.rb`) then this update and all subsequent (user triggered) will continue to work as expected.

File: spec/models/article_spec.rb [hunk 5]
```diff
@@ -528,6 +528,18 @@ def build_and_validate_article(*args)
...
+      upcased_user = create(:user, username: "UpcasedUserName")
+      article = create(:article, user: upcased_user)
+      expect(article.username).not_to match(/[AZ]+/)
+    end
+
+    it "returns a downcased username when an org slug has uppercase characters" do
+      upcased_org = create(:organization, slug: "UpcasedUserName")
+      article = create(:article, organization: upcased_org)
+      expect(article.username).not_to match(/[AZ]+/)
+    end
```
Comment (fdoxyz) [inline spec/models/article_spec.rb]: These tests make sure the `before_save` callback will "sanitize" the path regardless of the capitalization of the User/Org

File: lib/data_update_scripts/20201209134953_touch_articles_with_capitalized_paths.rb [hunk 6]
```diff
@@ -0,0 +1,13 @@
+module DataUpdateScripts
+  class TouchArticlesWithCapitalizedPaths
+    def run
+      offending_articles = Article.where("path != lower(path)")
+
+      # Some log visibility for troubleshooting/monitoring
+      Rails.logger.info("Updating #{offending_articles.count} articles...")
```
Comment (vaidehijoshi) [inline lib/data_update_scripts/20201209134953_touch_articles_with_capitalized_paths.rb:7]:
```suggestion
      Rails.logger.info("Updating #{offending_articles.count} articles with capitalized paths...")
```
**non-blocking suggestion:** this might make it a tiny bit more useful when parsing the logs for this in case something _does_ go wrong

File: spec/lib/data_update_scripts/touch_articles_with_capitalized_paths_spec.rb [hunk 7]
```diff
@@ -0,0 +1,25 @@
...
+    # Check to make sure the query only catches the article with a bad path
+    expect(Article.where("path != lower(path)").count).to eq(1)
+
+    # Run the script
+    described_class.new.run
+
+    # Make sure we no longer have any Articles with bad paths
+    expect(Article.where("path != lower(path)").count).to eq(0)
+  end
+end
```
Comment (vaidehijoshi) [inline spec/lib/data_update_scripts/touch_articles_with_capitalized_paths_spec.rb:25]: Thanks for adding this with helpful + clear comments! 👏🏽

File: spec/models/article_spec.rb [hunk 8]
```diff
@@ -745,6 +745,20 @@ def build_and_validate_article(*args)
   end
 
   context "when callbacks are triggered after save" do
+    describe "article path sanitazing" do
```
Comment (vaidehijoshi) [inline spec/models/article_spec.rb:748]:
```suggestion
    describe "article path sanitizing" do
```

**Review by vaidehijoshi — APPROVED** [review]
