### PR TITLE
Fix the last line of editor is not visible

### LINKED ISSUE #18759: Part of content at the bottom disappears when editing
**Describe the bug**
Part of the content at the bottom of the article is covered by the editor by default. You need to edit it manually, such as pressing ↓ then it will display.

**To Reproduce**
1. Go to edit your published posts
2. Scroll to the bottom of the edit page
3. Press ↓ to show the covered content

**Expected behavior**
The post shows full content by default when editing

**Screenshots**
chrome-capture-2022-10-21

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: 107.0.5304.107

### LINKED ISSUE #18833: Last line in edit mode not visible after switching from preview mode
**Describe the bug**
When switching from preview mode to edit mode, the last line is not visible when scrolled to bottom. 

**To Reproduce**

1. Go to create post.
2. Add dummy text to body, and make sure no empty line is left behind.
3. Switch to preview mode, scroll down to check what was the last line.
4. Switch to edit mode, scroll down to last line.

**Expected behavior**
When switching back to edit mode and scrolling to end, the last line should be visible.

**Screenshots**
**Preview mode**
image
**Edit Mode**
image

**Desktop (please complete the following information):**

- OS - version: Windows 10 21H2, x64-based processor
- Browser, version: Brave, Version 1.46.140 Chromium (Official Build)(64-bit) and Firefox 107.0.1 (64-bit)

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**
Notice the last line in edit mode and preview mode in screenshots, the scroll is fully at bottom in both.

### PR DESCRIPTION
**Pull request by ktmouk**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

When a user visits the edit page, and an article has long text, the textarea doesn't show the last line of content, even if a user scrolls down to the end. (detail: #18833)
This PR will fix this issue by using `ResizeObserver`. I believe This solution can fix almost all of the similar cases that cause the same problem. For example, if a user resizes the browser window, the same problem will happen.

I've checked the PR works fine on the browsers below:
  - Safari (iOS 16.2 and macOS)
  - Chrome 109.0.5414.119 (macOS)
  - Firefox 109.0 (macOS)
  - Chrome (Android12)

## Related Tickets & Documents

- closes #18833
- closes #18759

### Before
https://user-images.githubusercontent.com/17381979/215263393-90ecac55-988b-4d94-96e8-f70e6e9f1338.mov

### After
https://user-images.githubusercontent.com/17381979/215263397-1704d929-8145-429e-b857-2b8b9fa7ce92.mov|

### UI accessibility concerns?
- I believe this PR has no accessibility concerns.

## Added/updated tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [x] I need help with writing tests
  - I think adding the `useTextAreaAutoResize` test is a bit difficult because its behavior is complicated, but if the test is required, I am going to write it.

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

### CODE REVIEW

File: app/javascript/utilities/textAreaUtils.js [hunk 1]
```diff
@@ -287,7 +288,7 @@ export const useTextAreaAutoResize = () => {
       const height = Math.max(...allContentHeights);
       const newHeight = `${height}px`;
 
-      [textArea, ...additionalElements].forEach((element) => {
+      allElements.forEach((element) => {
```
Comment (ktmouk) [inline app/javascript/utilities/textAreaUtils.js:291]: [tiny refactoring] I think We can reuse `allElements` here.

File: app/javascript/utilities/textAreaUtils.js [hunk 2]
```diff
@@ -298,10 +299,19 @@ export const useTextAreaAutoResize = () => {
 
     // Resize on first attach
     resizeTextArea();
+
+    // Resize on window size changes
+    const resizeCallback = debounceAction(() => resizeTextArea(), 300);
+    const resizeObserver = new ResizeObserver(resizeCallback);
+    resizeObserver.observe(textArea);
```
Comment (ktmouk) [inline app/javascript/utilities/textAreaUtils.js:306]: I used `debounceAction` to prevent the callback from being called infinitely.

**Review by fdocr — APPROVED** [review]
