### PR TITLE
Fix UI showing "Following" after unfollowing a user

### LINKED ISSUE #11533: data-verb="unfollow" is not working after refreshing also it is showing data-verb="following" in code also & in UI too
**Describe the bug**
A few days ago I am just followed ex:-user(krishnadevz) on dev and then for reading new articles I refreshed that page and after some time I accidentally unfollowed ex user and then I again refreshed the page and still, it is showing `following`.

**To Reproduce**
* SignIn 
* open dashboard following section 
* and unfollow someone and then refresh it shows following 

**Expected behavior**
* Expected behavior is normal when you unfollow someone else expected is `follow` not `following` i think this internal error on dev  

**Screenshots**
descripfeatures

**Desktop:**

- OS, version: windows version 20H2 os build 19042.630
- Browser, version: firefox=83.0 (64-bit)/chrome=Version 87.0.4280.66 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by aitchiss**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

After unfollowing a user from their profile page, the UI would initially reflect the correct 'unfollowed' state, but on page refresh it would incorrectly show the UI that suggests you're following them (i.e. a button saying "Following"). Going to the dashboard > following users screen you could verify that the unfollow had been successfully processed, it's just the UI on the profile page was incorrect.

After a bit of investigation, it turned out this was because the call to `/follows/<userid>?followable_type=User` was cached in the backend, and kept returning the original 'followed' state.

As a small disclaimer - I'm not a backend dev 😅  I decided to give this a go since I'd already completed some investigation, but if this totally isn't the way we'd want to go about invalidating the cache on 'unfollow' then I'm very open to learning more and changing this!

## Related Tickets & Documents

Fixes #11533

## QA Instructions, Screenshots, Recordings

- Go to a user's profile other than your own
- If you don't follow them already, click to follow them
- Now click to unfollow them
- Notice the UI updates the button back to reading "Follow"
- Refresh the page
- The UI should still show the button reading "Follow"
- Click the Follow button and verify that it follows the user, showing the "Following" button
- Refresh the page and verify the correct "Following" button is shown

NB: I know the UI looks strange on page load, where you see a flash of the "Follow" button before it changes to "Following". This is a known issue, but separate to this bugfix, so please ignore for now!

https://user-images.githubusercontent.com/20773163/118129860-9f3e8980-b3f4-11eb-8b87-5a22388b20e3.mp4

### UI accessibility concerns?

No frontend/UI change here

## Added tests?

- [X] Yes - added a Cypress test

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [X] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] Are there any post deployment tasks we need to perform?

N/A

## [optional] What gif best describes this PR or how it makes you feel?

No idea what I'm doing

### CODE REVIEW

File: app/services/follows/check_cached.rb [hunk 1]
```diff
@@ -4,6 +4,10 @@ def self.call(follower, followable_type, followable_id)
       new(follower, followable_type, followable_id).call
     end
 
+    def self.delete(follower, followable_type, followable_id)
```
Comment (citizen428) [inline app/services/follows/check_cached.rb:7]: Normally we'd make this a separate service, e.g. `Follows::DeleteCached`. The general idea is that one service is responsible for one domain interaction.

Comment (aitchiss) [reply app/services/follows/check_cached.rb:7]: That makes sense - thanks!

**Review by rhymes — COMMENTED** [review]
This works well! I would separate the business logic like @citizen428 suggested but other than that, it's good to go!

Great job @aitchiss!

File: app/controllers/follows_controller.rb [hunk 2]
```diff
@@ -109,10 +109,12 @@ def follow(followable, need_notification: false)
     "already followed"
   end
 
-  def unfollow(followable, need_notification: false)
+  def unfollow(followable, followable_type, need_notification: false)
     user_follow = current_user.stop_following(followable)
     Notification.send_new_follower_notification_without_delay(user_follow, is_read: true) if need_notification
 
+    Follows::DeleteCached.delete(current_user, followable_type, followable.id)
```
Comment (rhymes) [inline app/controllers/follows_controller.rb:116]: just a tiny request and then we're on! `Follows::DeleteCached.call` instead of `Follows::DeleteCached.delete` to follow the pattern of most of other services we have

File: app/services/follows/delete_cached.rb [hunk 3]
```diff
@@ -0,0 +1,33 @@
+module Follows
+  class DeleteCached
+    def self.delete(follower, followable_type, followable_id)
```
Comment (rhymes) [inline app/services/follows/delete_cached.rb:3]: this would become `self.call`

File: app/services/follows/delete_cached.rb [hunk 4]
```diff
@@ -0,0 +1,33 @@
...
+      new(follower, followable_type, followable_id).delete
+    end
+
+    def initialize(follower, followable_type, followable_id)
+      @follower = follower
+      @followable_type = followable_type
+      @followable_id = followable_id
+    end
+
+    def delete
```
Comment (rhymes) [inline app/services/follows/delete_cached.rb:13]: this too would become `def call`

File: app/services/follows/delete_cached.rb [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+
+      cache_key = "user-#{follower.id}-#{follower.updated_at.rfc3339}/is_following_#{followable_type}_#{followable_id}"
+      Rails.cache.delete(cache_key)
+    end
+
+    private
+
+    attr_accessor :follower, :followable_type, :followable_id
+
+    def followable
```
Comment (rhymes) [inline app/services/follows/delete_cached.rb:24]: I can't find a place in the code where this method is called, it comes from `Follows::CheckCached` as it needs it here:

https://github.com/forem/forem/blob/b7ff9aadd1274124e19281ba247486d9c3e33a2a/app/services/follows/check_cached.rb#L18

Comment (aitchiss) [reply app/services/follows/delete_cached.rb]: woops! yes I got a bit too keen with some copy/paste there 😅

File: app/controllers/follows_controller.rb (hunk 2 above)
Comment (aitchiss) [reply app/controllers/follows_controller.rb]: that makes sense - thanks!

**Review by rhymes — APPROVED** [review]

File: app/controllers/follows_controller.rb (hunk 2 above)
Comment (citizen428) [reply app/controllers/follows_controller.rb]: @aitchiss Not sure if you're aware of it but we have a custom generator for services. `rails generate service Follows::DeleteCached`  would have created the following template (and a spec for it):

```ruby
class Follows::DeleteCached
  def self.call
    new.call
  end

  def call
  end
end
```

Comment (aitchiss) [reply app/controllers/follows_controller.rb]: I didn't know! Thanks!

File: cypress/integration/profileFlows/followUser.spec.js [hunk 6]
```diff
@@ -0,0 +1,28 @@
...
+
+    cy.get('@user').then((user) => {
+      cy.loginUser(user).then(() => {
+        cy.visit('/article_editor_v1_user');
+      });
+    });
+  });
+
+  it('follows and unfollows a user', () => {
+    //   Wait for the button to be initialised
```
Comment (jacobherrington) [inline cypress/integration/profileFlows/followUser.spec.js:14]:
```suggestion
    // Wait for the button to be initialised
```

:space_invader:

**Review by jacobherrington — APPROVED** [review]
LGTM! Nice work, this is super easy to follow. :smile:
