### PR TITLE
If there is no body of the linked issue or PR, don't render markdown

### LINKED ISSUE #14803: github liquid tag raises error when linked PR has no body
**Describe the bug**

When a github PR has no description body
When it is included in a github liquid tag

An error is shown after an empty POST to github's `/markdown` service:

```
Whoops, something went wrong:

    base: POST https://api.github.com/markdown: 422 - Missing or invalid 'text' attribute in JSON request // See: https://docs.github.com/rest/reference/markdown#render-a-markdown-document 
```

**To Reproduce**

Open a PR on a repo. For example, https://github.com/notauser/notarepo/pulls/1

Delete any body / template for the PR - should show "no description provided" on the PR page

Edit or create a new post 

Add a liquid tag github link to the PR in the markdown body

```
{% github https://github.com/notauser/notarepo/pulls/1 %}
```

Submit/publish or preview - should see this error

Screenshot from 2021-09-24 11-43-22

**Expected behavior**

Either a fallback preview (repo readme preview page?) or a meaningful/actionable error message "Must provide a PR body to embed preview" should be shown.

**Additional context**

Spinoff from #14802 since the user facing difficulty was resolved, this distills the behavior outside of the specific context.

### PR DESCRIPTION
**Pull request by djuber**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

When a PR has no body, we try to post no `body` to /markdown and ask github to render it. "body" is a required field (see https://docs.github.com/en/rest/reference/markdown#render-a-markdown-document) and an unhandled error is returned (the user sees a 422 response?).

Instead, give an empty `processed_html` body for the issue.

## Related Tickets & Documents

fixes #14803

## QA Instructions, Screenshots, Recordings

To reproduce/exercise:

```
{% github https://github.com/ospatil/nats-server/pull/1 %}
```

in main this raises a Whoops, something went wrong. On this branch you get the very slim preview with the "View on Github" button linking to the PR.

Screenshot from 2021-09-24 12-27-28

### UI accessibility concerns?

None.

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: bugfix - happy path (where issue/pr has a body) is unmodified
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [x] This change does not need to be communicated, and this is why not: small bugfix

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

File: app/models/github_issue.rb [hunk 1]
```diff
@@ -41,7 +41,8 @@ def retrieve_and_save_issue(url)
 
       # despite the counter intuitive name `.markdown` returns HTML rendered
       # from the original markdown
-      issue.processed_html = Github::OauthClient.new.markdown(issue.issue_serialized[:body])
+      issue.processed_html =
```
Comment (djuber) [inline app/models/github_issue.rb:44]: this is shorter code but might be a little wasteful (we post something to GH api when we know what to expect back).

A perfectly reasonable alternative would be

```ruby
issue.processed_html = if issue.issue_serialized[:body].present?
  Github::OauthClient.new.markdown(issue.issue_serialized[:body])
else
  ""
end
```

Comment (citizen428) [reply app/models/github_issue.rb:44]: I think I prefer the slightly longer alternative version.

**Review by citizen428 — APPROVED** [review]

**Review by juliannatetreault — APPROVED** [review]
