### PR TITLE
Message context menu in connect is not accessible #12250

### LINKED ISSUE #12250: Message Context Menu in Connect is Not Accessible
**Describe the bug**

Connect has a contextual menu on a message that lets you edit or delete a menu. It appears when you hover over a message and when you hover over the three dots icon of the menu, it provides options. It cannot be accessed via the keyboard.

image

**To Reproduce**

1. Tab through Connect. You'll be able to tab to focusable elements on a message like the user avatar or a link to the user, but that's it.
2. The menu never appears because the element is hidden until a message is hovered over with a mouse.

**Expected behavior**

A user should be able to access the contextual message menu and it's contents via keyboard or mouse.

**Screenshots**

https://user-images.githubusercontent.com/833231/104380587-3b18c100-54f9-11eb-9e0d-062539ad4b03.mp4

**Desktop (please complete the following information):**

- OS, version: N/A
- Browser, version: N/A

**Smartphone (please complete the following information):**

- Device: N/A
- OS, version: N/A
- Browser, version: N/A

**Additional context**

### PR DESCRIPTION
**Pull request by aitchiss**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

In Connect, the message options menu (the three dots at the right) previously appeared only on hover, and was inaccessible for keyboard and assistive technology users. This PR makes sure those buttons are 'real' buttons which become visible on focus as well as hover.

Other accessibility features have been added also, namely:

- The buttons are identified as having a popup with an expanded state
- The menus can be opened on keyboard Enter press as well as click
- The menus can be dismissed with the Escape key
- When opened, focus is transferred directly to the first item in the list
- When closed, focus is transferred back to the button which opened the menu
- Where the dropdown had two items, they've been changed to an unordered list so a screen reader announces how many actions are available

I've also made sure the menu closes if a user Tabs away from the menu options, in which case the trigger button is _not_ auto-focused (since the user is moving away from the menu options, we don't want to steal focus back)

### Some additional context

Dropdowns as a whole are going to be looked at in #12297. I've tried to avoid any hasty abstractions here, so when we pick up that issue we can look at the bigger picture.

## Related Tickets & Documents

Closes #12250

## QA Instructions, Screenshots, Recordings

- Start a chat in `/connect` (you may need to set up your local instance to have some mutual follows to do so)
- Write a message and send to the chat
- I found I needed to reload the page to see my sent message (not sure at the moment if that's just a problem for me locally, but mentioning just in case!)
- Check that if you hover with a mouse towards the right hand side, you can see the 'three dots' menu appear next to your message
- Check that you can click the menu for it to open
- Check that you can close the menu with Escape key
- Check that you can Tab to the menu button, and it's visible when focused
- Press Enter to open the menu and check that the first item (Edit) is focused
- Check you can Tab to the second item (Delete)
- Check that pressing Escape closes the menu and refocuses the button with the three dots
- Check that if you re-open the menu with the keyboard, and tab _past_ the final option, the menu closes but doesn't place focus on the three dots button
- Check that when you focus on the three dots button with a screen reader on, that it's announced as "expanded" when the dropdown is open, and "collapsed" when it's not (exact behaviour may vary with different screen readers/browsers)
- Check that even when the three dots button isn't currently visible, that it's exposed to screen readers (e.g. in the rotor)
- Log out, and log in as the chat recipient, and check the same behaviours hold true for the "three dots" button on someone else's message (in which case 'Report abuse' is the only option in the popup)

https://user-images.githubusercontent.com/20773163/118838785-e083dd00-b8bd-11eb-96f3-0b64afd91c6b.mp4

### UI accessibility concerns?

Covered in the above test steps

## Added tests?

- [X] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [X] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] Are there any post deployment tasks we need to perform?

N/A

## [optional] What gif best describes this PR or how it makes you feel?

much better

### CODE REVIEW

File: app/javascript/chat/content.jsx [hunk 1]
```diff
@@ -39,26 +39,22 @@ export class Content extends Component {
...
       // TODO: A button (role="button") cannot contain other interactive elements, i.e. buttons.
       // TODO: These should have key click events as well.
+      // eslint-disable-next-line jsx-a11y/click-events-have-key-events
       <div
         className="activechatchannel__activecontent activechatchannel__activecontent--sidecar"
         id="chat_activecontent"
         onClick={onTriggerContent}
         role="button"
         tabIndex="0"
-        aria-hidden="true"
```
Comment (aitchiss) [inline app/javascript/chat/content.jsx:61]: I've removed this, as the cypress tests highlighted we'd effectively blocked assistive tech users from this feature - I'm assuming it had been added instead of the `eslint-disable` so we'd pass the lint step despite the TODOs

File: app/javascript/chat/message.jsx [hunk 2]
```diff
@@ -22,8 +23,49 @@ export const Message = ({
   onReportMessageTrigger,
   onEditMessageTrigger,
 }) => {
+  const [dropdownOpen, setDropdownOpen] = useState(false);
```
Comment (aitchiss) [inline app/javascript/chat/message.jsx:26]: It might be that some of these changes can/will be abstracted as part of #12297

File: app/javascript/chat/message.jsx [hunk 3]
```diff
@@ -44,31 +86,76 @@ export const Message = ({
...
   );
   const dropdownReport = (
     <div className="message__actions">
-      <span className="ellipsis__menubutton">
-        <img src={ThreeDotsIcon} alt="message actions" />
-      </span>
+      <Button
+        id={dropdownTriggerId}
+        className={`ellipsis__menubutton ${
+          dropdownOpen ? 'opacity-1' : 'opacity-0'
```
Comment (aitchiss) [inline app/javascript/chat/message.jsx:137]: I'm using opacity instead of `display: none` so that the button still exists in the accessibility tree, and if a screen reader user pulls up a list of all controls on the page, this button will still appear

File: app/javascript/chat/chat.jsx [hunk 4]
```diff
@@ -664,10 +664,11 @@ export class Chat extends Component {
       });
     }
     if (messageIsEmpty) {
-      const messagesByCurrentUser = messages[activeChannelId].filter(
+      const messagesByCurrentUser = messages[activeChannelId]?.filter(
```
Comment (aitchiss) [inline app/javascript/chat/chat.jsx:667]: The changes in this file aren't really related to the bugfix at hand, but it was causing some unhandled exceptions that made the cypress test fail 🙃 

I don't really like this whole chunk of code but I'm conscious of scope creep and refactoring it doesn't really belong in this PR. The remainder of changes in this file are just formatting via prettier

File: cypress/integration/chatFlows/messageOptions.spec.js [hunk 5]
```diff
@@ -0,0 +1,74 @@
...
+    cy.fixture('users/chatUser2.json').as('user2');
+
+    cy.get('@user').then((user) => {
+      cy.loginUser(user).then(() => {
+        cy.visit('/connect');
+      });
+    });
+  });
+
+  it('should show message option menus', () => {
```
Comment (aitchiss) [inline cypress/integration/chatFlows/messageOptions.spec.js:19]: I'm going to re-run the frontend tests job a few times in Travis to make sure this is stable - I initially had some issues and it's got a lot of steps, so I'll try to be extra sure I'm not introducing anything potentially flaky

Comment (aitchiss) [reply cypress/integration/chatFlows/messageOptions.spec.js:19]: Ran 5 times and all green, so I think we're good ✅

File: app/assets/stylesheets/chat.scss [hunk 6]
```diff
@@ -920,20 +920,25 @@
...
-    .messagebody__dropdownmenu {
-      display: block;
+    .ellipsis__menubutton {
+      opacity: 1;
+    }
+  }
+
+  &:focus-within {
+    .ellipsis__menubutton {
+      opacity: 1;
```
Comment (nickytonline) [inline app/assets/stylesheets/chat.scss:941]: Nice!

File: app/javascript/chat/chat.jsx [hunk 7]
```diff
@@ -664,10 +664,11 @@ export class Chat extends Component {
...
         (message) => message.user_id === currentUserId,
       );
       const lastMessage =
+        messagesByCurrentUser &&
```
Comment (nickytonline) [inline app/javascript/chat/chat.jsx:671]: Nitpick (non-blocking): Prefer optional chaining. 

```js
messagesByCurrentUser?.[messagesByCurrentUser.length - 1];
```

**Review by nickytonline — APPROVED** [review]
Tested this locally, and it behaves as expected with mouse and keyboard navigation. One small non-blocking suggestion. 🚢

**Review by Ridhwana — APPROVED** [review]
I spent time testing this PR this morning as well, and seems to work well. These are great changes thanks @aitchiss!
