### PR TITLE
Fix more button not working after navigating back to the home page

### LINKED ISSUE #11897: Clicking "more" on sidebar doesn't work immediately after clicking main logo
**Describe the bug**
Clicking "more" in the left sidebar seems to have issues sometimes.

**To Reproduce**

1. Click the main logo
2. Immediately click the "more" button in the left sidebar
3. Notice that the "more" button doesn't expand

Refresh, and it works properly again.

**Expected behavior**

Clicking "more" expands the options every time.

**Screenshots**

[Here is a video](https://p241.p3.n0.cdn.getcloudapp.com/items/GGu2pxKk/Screen%20Recording%202020-12-14%20at%2004.19.01%20PM.mp4).

### PR DESCRIPTION
**Pull request by Zhao-Andy**
## What type of PR is this? (check all applicable)
- [x] Bug Fix

## Description
This PR fixes an issue where the "More" button on the homepage doesn't have a click event listener attached to it when you navigate from the homepage, to another page, and back to the homepage.

https://user-images.githubusercontent.com/17884966/107254949-cb1d2e00-6a05-11eb-93ee-e7ea319198bf.mov

However, as you can see in the video, a new issue happens where the opened "More" links remain opened after the first navigation. This is probably not _that_ big of an issue so I decided to leave it like this, rather than not fix the current bug.

## Related Tickets & Documents
Resolves #11897 

## QA Instructions, Screenshots, Recordings
1. Make sure you have at least 6 navigation links by visiting `/admin/navigation_links`
2. Visit the home page
3. Click "More"
4. Visit another page
5. Navigate to the homepage again by clicking the home logo link
6. Click "More"
7. See that it works
8. Repeat steps 4 - 6 and see that the menu links are still opened

### UI accessibility concerns?
Nope

## Added tests?
- [x] I need help with writing tests

## Added to documentation?
- [x] No documentation needed

## [optional] Are there any post deployment tasks we need to perform?
Nope

## [optional] What gif best describes this PR or how it makes you feel?

A cat plays whack a mole with a human using their finger as the mole

### CODE REVIEW

File: app/javascript/packs/base.js [hunk 1]
```diff
@@ -14,14 +14,18 @@ function getPageEntries() {
...
 
-const menus = [...document.getElementsByClassName('js-hamburger-trigger')];
-const moreMenus = [...document.getElementsByClassName('js-nav-more-trigger')];
+let menus = [...document.getElementsByClassName('js-hamburger-trigger')];
+let moreMenus = [...document.getElementsByClassName('js-nav-more-trigger')];
 
 getInstantClick().then((spa) => {
   spa.on('change', () => {
+    let menus = [...document.getElementsByClassName('js-hamburger-trigger')];
+    let moreMenus = [...document.getElementsByClassName('js-nav-more-trigger')];
```
Comment (nickytonline) [inline app/javascript/packs/base.js:23]: Refactor (blocking): The variables are already defined in the outer scope.
```suggestion
    menus = [...document.getElementsByClassName('js-hamburger-trigger')];
    moreMenus = [...document.getElementsByClassName('js-nav-more-trigger')];
```

Refactor (suggestion): What would be better is to make all this logic a function that gets called by `InstantClick` and on page load. This is a common pattern that occurs in the code base. We want code to run on page load and also when InstantClick changes the page.

e.g.

```js
function initializeMenus() {
  const { currentPage } = document.getElementById('page-content').dataset;
  const menus = [...document.getElementsByClassName('js-hamburger-trigger')];
  const moreMenus = [...document.getElementsByClassName('js-nav-more-trigger')];
  const memberMenu = document.getElementById('crayons-header__menu');
  const menuNavButton = document.getElementById('member-menu-button');

  setCurrentPageIconLink(currentPage, getPageEntries());
  initializeMobileMenu(menus, moreMenus);
  initializeTouchDevice(memberMenu, menuNavButton);
}

getInstantClick().then((spa) => {
  spa.on('change', initializeMenus);
});

initializeMenus();
```

Not sure on the naming of that though as it's the menus being set as well as the current page icon.

**Review by nickytonline — CHANGES_REQUESTED** [review]
A small change request @Zhao-Andy.

File: app/javascript/packs/base.js (hunk 1 above)
Comment (Zhao-Andy) [reply app/javascript/packs/base.js:23]: Ahh that makes much more sense. I actually looked at another code example but didn't think to refactor it to the pattern you showed. Will update!

File: app/javascript/packs/base.js [hunk 2]
```diff
@@ -14,21 +14,20 @@ function getPageEntries() {
   });
 }
 
-const menus = [...document.getElementsByClassName('js-hamburger-trigger')];
-const moreMenus = [...document.getElementsByClassName('js-nav-more-trigger')];
+function initializeNav() {
```
Comment (nickytonline) [inline app/javascript/packs/base.js:17]: Thanks for making these changes @Zhao-Andy.

For testing this, we could add an end to end test, but I'm wondering if it's worth the effort for this particular fix. Maybe in a separate PR we could have an end to end test that tests the sidebar navigation. 🤔

Comment (Zhao-Andy) [reply app/javascript/packs/base.js:17]: @nickytonline I spent about 30 minutes trying to do this and I think I need to seed some custom data. Not sure the best way to do that, but something like:

```js
cy.exec("rails db:seed")
```

would work. However, our particular seed file doesn't have the data I need `NavigationLink`. Is there a pattern we seed data with Cypress already? If not I think we could make that!

Comment (nickytonline) [reply app/javascript/packs/base.js:17]: There's an e2e seed file where you can put that stuff. Currently I je seed file is pretty bare bones as I've only added what needs to be there for e2e tests.

Comment (Zhao-Andy) [reply app/javascript/packs/base.js:17]: Oh great, what's that file called?

Comment (nickytonline) [reply app/javascript/packs/base.js:17]: These [E2E docs](https://docs.forem.com/tests/e2e-tests/) should help as well.

**Comment by Zhao-Andy** [comment]
@nickytonline added an e2e test :D it was easier than I thought! Thanks for the help on it!

**Review by aitchiss — COMMENTED** [review]
The fix with the more link is working great for me! Only thing is I'm seeing an issue now with the hamburger menu after navigation that I can't reproduce in production:

- Select one of the links from the hamburger menu
- On the new page, try to reopen the menu
- Button won't open menu

Has something in the changes to the menuTriggers setup affected it?

https://user-images.githubusercontent.com/20773163/108518875-fa168800-72c0-11eb-828a-3edbabb51c1a.mp4

File: app/javascript/topNavigation/utilities.js [hunk 3]
```diff
@@ -145,11 +145,15 @@ export async function getInstantClick(waitTime = 2000) {
  */
 export function initializeMobileMenu(menuTriggers, moreMenus) {
   menuTriggers.forEach((trigger) => {
-    trigger.addEventListener('click', toggleBurgerMenu);
+    if (trigger.onclick === null) {
+      trigger.onclick = toggleBurgerMenu;
+    }
```
Comment (Zhao-Andy) [inline app/javascript/topNavigation/utilities.js:150]: So this resolves the issue you caught @aitchiss, which happened because InstantClick would add a second click event on top of the original. So the toggle would go `open -> close` instantly after the second page navigation.

I'm not in love with this solution but it works... I guess an alternative would be to add a ` data-listener-attached="false"` to the element and then check for that in the listener function:
```js
function toggleBurgerMenu(e) {
  if(e.dataset.listenerAttached === "false") {
    // rest of the code
  }
}
```

Comment (aitchiss) [reply app/javascript/topNavigation/utilities.js:150]: if you use `onclick = ` instead of `addEventListener` you can safely omit the `null` check, since there can only be one `onclick` property at a time (so if InstantClick tries to attach the same handler again, it just safely overwrites the first one instead of adding a second 🙂)

https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onclick#value

File: cypress/integration/navigationFlows/homePageLeftSidebar.spec.js [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+
+  it('should open the "More" links', () => {
+    // Go to home page
+    cy.visit('/');
+
+    // Click on the More... button in the nav
+    cy.get('#page-content-inner').within(() => {
+      cy.findByText('More...').click();
+      cy.findByText('More...').should('have.class', 'hidden');
+      cy.findByText('Nav link 5').should('not.have.class', 'hidden');
```
Comment (aitchiss) [inline cypress/integration/navigationFlows/homePageLeftSidebar.spec.js:14]:
```suggestion
      cy.findByText('More...').should('not.be.visible');
      cy.findByText('Nav link 5').should('be.visible');
```

(blocking) - I think we should switch up the assertion here - Cypress can detect whether or not the element is currently visible, so rather than checking for the classname that should _produce_ that effect, we can just check the end effect without worrying about the implementation 🙂

File: cypress/integration/navigationFlows/homePageLeftSidebar.spec.js [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+    // go back to the homepage with InstantClick
+    cy.intercept('/?i=i').as('homepage');
+    cy.get('.site-logo').click();
+    cy.wait('@homepage');
+
+    // repeat and assert
+    cy.get('#page-content-inner').within(() => {
+      cy.findByText('More...').click();
+      cy.findByText('More...').should('have.class', 'hidden');
+      cy.findByText('Nav link 5').should('not.have.class', 'hidden');
```
Comment (aitchiss) [inline cypress/integration/navigationFlows/homePageLeftSidebar.spec.js:28]:
```suggestion
      cy.findByText('More...').should('not.be.visible');
      cy.findByText('Nav link 5').should('be.visible');
```
(as above)

File: cypress/integration/navigationFlows/homePageLeftSidebar.spec.js [hunk 6]
```diff
@@ -0,0 +1,31 @@
...
+      // visit another page with InstantClick
+      cy.findByText('Nav link 0').click();
+    });
+
+    // go back to the homepage with InstantClick
+    cy.intercept('/?i=i').as('homepage');
```
Comment (aitchiss) [inline cypress/integration/navigationFlows/homePageLeftSidebar.spec.js:20]: this is cool 😎

**Review by aitchiss — CHANGES_REQUESTED** [review]
This is looking great! Tested locally on desktop and mobile and all looking good - I just have a small change request for the Cypress test but otherwise looks good to me 👍

**Review by aitchiss — APPROVED** [review]
LGTM 🙂

File: app/javascript/topNavigation/utilities.js [hunk 7]
```diff
@@ -145,11 +145,11 @@ export async function getInstantClick(waitTime = 2000) {
  */
 export function initializeMobileMenu(menuTriggers, moreMenus) {
   menuTriggers.forEach((trigger) => {
-    trigger.addEventListener('click', toggleBurgerMenu);
+    trigger.onclick = toggleBurgerMenu;
```
Comment (nickytonline) [inline app/javascript/topNavigation/utilities.js:148]: Refactor (potentially blocking): @Zhao-Andy, curious why this was converted from a more standard `addEventListener`.

Comment (Zhao-Andy) [reply app/javascript/topNavigation/utilities.js:148]: 👋 Suzanne caught an issue earlier, and I left a comment that's resolved now about it: https://github.com/forem/forem/pull/12612#discussion_r579309338

> So this resolves the issue you caught @aitchiss, which happened because InstantClick would add a second click event on top of the original. So the toggle would go open -> close instantly after the second page navigation.

Comment (nickytonline) [reply app/javascript/topNavigation/utilities.js:148]: Ah, understood. There might be a better way to handle this, but for now, I think this is fine. I would add a comment in the code though explaining this.

File: cypress/integration/navigationFlows/homePageLeftSidebar.spec.js [hunk 8]
```diff
@@ -0,0 +1,31 @@
...
+  });
+
+  it('should open the "More" links', () => {
+    // Go to home page
+    cy.visit('/');
+
+    // Click on the More... button in the nav
+    cy.get('#page-content-inner').within(() => {
+      cy.findByText('More...').click();
+      cy.findByText('More...').should('not.be.visible');
```
Comment (nickytonline) [inline cypress/integration/navigationFlows/homePageLeftSidebar.spec.js:13]: refactor (non-blocking): chain Cypress commands since a reference to the element will already exist.

```suggestion
      cy.findByText('More...').click().should('not.be.visible');
```

File: cypress/integration/navigationFlows/homePageLeftSidebar.spec.js [hunk 9]
```diff
@@ -0,0 +1,31 @@
+describe('Home Page Left Sidebar', () => {
```
Comment (nickytonline) [inline cypress/integration/navigationFlows/homePageLeftSidebar.spec.js:1]: test (blocking): The test runs fine, but I am unable to rerun it. It fails on subsequent runs waiting for the homepage. I'm not sure why yet. This is fine for CI, but for someone writing tests, this will constantly fail after the first time it's run.

image

**Review by nickytonline — CHANGES_REQUESTED** [review]
This looks good Andy. There is just an issue with rerunning the e2e test you added.

File: cypress/integration/navigationFlows/homePageLeftSidebar.spec.js (hunk 9 above)
Comment (Zhao-Andy) [reply cypress/integration/navigationFlows/homePageLeftSidebar.spec.js:1]: Hmm not sure what happened but I can't reproduce it, at least after I merged master and fixed conflicts. Maybe that was related somehow?

**Comment by Zhao-Andy** [comment]
@nickytonline bumping this review now that you're back :)

**Comment by vaidehijoshi** [comment]
Hi all! Just wanted to check in on this issue as I believe it came up in a product demo to a customer recently and it would be rad to try to get this addressed soon 😃 Are there any blockers I can help with here or is it just waiting for one more review? Let me know if I can help get this over the finish line!

**Comment by Zhao-Andy** [comment]
Hey @vaidehijoshi! @nickytonline has reviewed it for me but is running into the same issue where the E2E tests are failing after a second run. At this point maybe I should move the specs into a different PR, since I know there have been a few requests for this to be fixed sooner rather than later. Thoughts?

File: cypress/integration/navigationFlows/homePageLeftSidebar.spec.js [hunk 10]
```diff
@@ -0,0 +1,29 @@
...
+    cy.get('#page-content-inner').within(() => {
+      cy.findByText('More...').click().should('not.be.visible');
+      cy.findByText('Nav link 5').should('be.visible');
+      // visit another page with InstantClick
+      cy.findByText('Nav link 0').click();
+    });
+
+    // go back to the homepage with InstantClick
+    cy.intercept('/?i=i').as('homepage');
+    cy.get('.site-logo').click();
```
Comment (nickytonline) [inline cypress/integration/navigationFlows/homePageLeftSidebar.spec.js:20]: Tests (blocking): As demonstrated in our pairing session, using Cypress testing library had the test passing reliably on my machine.

```suggestion
    cy.findAllByLabelText('DEV(local) Home').first().click();
```

**Review by nickytonline — APPROVED** [review]
This looks great @Zhao-Andy. One change request and this is good to go. Approving as you mentioned you were going to make the change.
