### PR TITLE
Runtime class for standardized native features

### LINKED ISSUE #9962: Native sharing not working
**Describe the bug**

When I tap the ellipsis, I don't see a native share dialog.

**To Reproduce**

1. Open an article
2. Tap the ellipsis

**Expected behavior**

I expected to see a native share dialog, as depicted in #1524

**Screenshots**

**Desktop (please complete the following information):**

N/A

**Smartphone (please complete the following information):**

- Device: Google Pixel 4
- OS, version: Android 10
- Browser, version: Chrome 84.0.4147.125

**Additional context**

Not familiar with this codebase, but it looks like this area may have been touched in #6815

### PR DESCRIPTION
**Pull request by fdoxyz**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [x] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description

Another step towards better global management of mobile native features. The new `Runtime` class can be used for checking whether a specific feature is available in the current context. It supports the use of a namespace for more granular checks, which helps deploy logic to the web JS before the native app release is published. This prevents breaking current/older native app releases.

__What's included in the PR:__
- All `isNativeIOS`/`isNativeAndroid` functions spread throughout the codebase now live in a single location
- Fixes #9962 by making use of the native share feature on Android devices
- Replaces the Google Analytics events from Podcasts with Ahoy in the same way as the Video Player (see #9539)

__What's not included in the PR:__
The Strategy pattern for Podcasts ([suggested here](https://github.com/forem/forem/pull/8054#discussion_r430210129)) is not fully implemented, because it requires a more thorough refactor of the Podcast player. It should ideally pick a strategy and reuse the code without caring whether we're working with mobile vs web.

This is an improvement though, because in the past we were doing checks to see if it was Android/iOS/web many times throughout the player. With this refactor we now make use of the Strategy pattern by storing the correct strategy during initialization in `Runtime.podcastMessage` and only if `undefined` we execute the web logic. This reduces from many checks to one `if (Runtime.podcastMessage) { ... } else { ... }`).

## Related Tickets & Documents

#9962 

## QA Instructions, Screenshots, Recordings

The copy to clipboard features in the following locations should continue to work in web & mobile:
- Image upload in Editor
- Connect share invitation link
- Article show page dropdown (copy URL)

The Podcast & video player should work both in web & mobile apps.

I understand checking that the native app features continue to work is tricky. Here's a video of it working but if interested in trying it out locally feel free to ask for help and I'll be happy to walk through the process.

https://share.getcloudapp.com/jkuZvBLY

## Added tests?

- [ ] yes
- [ ] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

I promise I'll get you out

### CODE REVIEW

File: app/assets/javascripts/initializers/initializeCommentDropdown.js [hunk 1]
```diff
@@ -113,6 +107,13 @@ function initializeCommentDropdown() {
       return;
     }
 
+    // Android native apps have enhanced sharing capabilities for Articles
+    const articleShowMoreClicked = button.id === 'article-show-more-button';
+    if (articleShowMoreClicked && Runtime.isNativeAndroid('shareText')) {
```
Comment (cglong) [inline app/assets/javascripts/initializers/initializeCommentDropdown.js:112]: Does this work for web/PWA users like #1524?

Comment (cglong) [inline app/assets/javascripts/initializers/initializeCommentDropdown.js:112]: Does this work for web/PWA users like #1524?

**Review by citizen428 — APPROVED** [review]
Nice, I like where this is going 👍  

Even if it's not fully implemented for podcasts yet, it feels like something we can gradually introduce in more places, pushing up the level of abstraction in the process (i.e. by switching only once on runtime env and picking the right strategy for the rest of the run which executes without further conditions).

File: app/assets/javascripts/initializers/initializeCommentDropdown.js (hunk 1 above)
Comment (fdoxyz) [reply app/assets/javascripts/initializers/initializeCommentDropdown.js:112]: At the moment it doesn't as this is only available in the native app environment, thank you for the follow up this is a good catch. I think it can be tweaked so it supports the PWA environment as well. I'll try out a few ideas and push another commit soon 👍

Comment (fdoxyz) [reply app/assets/javascripts/initializers/initializeCommentDropdown.js:112]: After trying a few ideas I made it work but there's a few edge cases where this doesn't play well for all platforms. 

I'll be tackling PWA support and other mobile platforms (iOS currently doesn't have this enhanced experience either) in a separate PR since this refactor looks good for now.

I'll report updates on this over in #9962
