### PR TITLE
Fixed twitter timeline display in comments preview

### LINKED ISSUE #12039: Twitter timeline liquid tag loses content in article comment preview
**Describe the bug**

When live previewing article comment, twitter timeline's content couldn't render properly. It's only showing the CTA button

**To Reproduce**

1. Go to any article
2. Scroll down to comment section
3. Copy and paste this code:

```
{% twitter_timeline https://twitter.com/NYTNow/timelines/576828964162965504 %}
```

4. Click Preview button

**Expected behavior**

The content should be displayed like live preview in [Write a new post](https://dev.to/new) page

**Screenshots**

screenshot

**Desktop (please complete the following information):**

- OS, version: N/A
- Browser, version: Mozilla Firefox 84.0.1

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by akashdotsrivastava**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
The tweet timeline/tweet itself does not show up when we add a tweet_timeline tag in a comment under an article and hit Preview. The only thing that shows up is the CTA button view on twitter. This PR fixes the issue.

## Related Tickets & Documents
Closes #12039 

## QA Instructions, Screenshots, Recordings

- Go to any article
- Scroll down to comment section
- Copy and paste this code:

{% twitter_timeline https://twitter.com/NYTNow/timelines/576828964162965504 %}

- Click Preview button
- Observe that the tweet timeline shows up along with the CTA view on twitter button, as opposed to just the CTA button showing up in master

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://docs.forem.com/frontend/accessibility)._

## Added tests?

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## Added to documentation?

- [ ] [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/)
- [ ] README
- [ ] No documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

File: spec/support/twitter_timeline_tag_context.rb [hunk 1]
```diff
@@ -0,0 +1,16 @@
+shared_context "with twitter_timeline_tag" do
```
Comment (rhymes) [inline spec/support/twitter_timeline_tag_context.rb:1]: I'm not super keen on using shared contexts if there's nothing to share. I'd rather these things be extracted when they are needed to be extracted. The likeliness we need to check these expectations in multiple places are very slim (after all they are only supported in articles and comments). I'd rather this code stay in `spec/system/comments/user_fills_out_comment_spec.rb` for now

**Review by rhymes — COMMENTED** [review]
Works great! Left a note about code organization.

Thank you a lot @akashdotsrivastava!

File: spec/support/twitter_timeline_tag_context.rb (hunk 1 above)
Comment (akashdotsrivastava) [reply spec/support/twitter_timeline_tag_context.rb]: Makes sense. Made changes.

File: spec/system/comments/user_fills_out_comment_spec.rb [hunk 2]
```diff
@@ -116,6 +117,21 @@
...
+      visit article.path.to_s
+
+      wait_for_javascript
+    end
+
+    it "User fill out comment box with a TwitterTimeline tag, then clicks preview" do
+      fill_in "text-area", with: twitter_comment
+      click_button("Preview")
+
+      expect(page).to have_css(".ltag-twitter-timeline-body iframe", count: 1)
```
Comment (msarit) [inline spec/system/comments/user_fills_out_comment_spec.rb:131]: Hey @akashdotsrivastava. When I pulled your branch down, this spec keeps failing. Specifically, the output states that it cannot find the element with CSS `.ltag-twitter-timeline-body iframe`.

It may be just on my end though 🤷🏾‍♀️

Comment (rhymes) [reply spec/system/comments/user_fills_out_comment_spec.rb:131]: @msarit I feel you. I always have trouble with system tests locally, that's why I cannot wait for us to switch to E2E for all of these. That said, I tried to run `bundle exec rspec spec/system/comments/user_fills_out_comment_spec.rb` and it doesn't pass for me either

Comment (akashdotsrivastava) [reply spec/system/comments/user_fills_out_comment_spec.rb:131]: Hey @msarit and @rhymes . Thanks for your comments. I went back and double-checked the above spec. I ran it as a solitary as well the whole suite. Passed in both the cases.

Is there something I can do to make sure it works more convincingly? I mean it is more or less a copy of a similar test that tests runkit tag on preview and checks if the runkit iframe exists, only the same for Twitter in this case. I see it passing though in the build https://travis-ci.com/github/forem/forem/jobs/479982271

Comment (rhymes) [reply spec/system/comments/user_fills_out_comment_spec.rb:131]: Nope, I trust your code and CI. Thank you for clarifying!

**Review by rhymes — APPROVED** [review]
LGTM

**Review by aitchiss — APPROVED** [review]
looks good to me 👍

**Comment by cmgorton** [comment]
Thanks for this contribution @akashdotsrivastava🎉
