### PR TITLE
fix request center UI

### LINKED ISSUE #10823: Connect: Request center overlays last chat
**Describe the bug**

When opening the request center from a connect channel it overlays the existing channel which makes it hard to read. Switching away from the app and then switching back gives the desired result.

**To Reproduce**

1. Go to the Connect.
2. Open the Request Center
    Screenshot_13_10_20_11_40
3. The Request Center overlays the current chat, which reamins scrollable in the background (but resized)
    IMG_1145
4. Switch away from the app
5. Switch back, everything works now.
    IMG_1147

**Expected behavior**

End up with the correct view right away.

**Smartphone (please complete the following information):**

- Device: iPhone 11
- OS, version: iOS 14.0.1
- Browser, version: DEV app

### PR DESCRIPTION
**Pull request by narender2031**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
- When users click on the request center in mobile UI.  chat text is shown override with request center UI. 

## Related Tickets & Documents
- Closes #10823 
## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] docs.forem.com
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Review by benhalpern — APPROVED** [review]
Looks good to me.

File: app/javascript/chat/RequestManager/RequestManager.jsx [hunk 1]
```diff
@@ -130,7 +130,7 @@ export default class RequestManager extends Component {
     const { channelJoiningRequests, userInvitations } = this.state;
 
     return (
-      <div className="activechatchannel__activeArticle activesendrequest">
+      <div className="activesendrequest">
```
Comment (nickytonline) [inline app/javascript/chat/RequestManager/RequestManager.jsx:133]: I looked through the code base and the `activesendrequest` CSS class is not defined anywhere in the code base. The only reference to is in this file and channelRequest.jsx.

@narender2031 @sarthology, is this class constructed somewhere in JS or is this class no longer required?

image

**Review by citizen428 — APPROVED** [review]
