### PR TITLE
Storybook dropdown should be accessible 11724

### LINKED ISSUE #11724: Storybook: dropdown should be accessible
**Describe the bug**

In going through the components in Storybook, I found a dropdown that needs to be made accessible. It resembles the "hover only button" mentioned in #7139, which makes me think that possibly the implementation on the live site was updated but Storybook was not. This dropdown only shows content on hover of a link that looks like a button, and it's not keyboard accessible. It should be a `<button>` element and show content when activated with the keyboard.

I worked on a dropdown implementation in #11509 that could be referenced for this work, particularly for keyboard events and focus management. It would be great to have a repeatable component that's accessible, so all instances could be brought up to date.

**To Reproduce**

1. Go to https://storybook.forem.com/?path=/story/components-dropdowns--default
2. Observe the button that says "Hover to trigger dropdown"
3. Try focusing it with your keyboard, and you'll find the content isn't accessible without a mouse.

**Expected behavior**

The button should be focusable but only toggle content on Enter/Space or the Escape keys. It should have some ARIA attributes that indicate it's a toggle control, such as `aria-haspopup` and `aria-expanded`.

**Screenshots**

Storybook with hover dropdown open in Element Inspector

**Desktop (please complete the following information):**

- OS, version: All
- Browser, version: All

**Smartphone (please complete the following information):**

- Device: All
- OS, version: All
- Browser, version: All

**Additional context**

This is part of a broader review of Storybook components, so issues will be filed separately.

### PR DESCRIPTION
**Pull request by aitchiss**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [X] Documentation Update

## Description

This PR updates the Dropdown Storybook stories so that they are keyboard accessible. The dropdowns can now be opened  and closed by keyboard (Enter / Esc), and can also be closed by clicking outside of the dropdown.

Notes have been added to the stories to give context on accessibility implications when using the dropdown component.

This PR ensures that our Storybook documents accessible usage of the Dropdown component, however wider work is needed to ensure all dropdowns used throughout the app are consistently handling keyboard events and focus in a way optimised for accessibility. This will need to be a generalised approach that accounts for both Preact and non-Preact usage. A new issue has been created for this here: #12297 

## Related Tickets & Documents

Closes #11724 - Storybook dropdown should be accessible

## QA Instructions, Screenshots, Recordings

- Open Storybook and navigate to Dropdowns
- In each of the Dropdown stories, you should be able to:
-- Focus the activator button by pressing the Tab key
-- When pressing enter on the focused button, the dropdown content should appear, and focus should be sent to the link inside the content
-- When the dropdown is open, pressing Escape should close it
-- When the dropdown is open, clicking outside of the dropdown content should close it
-- Clicking the button with the mouse should toggle the dropdown content open/closed
-- When using a screen reader (I have tested this on Safari with VoiceOver), the expanded/collapsed state of the dropdown should be announced when the activator button is focused

### UI accessibility concerns?

See above QA instructions. 

Please also note I've disabled a jsx-a11y warning regarding the `keyUp` handler on the wrapping `div` in both `Dropdown.stories.jsx` and `dropdown.html.stories.jsx`.  The event handler has been added to the containing (non-interactive) `div` to ensure Escape key presses are captured to collapse the dropdown content. As the containing `div` isn't expected to be interactive, the linter warning is in this case a false positive. A comment has been added to the code to this effect too.

## Added tests?

- [ ] Yes
- [X] No, and this is why: the underlying Dropdown component has not been changed, the code changes only impact the Storybook documentation
- [ ] I need help with writing tests

## Added to documentation?

- [ ] [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/)
- [ ] README
- [ ] No documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

a stoat pops its head up and down

### CODE REVIEW

File: app/javascript/.storybook/preview.js [hunk 1]
```diff
@@ -67,6 +67,7 @@ const themeSwitcherDecorator = (storyFn) => {
 };
 
 addDecorator(themeSwitcherDecorator);
+addDecorator((Story) => <Story />);
```
Comment (aitchiss) [inline app/javascript/.storybook/preview.js:70]: This allows use to use Preact hooks in Storybook

File: app/javascript/crayons/Dropdown/__stories__/dropdowns.md [hunk 2]
```diff
@@ -9,3 +9,16 @@ dependent on width:
...
+When a dropdown of options is opened, focus should be sent to the first
+interactive item inside the dropdown content. When the dropdown is closed, focus
+should return to the activator button. If there are no interactive items,
+consider using an `aria-live` region to ensure the new content is announced to
+screen-reader users when the dropdown appears.
+
+A user should be able to open and close the dropdown by keyboard (e.g. using
+Enter and Escape), and appropriate `aria` (e.g. `aria-haspopup`) should be used
+to indicate the relationship between the activator button and the dropdown
+content.
```
Comment (vaidehijoshi) [inline app/javascript/crayons/Dropdown/__stories__/dropdowns.md:24]: 👏🏽👏🏽

File: app/javascript/crayons/Dropdown/__stories__/dropdowns.md [hunk 3]
```diff
@@ -9,3 +9,16 @@ dependent on width:
...
+### Dropdown accessibility
+
+When a dropdown of options is opened, focus should be sent to the first
+interactive item inside the dropdown content. When the dropdown is closed, focus
+should return to the activator button. If there are no interactive items,
+consider using an `aria-live` region to ensure the new content is announced to
+screen-reader users when the dropdown appears.
+
+A user should be able to open and close the dropdown by keyboard (e.g. using
+Enter and Escape), and appropriate `aria` (e.g. `aria-haspopup`) should be used
```
Comment (vaidehijoshi) [inline app/javascript/crayons/Dropdown/__stories__/dropdowns.md:22]:
```suggestion
Enter and Escape), and appropriate `aria` attributes (e.g. `aria-haspopup`) should be used
```
Thought this might be nice to add in case someone is unfamiliar with `aria` :)

**Review by vaidehijoshi — APPROVED** [review]
Works beautifully!! :) 

> -- When using a screen reader (I have tested this on Safari with VoiceOver), the expanded/collapsed state of the dropdown should be announced when the activator button is focused

Also, super impressed that you added screen reader QA instructions to this -- I _love_ that! Thank you 💞

File: app/javascript/crayons/Dropdown/__stories__/dropdowns.md [hunk 4]
```diff
@@ -9,3 +9,16 @@ dependent on width:
 - < 250px: 16px 251 - 320px: 24px
 
 FYI: Dropdowns use “Box” component as background, with Level 3 elevation.
+
+### Dropdown accessibility
```
Comment (rhymes) [inline app/javascript/crayons/Dropdown/__stories__/dropdowns.md:13]: ❤️

**Review by rhymes — COMMENTED** [review]
Hi @aitchiss, love the idea!

I tried to test it and I wasn't able to use the keyboard, I'm 100% sure I'm doing something wrong though.

1. I checked out the PR
2. Ran `yarn storybook`
3. Went to http://localhost:6006/?path=/story/components-dropdowns--default
4. Tabbed a bit until the dropdown was in focus but as I hit the enter key, the page reloads (I tried both on Firefox and Chromium-based Edge)

Here's a gif if it can help:

dropdown

**Comment by aitchiss** [comment]
> Hi @aitchiss, love the idea!
> 
> I tried to test it and I wasn't able to use the keyboard, I'm 100% sure I'm doing something wrong though.
> 
> 1. I checked out the PR
> 2. Ran `yarn storybook`
> 3. Went to http://localhost:6006/?path=/story/components-dropdowns--default
> 4. Tabbed a bit until the dropdown was in focus but as I hit the enter key, the page reloads (I tried both on Firefox and Chromium-based Edge)
> 
> Here's a gif if it can help:
> 
> dropdown

Hey @rhymes - thanks for the review! What you're experiencing is an issue with the visible focus state of the link in the dropdown... The dropdown link goes to "/" which is why when you hit enter again it's reloading the home path.

I'm not sure why a default focus style isn't visible for a link (I didn't add any additional CSS to it) but I agree it's a confusing bit of documentation if you can't see that focus move, so I'll tweak it a bit to make it clearer 👍

File: app/javascript/crayons/Dropdown/__stories__/dropdowns.md (hunk 3 above)
Comment (aitchiss) [reply app/javascript/crayons/Dropdown/__stories__/dropdowns.md]: Nice - you're totally right, it makes it a bit clearer

**Comment by rhymes** [comment]
@aitchiss I managed to see your code, I had to remove the `app/javascript/storybook-static` folder and re-run Storybook. I guess it didn't pick the changes. Will review and report back

**Review by rhymes — APPROVED** [review]
I tried again with Edge, Chrome and Firefox and it works, thank you!

**Comment by aitchiss** [comment]
thanks @rhymes - good to know about that `storybook-static` folder for future!

**Comment by aitchiss** [comment]
@vaidehijoshi / @rhymes - I've pushed a commit since you approved - it's a minor CSS change to make the focus on the dropdown's link visible. Just in case you want to have a look at it.

**Comment by rhymes** [comment]
@aitchiss re-tested, can't accept twice, but let's say: signed and sealed :D

**Review by vaidehijoshi — APPROVED** [review]
