### PR TITLE
Keep `published_at` when changing author of a scheduled article from the dashboard

### LINKED ISSUE #18609: Setting post author overrides post scheduling
**Describe the bug**

I scheduled [the scheduling feature announcement post on CodeNewbie](https://community.codenewbie.org/codenewbie/this-post-is-scheduled-for-330pm-us-eastern-time-39fe) for 3:30pm ET, which worked as expected. I then switched the author to Ben within the CodeNewbie Team via the Dashboard, and it posted immediately (3:06pm ET). I was able to rectify the issue by resetting the post time to the future time of 3:30pm ET in the Admin view. I am not sure if this would reproduce on another Forem.

**To Reproduce**

1. Create a post in CodeNewbie Community under the CodeNewbie Team
2. Schedule the post for a future time using the schedule post feature
3. Save draft
4. Go to Dashboard and navigate to CodeNewbie Team
5. Navigate to the scheduled post, select "edit," and select a different author from the dropdown
6. If the bug reproduces, the post will publish immediately

**Expected behavior**

I expected [this post](https://community.codenewbie.org/codenewbie/this-post-is-scheduled-for-330pm-us-eastern-time-39fe) to publish at its scheduled time with its assigned author in the byline.

**Desktop (please complete the following information):**

- OS, version: macOS Monterey v12.3.1
- Browser, version: Google Chrome Version 106.0.5249.119 (Official Build) (arm64)

### PR DESCRIPTION
**Pull request by lightalloy**
## What type of PR is this? (check all applicable)
- [x] Bug Fix

## Description
Fixes a bug described in #18609
While exploring the problem I found out two issues instead of one:
1) Changing an author of a scheduled DRAFT: author was not saved
2)  Changing an author of a scheduled article: author was saved, but `published_at` was updated to current time, and the post was published immediately
This pr should fix both issues.

The problem was that if we don't pass `published_at` to `ArticlesController#update`, we assume that we want to nullify it and publish immediately. But that's not what we want when updating an author.

## Related Tickets & Documents
- Closes #18609

## QA Instructions, Screenshots, Recordings
Before testing, I recommend to reproduce the bugs described earlier.

1) create a scheduled article under an org
2) go to the dashboard
3) choose the org from the dropdown
изображение
4) press 3 dots in your article row, change the author from the dropdown
изображение

5) the author should have changed and the `published_at` should remain as it was before.

Perform the same steps for the scheduled draft (in the first step - choose published_at from post options, then click "Save draft" instead of "Schedule")

## Added/updated tests?

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [x] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

### CODE REVIEW

File: app/controllers/articles_controller.rb [hunk 1]
```diff
@@ -327,6 +328,12 @@ def article_params_json
       allowed_params << :organization_id
     end
 
+    manage_published_at_params
```
Comment (lightalloy) [inline app/controllers/articles_controller.rb:331]: Not a great improvement, I just moved the code to a separate method to please rubocop. I would prefer a more serious refactoring, but that's a separate task.

File: app/views/dashboards/_dashboard_article.html.erb [hunk 2]
```diff
@@ -16,7 +16,7 @@
     <div id="ellipsis-menu-dropdown-<%= article.id %>" class="crayons-dropdown top-100 right-0 z-10 align-left js-ellipsis-menu-dropdown">
       <%= form_for(article, method: :patch, remote: true, authenticity_token: true, html: { "data-type": "json", class: "p-0 js-archive-toggle" }) do |f| %>
         <%= f.hidden_field :archived, value: !article.archived %>
-
+        <%= f.hidden_field :from_dashboard, value: 1 %>
```
Comment (lightalloy) [inline app/views/dashboards/_dashboard_article.html.erb:19]: I added `from_dashboard` just in case here, this partial is only used for published posts, and the bug is only related to the scheduled, but still we don't pass `published_at` here, so it makes sense to make sure that we don't intend to nullify it.

**Review by jaw6 — APPROVED** [review]

**Review by Ridhwana — APPROVED** [review]
