### PR TITLE
Don't include "anti-followed" tags in email digest

### LINKED ISSUE #13915: Community Digest Emails Not Factoring in Anti-Follows
**Describe the bug**

Users are receiving links to posts on tags that they are "anti-following" — i.e. tags that they have adjusted to have a negative follow weight from https://dev.to/dashboard/following_tags.

**To Reproduce**

1. Follow a tag(s) that you want to anti-follow
2. Go to 'https://dev.to/dashboard/following_tags' and adjust this tag's follow weight to be negative
3. Ensure that you have check "Send me a periodic digest of top posts from my tags" in 'https://dev.to/settings/notifications' -->
4. Look for incongruencies in emails

**Expected behavior**

If you are anti-following a tag, you should not receive suggested posts that include these tags in your community digest.

**Additional context**

A DEV user wrote in to describe this issue.

One odd consideration, what do we do with posts that include tags the user is following, but also include tags that the user is anti-following? Do we send these posts to the user? I believe we should probably exclude these posts, but wanted to bring this up as something to keep in mind.

### PR DESCRIPTION
**Pull request by citizen428**
## What type of PR is this? (check all applicable)

- [X] Refactor
- [X] Bug Fix

## Description

The digest emails could include articles for the tags the user "anti-followed". In case you aren't aware of this feature, "anti-following is done somewhat counter-intuitively by following a tag first and then assigning it a negative score.

image

In the case of the digest email, this led to a problem because `EmailDigestArticleCollector` only checked if `User#cached_followed_tag_names` contains any tags, without also checking if any of them are anti-follows. I suspect that the same mechanism is creating problems in other areas too, e.g. I saw the same method being used in `Users::SuggestRecent` but again we don't seem to differential between follows and anti-follows.

This PR does the following:

* Change `User#cached_followed_tag_names` to only include tags with a score >= 1.
* Introduce `User#cached_antifollowed_tag_names` that includes tags with a score < 1.
* Update `EmailDigestArticleCollector` to take both into account for the purposes of the `user_has_followings?` helper because otherwise there'd be a corner-case where we fall back to all articles if a user has only anti-followed tags. Since this class uses `@user.followed_articles` which in turn relies on `cached_followed_tag_names` this class should no longer return articles the user is actively trying to avoid.
* Since I was dealing with tags already, I thought it might be a good idea to also excluded anti-followed tags from the tag list in the left sidebar.

## Related Tickets & Documents

Closes #13915

## QA Instructions, Screenshots, Recordings

* The unit tests hopefully have this covered quite well.

### UI accessibility concerns?

None

## Added/updated tests?

- [X] Yes

## [Forem core team only] How will this change be communicated?

- [X] I will share this change internally with the appropriate teams

### CODE REVIEW

File: app/javascript/leftSidebar/TagsFollowed.jsx [hunk 1]
```diff
@@ -23,6 +23,14 @@ export const TagsFollowed = ({ tags = [] }) => {
             href={`/t/${tag.name}`}
           >
             {`#${tag.name}`}
+            {tag.points < 1 && (
```
Comment (citizen428) [inline app/javascript/leftSidebar/TagsFollowed.jsx:26]: Is this still an acceptable pattern in modern React and in line with our current practices?

File: app/models/user.rb [hunk 2]
```diff
@@ -307,6 +307,20 @@ def cached_followed_tag_names
         id: Follow.where(
           follower_id: id,
           followable_type: "ActsAsTaggableOn::Tag",
+          points: 1..,
```
Comment (citizen428) [inline app/models/user.rb:310]: This ensures that `cached_followed_tag_names` really only includes followed tags.

File: app/models/user.rb [hunk 3]
```diff
@@ -307,6 +307,20 @@ def cached_followed_tag_names
...
+        ).select(:followable_id),
+      ).pluck(:name)
+    end
+  end
+
+  def cached_antifollowed_tag_names
```
Comment (citizen428) [inline app/models/user.rb:316]: Yes, there's repetition between these two methods. No, I don't think that's a problem.

File: app/services/broadcasts/welcome_notification/generator.rb [hunk 4]
```diff
@@ -99,7 +99,7 @@ def authenticated_with_all_providers?
       end
 
       def user_following_tags?
-        user.cached_followed_tag_names.count > 1
```
Comment (citizen428) [inline app/services/broadcasts/welcome_notification/generator.rb:102]: I'm not sure why we used `> 1` here instead of `>= 1` but `.any?` seems to actually make the most sense.

File: app/javascript/leftSidebar/TagsFollowed.jsx (hunk 1 above)
Comment (aitchiss) [reply app/javascript/leftSidebar/TagsFollowed.jsx:26]: Generally I'd suggest using a ternary with `null` as the `&&` approach [can sometimes lead to unexpected consequences](https://kentcdodds.com/blog/use-ternaries-rather-than-and-and-in-jsx) (it doesn't in this case though, so please just take this as a general suggestion, and it would definitely be fine and in-keeping with a lot of our other code as-is)

**Comment by benhalpern** [comment]
This looks good to me.

In the long run I'd definitely be in favor of getting rid of the "anti-follow" which is more of a hack in favor of being able to mute a tag (which could even apply similar logic under the hood if that made sense).

Definitely cool with applying this now though. No need to wait on improving functionality in favor of something in the future.

File: app/javascript/leftSidebar/TagsFollowed.jsx (hunk 1 above)
Comment (citizen428) [reply app/javascript/leftSidebar/TagsFollowed.jsx:26]: Thanks for the link. Since the predicate returns an actual boolean this is one of the safe use-cases, so I'm inclined to leave as-is, as I find it slightly cleaner than the ternary version. Maybe we can standardize one way to do this in the future.

**Comment by citizen428** [comment]
@benhalpern Great, thanks! I was thinking along the lines of a separate way to "mute" a tag, even if that just creates an anti-follow as before. For now, my main goal was fixing the digest email issue but this seemed like it could be a bigger win since it also potentially fixes problems in other areas.

**Comment by citizen428** [comment]
As is sometimes the case, this seemed easier originally than it turned out to be. At the heart of `EmailDigestArticleCollector` we use `User#followed_articles` which in turns uses `User#cached_followed_tag_names`. While this list no longer includes antifollowed tags we're also *not* explicitly excluding them, so they can still slip through. For this query we don't join articles and tags, probably for performance reasons but instead rely on the following two helpers which match against `Article#cached_tag_list`:

```ruby
  scope :cached_tagged_with, lambda { |tag|
    case tag
    when String, Symbol
      # In Postgres regexes, the [[:<:]] and [[:>:]] are equivalent to "start of
      # word" and "end of word", respectively. They're similar to `\b` in Perl-
      # compatible regexes (PCRE), but that matches at either end of a word.
      # They're more comparable to how vim's `\<` and `\>` work.
      where("cached_tag_list ~ ?", "[[:<:]]#{tag}[[:>:]]")
    when Array
      tag.reduce(self) { |acc, elem| acc.cached_tagged_with(elem) }
    when Tag
      cached_tagged_with(tag.name)
    else
      raise TypeError, "Cannot search tags for: #{tag.inspect}"
    end
  }

  scope :cached_tagged_with_any, lambda { |tags|
    case tags
    when String, Symbol
      cached_tagged_with(tags)
    when Array
      tags
        .map { |tag| cached_tagged_with(tag) }
        .reduce { |acc, elem| acc.or(elem) }
    when Tag
      cached_tagged_with(tags.name)
    else
      raise TypeError, "Cannot search tags for: #{tags.inspect}"
    end
  }

```

Alas, these can't be easily negated and I'm a bit hesitant to add another complex scope to `Article`. 

A quicker — but less clean — potential alternative approach would be to raise the limit in `EmailDigestArticleCollector` from 6, manually filter out the antitagged ones and then take the first remaining 6 (if any). But that feels quite hacky and I'm also not super keen on that.

I'll need to dwell on this for a bit.

File: app/models/user.rb [hunk 5]
```diff
@@ -258,8 +258,14 @@ def path
   end
 
   def followed_articles
-    Article
-      .cached_tagged_with_any(cached_followed_tag_names).unscope(:select)
+    relation = Article
```
Comment (citizen428) [inline app/models/user.rb:261]: I tried to run the generate query in Blazer and it timed out. That said, the original query without exclusions also timed out. We're only using this method in `EmailDigestArticleCollector` so I hope that's ok.

@djuber Maybe you have a good way of figuring out if this is reasonably safe to deploy?

File: config/routes.rb [hunk 6]
```diff
@@ -146,7 +146,6 @@
     resources :response_templates, only: %i[index create edit update destroy]
     resources :feedback_messages, only: %i[index create]
     resources :organizations, only: %i[update create destroy]
-    resources :followed_articles, only: [:index]
```
Comment (citizen428) [inline config/routes.rb:149]: This is not directly related to this PR but I tried to see where `User#followed_articles` is used and stumbled upon this route which actually 404s:

```
ActionController::RoutingError - uninitialized constant FollowedArticlesController
Did you mean?  FollowsController:
```

File: app/workers/follows/update_points_worker.rb [hunk 7]
```diff
@@ -9,7 +9,8 @@ def perform(article_id, user_id)
       return unless article && user
 
       adjust_other_tag_follows_of_user(user.id)
-      followed_tag_names = user.cached_followed_tag_names
+      followed_tag_names =
+        user.cached_followed_tag_names + user.cached_antifollowed_tag_names
```
Comment (citizen428) [inline app/workers/follows/update_points_worker.rb:13]: I needed both for the spec to become green. @benhalpern Do you maybe have a bit more context on this? Would it e.g. be ok to remove the antifollowed tags and update the expected values in the spec? I was a bit unsure about all of this.

**Comment by djuber** [comment]
> and then assigning it a negative score

For context (I had no idea where to assign scores to tags in the UI) you want to do this at /dashboard/following_tags - where you'll see the list of followed tags and their weights (each defaulting to 1.0). After editing and selecting "update weights" you'll see the "Anti-follow" indicator next to the tag.

File: app/models/user.rb [hunk 8]
```diff
@@ -258,8 +258,14 @@ def path
...
+    if cached_antifollowed_tag_names.any?
+      relation = relation.not_cached_tagged_with_any(cached_antifollowed_tag_names)
+    end
+
+    relation
+      .cached_tagged_with_any(cached_followed_tag_names)
+      .unscope(:select)
       .union(Article.where(user_id: cached_following_users_ids))
```
Comment (djuber) [inline app/models/user.rb:269]: just pointing out (not a bug, but clarifying behavior as I read through this) - if a followed user adds an antifollowed tag to an article - it's shown in the digest, because of the union on followed users' articles.

Comment (citizen428) [reply app/models/user.rb:269]: Yes, so this is a hard one. I figured the direct user follow overrides any tag preferences but I guess one could argue this point. That said, given how hard it is to figure out how to even antifollow a tag, I'm not sure how many of those we actually have. I tried to run some Blazer queries but they all timed out.

File: app/models/user.rb (hunk 5 above)
Comment (djuber) [reply app/models/user.rb:261]: with no followed users (just tag follows and anti-follows) I get locally a query that looks like this

```sql
SELECT "articles".*
FROM (
  (
  -- following tags and antifollowing tags
    SELECT "articles".*
      FROM "articles"
      WHERE
        NOT ((cached_tag_list ~ '[[:<:]]computerscience[[:>:]]'))
        AND (cached_tag_list ~ '[[:<:]]go[[:>:]]' OR cached_tag_list ~ '[[:<:]]python[[:>:]]')
  )
  UNION (
    -- no following user ids, empty union query:
    SELECT "articles".* FROM "articles" WHERE 1=0
    )
) "articles";
```

Running explain on this in blazer gives the following (local explain would be biased by factors like table size and statistics and could be misleading):

```
Unique  (cost=173963.32..175036.53 rows=29403 width=1133)
  ->  Sort  (cost=173963.32..173978.02 rows=29403 width=1133)
        Sort Key: articles.id, articles.user_id, articles.title, articles.body_html, articles.slug, articles.created_at, articles.updated_at, articles.main_image, articles.description, articles.published, articles.published_at, articles.featured, articles.processed_html, articles.featured_number, articles.social_image, articles.body_markdown, articles.organization_id, articles.canonical_url, articles.collection_id, articles.show_comments, articles.main_image_background_hex_color, articles.receive_notifications, articles.approved, articles.published_from_feed, articles.comments_count, articles.reactions_count, articles.video, articles.video_code, articles.video_source_url, articles.video_thumbnail_url, articles.video_closed_caption_track_url, articles.hotness_score, articles.feed_source_url, articles.positive_reactions_count, articles.edited_at, articles.crossposted_at, articles.spaminess_rating, articles.cached_tag_list, articles.path, articles.cached_user_name, articles.cached_user_username, articles.last_comment_at, articles.email_digest_eligible, articles.boost_states, articles.video_state, articles.page_views_count, articles.previous_positive_reactions_count, articles.score, articles.reading_time, articles.comment_template, articles.video_duration_in_seconds, articles.experience_level_rating, articles.experience_level_rating_distribution, articles.last_experience_level_rating_at, articles.rating_votes_count, articles.originally_published_at, articles.organic_page_views_count, articles.organic_page_views_past_month_count, articles.organic_page_views_past_week_count, articles.cached_user, articles.cached_organization, articles.archived, articles.any_comments_hidden, articles.nth_published_by_author, articles.comment_score, articles.search_optimized_title_preamble, articles.search_optimized_description_replacement, articles.public_reactions_count, articles.previous_public_reactions_count, articles.user_subscriptions_count, articles.co_author_ids, articles.reading_list_document
        ->  Append  (cost=0.00..173526.87 rows=29403 width=1133)
              ->  Seq Scan on articles  (cost=0.00..173394.56 rows=29402 width=2290)
                    Filter: (((cached_tag_list)::text !~ '[[:<:]]computerscience[[:>:]]'::text) AND (((cached_tag_list)::text ~ '[[:<:]]go[[:>:]]'::text) OR ((cached_tag_list)::text ~ '[[:<:]]python[[:>:]]'::text)))
              ->  Result  (cost=0.00..0.00 rows=0 width=0)
                    One-Time Filter: false
```

I think the union between followed tags and followed users is imposing the sort/sort-key/append actions in the query plan?

Limiting the columns to just id and title, and limiting the result set to 10 (on the outer query, not the inner query) and re-running, I'm seeing about 3-4s in blazer to run the query, it's probably not something we want to do often or in a loop over users, and definitely not something we'd want in the frontend.

Removing the "any articles for followed users" empty union select I get a much more reasonable result

```sql
explain SELECT "articles".*
FROM (
  (
  -- following tags and antifollowing tags
    SELECT "articles".*
      FROM "articles"
      WHERE
        NOT ((cached_tag_list ~ '[[:<:]]computerscience[[:>:]]'))
        AND (cached_tag_list ~ '[[:<:]]go[[:>:]]' OR cached_tag_list ~ '[[:<:]]python[[:>:]]')
  )
-- UNION for followed users was here
) "articles" limit 10;
```

```
Limit  (cost=0.00..58.97 rows=10 width=2290)
  ->  Seq Scan on articles  (cost=0.00..173394.56 rows=29402 width=2290)
        Filter: (((cached_tag_list)::text !~ '[[:<:]]computerscience[[:>:]]'::text) AND (((cached_tag_list)::text ~ '[[:<:]]go[[:>:]]'::text) OR ((cached_tag_list)::text ~ '[[:<:]]python[[:>:]]'::text)))
```

Without the users union this query runs in 288ms in blazer (using the simpler query plan):

```sql
SELECT "articles".id, "articles".title FROM ( (SELECT "articles".* FROM "articles" WHERE NOT ((cached_tag_list ~ '[[:<:]]computerscience[[:>:]]')) AND (cached_tag_list ~ '[[:<:]]go[[:>:]]' OR cached_tag_list ~ '[[:<:]]python[[:>:]]'))  ) "articles" limit 10;
```

**Review by djuber — APPROVED** [review]

File: app/javascript/leftSidebar/TagsFollowed.jsx (hunk 1 above)
Comment (nickytonline) [reply app/javascript/leftSidebar/TagsFollowed.jsx:26]: Food for thought. Should we even show an anti-follow tag in the sidebar?

Comment (citizen428) [reply app/javascript/leftSidebar/TagsFollowed.jsx:26]: I wondered about that too. The thing is, once you click on configuring the tags there, the antifollowed tags will show up in the list because, well, that's where you configure the antifollow in the first place. But at one point we also talked about completely removing this tags list from the sidebar, at least when Lisa was still here. I can go either way really but I think you may be right here, maybe removing antifollowed tags from this list is indeed the way to go (and it also means I don't need to mess around with CSS which is probably better for everyone involved).

File: app/models/user.rb (hunk 5 above)
Comment (citizen428) [reply app/models/user.rb:261]: Thanks for all the details @djiber, much appreciated. Also, great idea re the warning, I'll definitely add that.

File: app/javascript/leftSidebar/TagsFollowed.jsx (hunk 1 above)
Comment (citizen428) [reply app/javascript/leftSidebar/TagsFollowed.jsx]: I updated the code to no longer display anti-followed tags in the left sidebar and also to use a ternary.

**Review by rhymes — APPROVED** [review]
Let's give this a try!

**Review by Ridhwana — APPROVED** [review]

File: app/models/article.rb [hunk 9]
```diff
@@ -227,6 +227,16 @@ class Article < ApplicationRecord
     end
   }
 
+  # NOTE: @citizen428
+  # I'd usually avoid using Arel directly like this. However, none of the more
```
[the remark this answers is not in the document]
Comment (citizen428) [reply app/models/article.rb:231]: Right? It's actually quite a nice API.
