### PR TITLE
Removing the stackbit integration

### LINKED ISSUE #15700: Stackbit blog extension doesn't work on non-DEV Forems
**Describe the bug**

At the end of the User Extension Settings page (`/settings/extensions`), there's an option for users to set up their own Stackbit blog with one click:

Stackbit blog extension on a non-DEV Forem

Clicking on this on DEV returns [`https://dev.to/connecting-with-stackbit`](https://dev.to/connecting-with-stackbit) but since this page doesn't exist on any other Forem, it simply returns a 404 error page.

**To Reproduce**

1. go to any Forem except DEV
2. navigate to `settings/extensions` and scroll down to **Generate a personal blog from your Forem posts** 
3. click `Get Started` to see the error

**Expected behavior**

Either this opens a pre-loaded page like [`https://dev.to/connecting-with-stackbit`](https://dev.to/connecting-with-stackbit) with full functionality, or the section doesn't appear in the User Extension Settings at all.

### PR DESCRIPTION
**Pull request by jeremyf**
## What type of PR is this? (check all applicable)

- [X] Bug Fix
- [X] Feature Removal

## Description

The feature didn't quite work and Stackbit no longer supports this
integration.

Yes there are a few places where the webhooks has a string of "stackbit"
but I'm hesitant to remove that, as they are the part of the Webhooks
tests.

## Related Tickets & Documents

Closes #15700

## QA Instructions, Screenshots, Recordings

I have no guidance, as much of this is a removed view partial.

### UI accessibility concerns?

None.

## Added/updated tests?

- [x] Yes

## [Forem core team only] How will this change be communicated?

- [x] I will share this change internally with the appropriate teams

### CODE REVIEW

File: app/decorators/user_decorator.rb [hunk 1]
```diff
@@ -97,10 +97,6 @@ def fully_banished?
     articles_count.zero? && comments_count.zero? && suspended?
   end
 
-  def stackbit_integration?
-    access_tokens.any?
```
Comment (djuber) [inline app/decorators/user_decorator.rb:101]: is this integration the only use of User's `has_many :access_tokens` doorkeeper integration (dev as an auth provider)

https://github.com/forem/forem/pull/3504 was where we added this (Mac or Ben may have more context on what this is used for)

If we're not otherwise using doorkeeper and there's no plan to use it, it might make sense to examine dropping that library as well.

**Review by djuber — APPROVED** [review]
This looks like it removes references to stackbit from the site.

I left a note about possibly *also* removing doorkeeper if stackbit was the only auth consumer - but looking a little further, it seems that might be tied to webhooks (do we use those elsewhere?)

File: app/decorators/user_decorator.rb (hunk 1 above)
Comment (jeremyf) [reply app/decorators/user_decorator.rb:101]: I did a bit of digging…and I think it is, but I'm _not_ touching that relationship at this time

**Review by msarit — APPROVED** [review]

File: lib/data_update_scripts/20211206222716_remove_stackbit_page.rb [hunk 2]
```diff
@@ -0,0 +1,7 @@
+module DataUpdateScripts
+  class RemoveStackbitPage
+    def run
+      Page.find_by(slug: "connecting-with-stackbit")&.destroy
```
Comment (citizen428) [inline lib/data_update_scripts/20211206222716_remove_stackbit_page.rb:4]: Rails 6 added `destroy_by`:

```suggestion
      Page.destroy_by(slug: "connecting-with-stackbit")
```

**Review by citizen428 — CHANGES_REQUESTED** [review]
Blocking review because I would like some clarifications from a product standpoint first.

> The feature didn't quite work and Stackbit no longer supports this integration.

I just now created a Stackbit site from my DEV account and their site creation flow still reference DEV as a headless CMS:

Screen Shot 2564-12-07 at 10 40 32

Now I did have trouble _viewing_ the site but the Stackbit app and Github repository were created as expected, so are we really sure we want to remove this without talking to Stackbit first and breaking something in one of their flows?

AFAIK we also have users actively using this, so I'm not sure we should remove this without a deprecation post and timeline.

cc @benhalpern who maybe has some historical context and may also be better aware of any agreements/deals we have with Stackbit.

**Comment by jeremyf** [comment]
> Blocking review because I would like some clarifications from a product standpoint first.

I looped you into the Slack message thread and agree that this is now blocked.

**Comment by benhalpern** [comment]
@citizen428 The problem is that this is already at least partially deprecated. We had a communication line with them where I believe there may have been confusion, but we can follow up with their side if things are still displaying in some way over there.

The functionality is effectively no longer in full use. I have a draft post about this, including linking to resources where folks could re-implement this for all intents and purposes via API if they wish. In general we should definitely give warning, but the functionality is already no longer fully supported.

**Comment by joshpuetz** [comment]
Question: are there stored access tokens that we can delete from our database?

**Comment by JennieOcken** [comment]
Echoing what Ben said here from a Product perspective.  Stackbit is depreciating this connection from their side.  We thought we would have more time to turn it off, but it looks like they have started that depreciation process.  We should remove this functionality so we don't create broken functionality.

**Comment by jeremyf** [comment]
> Question: are there stored access tokens that we can delete from our database?

Blazer blocks me from seeing any of that information.  My assumption is "Yes there are tokens."  But that's opaque to me.  Given the deprecation, we could certain clean up those keys.

**Comment by benhalpern** [comment]
Just to speak to the broader use of doorkeeper, just want to get everyone on the same page that I think this would allow us to ✂️✂️✂️ doorkeeper altogether _if_ that is what we wanted to do (I don't think we use it for any other reason — correct me if I'm wrong), but it is definitely correct not to rush that choice and treat that as outside the scope of the PR.

@JennieOcken @citizen428 an argument could be made to keep it around _if_ it might play a role in future platform/plugin stuff, but seems like cleaning it out and ridding ourselves of this extra code liability is more appropriate, eh?

**Review by citizen428 — APPROVED** [review]

**Comment by citizen428** [comment]
@benhalpern I'm definitely for removing Doorkeeper for now and not keeping it around purely for the sake of "what if" scenarios. Though I think it should probably be done in a follow-up PR so we have more time to evaluate if it's really necessary.

> Blazer blocks me from seeing any of that information. My assumption is "Yes there are tokens." But that's opaque to me. Given the deprecation, we could certain clean up those keys.

@jeremyf We can loop in @Zhao-Andy, I guess he could delete this with a one-off statement from a Rails console. I'll take care of talking to him.

**Comment by JennieOcken** [comment]
Re: Doorkeeper

I am 💯 with @citizen428 here.  When we get to the plugin marketplace, we should evaluate the best tools for that job.  We may bring it back at that point, but our implementation may very well be different or we may have different needs.  I would love to see someone open and complete that separate PR for that cleanup.
