### PR TITLE
15 minute fix: Shorten long titles from feed items if needed

### LINKED ISSUE #13959: RSS sync silently ignores feed entries with long titles (I think)
**Describe the bug**

I have noticed that some of my posts to our (OpenNMS's) blog don't show up in my dashboard as draft posts.  Up until now I've just ignored it and let an entry go missing here or there.  Today I tried adding the entry manually, and found that it wouldn't let me save because my title was too long.

I suspect these entries are getting missed because the title is too long so it can't get auto-saved into my dashboard.

**To Reproduce**

1. Create an RSS feed with an entry with a very long title.
2. refresh RSS

**Expected behavior**

All RSS feed entries get draft posts.

**Desktop (please complete the following information):**

- OS, version: Mac OS X Catalina
- Browser, version: Firefox 89

**Additional context**

Our RSS feed is https://www.opennms.com/feed/

The June 7th entry _("OpenNMS On the Horizon - Documentation, Flows and Nephron, Docker Container Trust, Thresholding, Metadata, Time-Series API, Minion Health Checks")_ did not auto-import.

### PR DESCRIPTION
**Pull request by djuber**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

When an rss feed includes items with long titles, the created Articles fail validation (silently) and no draft post is created in the dashboard. 

Following the pattern we follow for long article descriptions, if the title is too long, just truncate and add ellipsis. 

The author can fix this up if desired in the editor when setting `published: true`    

This didn't go through any RFC or product decision making process, it's the smallest fix I can think of to stop dropping imported content because of long titles. 

## Related Tickets & Documents

Fixes #13959

## QA Instructions, Screenshots, Recordings

I set the test user's feed_url to the reporter's rss feed - https://www.opennms.com/feed/
I then called `Feeds::Import.call(users: User.where(id: the_user_id))`, which is what the feed worker does internally on a refresh.

On main only 7 articles were created (with short enough titles). In this branch the remaining three were successfully imported and the titles were shortened as described:

```ruby
 [16] pry(main)> Article.last.attributes.slice("description", "title")
  Article Load (1.3ms)  SELECT "articles".* FROM "articles" ORDER BY "articles"."id" DESC LIMIT $1  [["LIMIT", 1]]                                                                                        
=> {"description"=>
  "Since last time, we did a bunch more documentation updates, plus worked on a number of bug fixes and...",
 "title"=>
  "OpenNMS On the Horizon – Documentation, Flows and Nephron, Docker Container Trust, Thresholding, Metadata, Time-Series API, M..."}
```

### UI accessibility concerns?

I don't think so.

## Added tests?

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [x] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] Are there any post deployment tasks we need to perform?

None. If imports had been skipping recent articles because of title length, they should be added during the next refresh.
 
## [optional] What gif best describes this PR or how it makes you feel?

wordpress post with title too long to be visible in the editor

### CODE REVIEW

File: spec/services/feeds/assemble_article_markdown_spec.rb [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+
+RSpec.describe Feeds::AssembleArticleMarkdown, type: :service do
+  let(:user) { create(:user, feed_mark_canonical: true) }
+  let(:feed_source_url) { "https://feed.source/url" }
+  let(:feed) { Struct.new(:url).new("https://feed.source/") }
+  let(:title) { "A title" }
+  let(:content) { "Some content that came in with the item, should be the body" }
+
+  let(:item) do
+    Struct
```
Comment (djuber) [inline spec/services/feeds/assemble_article_markdown_spec.rb:11]: pretty sure this should be a double instead of a struct.

File: app/services/feeds/assemble_article_markdown.rb [hunk 2]
```diff
@@ -31,6 +31,10 @@ def call
 
     private
 
+    def processed_title
```
Comment (djuber) [inline app/services/feeds/assemble_article_markdown.rb:34]: borrowed the term and the behavior from [`Article#processed_description`](https://github.com/forem/forem/blob/main/app/models/article.rb#L340-L346)

File: app/services/feeds/assemble_article_markdown.rb [hunk 3]
```diff
@@ -31,6 +31,10 @@ def call
...
+      @title.size <= 128 ? @title : "#{@title[0..124]}..."
```
Comment (citizen428) [inline app/services/feeds/assemble_article_markdown.rb:35]: Rails has this built-in:

```ruby
test = "x" * 20
test.truncate(10, omission: "...")
#=> "xxxxxxx..."
```

```suggestion
      @title.truncate(128, omission: "...")
```

File: spec/services/feeds/assemble_article_markdown_spec.rb (hunk 1 above)
Comment (citizen428) [reply spec/services/feeds/assemble_article_markdown_spec.rb:11]: Let's make it a verifying double then 😃 This requires some minor code changes but I honestly think they are for the better as the current code mixes method access and `:[]` access for `Feedjira::Parser::RSSEntry`:

```diff
diff --git a/app/services/feeds/assemble_article_markdown.rb b/app/services/feeds/assemble_article_markdown.rb
index 75325751b..5fc6abde1 100644
--- a/app/services/feeds/assemble_article_markdown.rb
+++ b/app/services/feeds/assemble_article_markdown.rb
@@ -6,8 +6,8 @@ def self.call(item, user, feed, feed_source_url)

     def initialize(item, user, feed, feed_source_url)
       @item = item
-      @title = item[:title].strip
-      @categories = item[:categories] || []
+      @title = item.title.strip
+      @categories = item.categories || []
       @user = user
       @feed = feed
       @feed_source_url = feed_source_url
@@ -58,7 +58,7 @@ def assemble_body_markdown
     end

     def get_content
-      @item[:content] || @item[:summary] || @item[:description]
+      @item.content || @item.summary || @item.description
     end

     def thorough_parsing(content, feed_url)
diff --git a/spec/services/feeds/assemble_article_markdown_spec.rb b/spec/services/feeds/assemble_article_markdown_spec.rb
index 4365b4e81..af44fcacf 100644
--- a/spec/services/feeds/assemble_article_markdown_spec.rb
+++ b/spec/services/feeds/assemble_article_markdown_spec.rb
@@ -3,19 +3,18 @@
 RSpec.describe Feeds::AssembleArticleMarkdown, type: :service do
   let(:user) { create(:user, feed_mark_canonical: true) }
   let(:feed_source_url) { "https://feed.source/url" }
-  let(:feed) { Struct.new(:url).new("https://feed.source/") }
+  let(:feed) { instance_double("Feedjira::Parser::RSS", url: "https://feed.source/") }
   let(:title) { "A title" }
   let(:content) { "Some content that came in with the item, should be the body" }

   let(:item) do
-    Struct
-      .new(:title, :categories, :published, :content)
-      .new(
-        title,
-        %w[tag1 tag2 tag3 tag4 tag5],
-        "2020-12-20",
-        content,
-      )
+    instance_double(
+      "Feedjira::Parser::RSSEntry",
+      title: title,
+      categories: %w[tag1 tag2 tag3 tag4 tag5],
+      published: "2020-12-20",
+      content: content,
+    )
   end

   let(:feeds_assemble_article_markdown) { described_class.new(item, user, feed, feed_source_url) }
```

The specs are green for me with all these changes applied.

Comment (djuber) [reply spec/services/feeds/assemble_article_markdown_spec.rb:11]: Thanks for digging this out!

File: app/services/feeds/assemble_article_markdown.rb (hunk 3 above)
Comment (djuber) [reply app/services/feeds/assemble_article_markdown.rb:35]: Well, having named it, this is obviously the right thing. :smile:
I'll do the same for `Article#processed_description` in a second PR.

The only thing we may be doing "specially" in processed description is aligning the ellipsis to non-whitespace (so you don't get "text text text ..." and instead get "text text text..." even if it causes the truncated string to be shorter than it would be). It looks like `separator: " "` is what I also want for that behavior.

**Review by citizen428 — APPROVED** [review]

**Review by rhymes — APPROVED** [review]
This is awesome!
