### PR TITLE
Remove sustaining member newsletter, and its settings

### LINKED ISSUE #17498: Remove legacy Sustaining Membership code
**Describe the bug**

There is no longer a direct user supporting membership for DEV (and probably will not be for other forems going forward). We have some legacy code from several years ago that only supported this feature.

This functionality is fully distinct from organization [sponsorships](https://github.com/forem/forem/pull/3438).

Suggested removals

- There is a  `monthly_dues` column on user which is unneeded (pulling this into a separate issue)
- User has an `a_sustaining_member?` predicate which could also be removed (sustaining members were those with positive monthly dues).
- There is a newsletter configurable via Settings::General.mailchimp_sustaining_members_id which can be deprecated/removed since we won't be subscribing anyone to this. 
- There is an admin customization form to set this newsletter up.
- Mailchimp::Bot knows about sustaining member email subscriptions, and won't need to know it.
- There's a translation key for email_membership_newsletter in the helpers locale files that could be removed as unused. 

There's a few other places where `sustaining_member` is used in this context which probably can be removed together or individually. 

**Additional context**

Most of this just serves to document the feature is dead and the code is ready to be cleaned up

Initial feature described in [Ben's announcement from 2018](https://dev.to/ben/announcing-sustaining-memberships-for-devto-4ad9) - the link https://dev.to/membership gives a 404 (that route was removed)

#801 closed an issue related to billing enhancements based on this feature having been disabled/removed in 2018
#1107 removed the membership link from the sidebar - which was [implemented as a page](https://github.com/forem/forem/blob/e492ce83048d8b3e32fac681523b52c373fbecfa/config/routes.rb#L210) in 2018
#2741 removed most of the pages/views for this 
#3575 and #6243 removed stripe billing support for this 
#5675 clarified the intent of the two newsletters (users were erroneously being prompted to subscribe to the sustaining member newsletter during onboarding)

### PR DESCRIPTION
**Pull request by djuber**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature (removal)
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This removes the concept of sustaining memberships from the system,
and logic related to or dependent on it.

This does not remove the monthly_dues column from the users table (todo).

## Related Tickets & Documents

- Closes #17498

## QA Instructions, Screenshots, Recordings

Please let nothing break. Specifically forms in the admin area around mailchimp newsletters were touched and should be spot checked.

### UI accessibility concerns?

None

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: removing old behavior, nothing to test

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [x] This change does not need to be communicated, and this is why not: almost nobody knew this was even here, they won't miss it.

## [optional] Are there any post deployment tasks we need to perform?

I think a mailchimp administrator could remove the newsletter if it exists?

### CODE REVIEW

File: lib/data_update_scripts/20220429142653_remove_mailchimp_sustaining_members_newsletter.rb [hunk 1]
```diff
@@ -0,0 +1,7 @@
+module DataUpdateScripts
+  class RemoveMailchimpSustainingMembersNewsletter
+    def run
+      Settings::General.where(var: "mailchimp_sustaining_members_id").delete_all
```
Comment (djuber) [inline lib/data_update_scripts/20220429142653_remove_mailchimp_sustaining_members_newsletter.rb:4]: I think this might need to be `#destroy_all` to trigger the after_commit hook on `Settings::Base` to `clear_cache`?

**Review by maestromac — APPROVED** [review]
LGTM!
