### PR TITLE
Bust Content Cache after updation of Settings

### LINKED ISSUE #14129: Ensure "Community Name" updates quickly in header after change
**Describe the bug**

If a Forem does not have a logo set, it will use some auto-generated text (originally `New Forem`).  This area is updated after the admin changes the "Community Name" via Config.

It updates quickly via `/admin`, but not as quickly in the public-facing Forem.

**To Reproduce**

1. Set up a brand new Forem
2. Set a new Community Name
3. Refresh the page via `/admin` and on the main homepage
4. Notice that the top left section is updated in Admin, but not in the main Forem

**Expected behavior**

After updating Community Name, it reflects immediately in the header.

**Screenshots**

Here is a video:
https://user-images.githubusercontent.com/9434801/124306709-64bbb800-db2c-11eb-9207-41915feba503.mp4

**Additional context**

Likely caching.  Similar in nature to #12473

### PR DESCRIPTION
**Pull request by keshavbiswa**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
- Cache was not getting busted after settings update for application layout resulting in the header not getting updated with correct community name.
## Related Tickets & Documents
Closes #14129
## QA Instructions, Screenshots, Recordings
Refer to #14129

## Added/updated tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [x] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://admin.forem.com/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

File: app/controllers/admin/settings/general_settings_controller.rb [hunk 1]
```diff
@@ -1,6 +1,8 @@
 module Admin
   module Settings
     class GeneralSettingsController < Admin::Settings::BaseController
+      after_action :bust_content_change_caches, only: %i[create]
```
Comment (citizen428) [inline app/controllers/admin/settings/general_settings_controller.rb:4]: Given that this controller only has one action I'm very tempted to inline this right after the `Audit::Logger` call to make it a bit more obvious. But I'm happy to leave it here if others prefer that.

**Review by citizen428 — APPROVED** [review]

**Review by rhymes — APPROVED** [review]
