### PR TITLE
Optimise dropdowns for accessibility - Post comments and share

### LINKED ISSUE #13744: Bug: Comments dropdown open when arriving on page
**Describe the bug**
The comments dropdown seems to automatically open when I press back after looking at a users profile. It's always the first comment and seemingly only when I'm coming back from looking at a profile.

image

**To Reproduce**
1. go to a post with comments
2. click on any user's profile picture
3. go back using browser navigation
4. see the menu is open.

**Expected behaviour**
Then menu should only open when I actively open it.

**Screenshots**
forem__back-bug

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Chrome 90.0.4430.212

**Smartphone (please complete the following information):**
N/A

**Additional context**
A very minor thing in the grand scale of things but I noticed it so I'm sure others have too.

### PR DESCRIPTION
**Pull request by aitchiss**
## What type of PR is this? (check all applicable)

- [X] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This PR is the first of several to address #12297 (Optimise all usage of crayons dropdown for accessibility), and lays the groundwork for the future PRs by introducing a helper to initialize a given dropdown with the relevant click/key events and focus handlers.

In addition to adding the helper, this PR focuses on:

- Dropdowns in comment areas (including posts, podcasts and the comment index page)
- The article share options dropdown

Initialization of these dropdowns has been moved to relevant JS packs, utilising the new helper.

## Related Tickets & Documents

#12297
Fixes #13744

## QA Instructions, Screenshots, Recordings

I've tested this locally on desktop, and android mobile. However some of the code moved from initializers to packs affects the Android native app, which will need tested too.

### Expected dropdown functionality

In all cases, the dropdowns mentioned below should function as follows:

- Opens and closes with a mouse click on the relevant button
- Button can be focused by keyboard, and pressing `Enter` opens and closes the dropdown
- `Escape` closes the dropdown when it's open
- Clicking anywhere outside of the dropdown closes it if it is open
- If activated by keyboard, visible focus is transferred to the first interactive item (e.g. link) in the dropdown when it opens
- If a user closes the dropdown by pressing `Escape`, focus is returned back to the button that opened it
- If a user closes the dropdown by clicking outside, focus is returned back to the button that opened it _unless_ they clicked on some other interactive item (e.g. they clicked a button that exists elsewhere on the page)
- When the dropdown is open, if you use the `Tab` key or `Shift + Tab` (moves backwards) and tab past the first or last interactive item in the dropdown, the dropdown should close
- The button which activates the dropdown should have the attributes: `aria-expanded`, `aria-haspopup="true"`, `aria-controls="the_id_of_the_dropdown_content"`
- `aria-expanded` should be "true" when the dropdown is visible, and "false" otherwise

### Article share dropdown

- Go to any article and click the `...` button (next to the reactions)
- Check that dropdown interaction conforms with the requirements above ☝️
- Check that the "Copy to clipboard" functionality continues to work as before
- Check that if you click the copy to clipboard function and the "Copied to clipboard" notice appears, if you close and re-open the dropdown, it is no longer visible
- Check that the links in the dropdown work as before, and that when you select a link, the dropdown also closes

### Comment dropdowns

These need checked in the article page, the podcast page, and the comment index page

- In a post with multiple comments, check that each dropdown interaction conforms with the requirements above ☝️
- Check that when you "Copy link" the text is copied to your clipboard and the dropdown closes
- Check that you can follow each of the links
- Check both comments made by the current user, and a different user (since different options appear)
- Add a new comment, and make sure that the dropdown works as expected when the new comment appears in the list

### UI accessibility concerns?

The dropdown interaction referenced above represents an accessibility improvement, allowing keyboard users to reach dropdown content easily, and giving context to screen reader users via aria attributes.

## Added tests?

- [X] Yes - Added Cypress tests for comments and the post actions menu
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://forem.gitbook.io/forem-admin-guide/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [X] This change does not need to be communicated, and this is why not: I think we should communicate the change once all of #12297 is complete

## [optional] What gif best describes this PR or how it makes you feel?

it's a system

### CODE REVIEW

**Review by rhymes — COMMENTED** [review]
Thanks @aitchiss! Works great on Chrome, there are some quirks on Firefox, see my notes:

**Expected dropdown functionality**

Everything works, only a tiny detail:

> Button can be focused by keyboard, and pressing Enter opens and closes the dropdown

I can only open it, if I click Enter, I have to click Esc again. Is this correct? To me it feels correct: I click Enter, then I'm in the dropdown, I click Esc, I'm back on the button, I click Enter again and I'm back in the dropdown

**Article share dropdown**

Everything works, except the following:

> Check that the "Copy to clipboard" functionality continues to work as before

This doesn't work in Firefox, but it works in Chromium

I have a question: why can't I reach the button with the tab - shift tab? Also: the button doesn't have the hand cursor, so it's not self evident to me that I'm supposed to click on it (this is already an issue on Forem, nothing introduced by your PR)

**Comment dropdowns**

> Check that when you "Copy link" the text is copied to your clipboard and the dropdown closes

This isn't working in Firefox, but it works in Chromium

**Comment by rhymes** [comment]
For some odd reason I noticed I can't copy data from the clipboard on Firefox on other branches as well. I can copy fine from, for example, GitHub's "copy link" in any comment here in this thread.

This is what I see after uploading an image:

Screenshot 2021-05-28 at 10 03 18 AM (2)

(this is the `main` branch and I'm using Firefox 89)

**Comment by aitchiss** [comment]
> For some odd reason I noticed I can't copy data from the clipboard on Firefox on other branches as well. I can copy fine from, for example, GitHub's "copy link" in any comment here in this thread.
> 
> This is what I see after uploading an image:
> 
> Screenshot 2021-05-28 at 10 03 18 AM (2)
> 
> (this is the `main` branch and I'm using Firefox 89)

So this works for me in Firefox! But I notice that you have an icon next to the browser URL that suggests Firefox thinks you're not in a secure context, and `navigator.clipboard` is null when not in a secure context. I'm not sure why my firefox thinks localhost is secure and yours doesn't 🤔

**Comment by aitchiss** [comment]
Thanks for reviewing this @rhymes !

> I can only open it, if I click Enter, I have to click Esc again. Is this correct? To me it feels correct: I click Enter, then I'm in the dropdown, I click Esc, I'm back on the button, I click Enter again and I'm back in the dropdown

This is correct, I have worded the requirement poorly! The transfer of focus is correct, but if you were to e.g. `Shift + Tab` back to the button after opening the dropdown, you should be able to press `Enter` to close it

>This doesn't work in Firefox, but it works in Chromium

> I have a question: why can't I reach the button with the tab - shift tab? Also: the button doesn't have the hand cursor, so it's not self evident to me that I'm supposed to click on it (this is already an issue on Forem, nothing introduced by your PR)

The clipboard functionality seems to be to do with your firefox settings (as above) - I'll see if I can dig to find out why that's happening. You can't tab to the clipboard button because it's not a button 🙄 😢 It's awful, but there's a separate issue being worked on by a community member at the moment to fix it, so I've left it as out of scope here for now

**Comment by rhymes** [comment]
> The clipboard functionality seems to be to do with your firefox settings (as above) - I'll see if I can dig to find out why that's happening. You can't tab to the clipboard button because it's not a button 🙄 😢 It's awful, but there's a separate issue being worked on by a community member at the moment to fix it, so I've left it as out of scope here for now

Thank you! Now I remember, `navigator.clipboard` is correcly forbidden for insecure scenarios. It might be something with my own setting as it's definitely a new behavior. I vaguely remember it used to work. I wonder if anything has changed in the Permissions API relative to `clipboard.writeText()` https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText

File: app/javascript/packs/articlePage.jsx [hunk 1]
```diff
@@ -20,48 +23,99 @@ if (snackZone) {
...
+
+// Initialize the share options
+const shareDropdownButton = document.getElementById('article-show-more-button');
+
+if (shareDropdownButton.dataset.initialized !== 'true') {
+  if (Runtime.isNativeAndroid('shareText')) {
+    // Android native apps have enhanced sharing capabilities for Articles and don't use our standard dropdown
+    shareDropdownButton.addEventListener('click', () =>
+      AndroidBridge.shareText(location.href),
+    );
```
Comment (aitchiss) [inline app/javascript/packs/articlePage.jsx:38]: @fdoxyz - just a heads up that this code has moved from initializers to packs. The code itself hasn't changed though, so I don't believe there's a great regression risk. Do you think we need to specifically test this PR in terms of the android mobile app where this behavior is triggered?

Comment (fdoxyz) [reply app/javascript/packs/articlePage.jsx:38]: Thank you for the heads up @aitchiss! I tested this locally with the Android DEV app and things are working as expected.

> Do you think we need to specifically test this PR in terms of the android mobile app where this behavior is triggered?

I think it would be a great addition to avoid regressions! Would it be difficult to add a test case where we stub `Runtime.isNativeAndroid('shareText')` to return `true` and then check that `navigator.share` is called when a click to the `shareDropdownButton` is clicked/tapped?

I'm asking because it's non-trivial for me to work my way round stubbing these in Cypress tests (especially the `navigator`) 😅  If you do manage to add this test case I'd appreciate if you ping me on it, just to take a look and make sure I learn how these stubs can be done in Cypress for future spec I'll nee to write 🙏 

The DEV Android app isn't a major focus right now, but future Android native efforts will rely on this feature as well, at least until `navigator.share` is supported within the Android WebView

Comment (aitchiss) [reply app/javascript/packs/articlePage.jsx:38]: I was full of hope about stubbing the various things in Cypress, but it looks like it's not so straightforward 🙃 

I think probably it could be possible with more investigation, but maybe that would need to be separate to this PR as it might take a while! I'm thinking that eventually what would be great is if the android app had its own test for this.

**Review by fdoxyz — APPROVED** [review]
I don't have opinions on specifics, but from conversations I've had before with Nick (about moving these initializers to `app/assets/javascripts/initializePage.js`) this seems like a great approach.

I gave this a thorough test throughout different devices (browsers on macOS, iOS, Android + iOS mobile app) and it works as expected. Also, followed the QA steps and everything checked out okay for me 👍 

Given this _"is the first of several to address #12297"_ it LGTM so we can unblock this 🙂

File: app/javascript/packs/articlePage.jsx (hunk 1 above)
Comment (aitchiss) [reply app/javascript/packs/articlePage.jsx:38]: > A small/medium problem of this approach would be that the Android app checks wouldn't be run in forem/forem PRs which could potentially break this behavior.

Yeah that's very true. Agree that it's definitely worth some research - let me know if I can help at all!
