### PR TITLE
Fix details liquid tag oversanitizing markdown

### LINKED ISSUE #18923: Markdown table is not parsed inside details liquid tag
**Describe the bug**

Markdown tables seem not being parsed inside the `details` liquid tag for some reason. It is _not_ that Markdown is totally unavailable inside the tag, but only tables as far as I am currently aware.

**To Reproduce**

1. Open https://dev.to/new
2. Paste the following text into the body
   ```
   ![placeholder](https://via.placeholder.com/150)

   A|B|C
   --|--|--
   1|2|**3**

   {% details sample %}

   ![placeholder](https://via.placeholder.com/150)

   A|B|C
   --|--|--
   1|2|**3**

   {% enddetails %}
   ```
3. Preview, save, or publish to see it renders as the screenshot below

**Expected behavior**

Markdown tables should be rendered as HTML tables either inside or outside the `details` tag.

**Screenshots**

- dev.to post edit UI:
  image

- dev.to post preview (`<details>` opened):
  image

**Desktop (please complete the following information):**

- OS, version: Win 11
- Browser, version: FF 108.0.1

**Smartphone (please complete the following information):**

- Device: iPhone SE
- OS, version: iOS 15.7
- Browser, version: Forem iOS app

### PR DESCRIPTION
**Pull request by yheuhtozr**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Fix #18923 where Markdown tables not working inside a `{% details %}` liquid tag. This seems due to the entire content of details tag once rendered into HTML, then going through sanitizer that doesn't match Forem's whitelist.

Theoretically it should allow all HTML tags produced by Markdown you are allowed to write, though I'm not totally sure if my altered code satisfies it. Any suggestions are welcome.

## Related Tickets & Documents

- Related Issue #
- Closes #18923

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [X] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://developers.forem.com) or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

File: app/liquid_tags/details_tag.rb [hunk 1]
```diff
@@ -10,7 +10,12 @@ def initialize(_tag_name, summary, _parse_context)
 
   def render(_context)
     content = Nokogiri::HTML.parse(super)
-    parsed_content = sanitize(content.xpath("//html/body").inner_html)
+    parsed_content = sanitize(
+      content.xpath("//html/body").inner_html,
+      tags: MarkdownProcessor::AllowedTags::RENDERED_MARKDOWN_SCRUBBER,
+      attributes: MarkdownProcessor::AllowedAttributes::RENDERED_MARKDOWN_SCRUBBER |
+        MarkdownProcessor::AllowedAttributes::DISPLAY_AD,
```
Comment (maestromac) [inline app/liquid_tags/details_tag.rb:17]:
```suggestion
      attributes: MarkdownProcessor::AllowedAttributes::RENDERED_MARKDOWN_SCRUBBER,
```

I believe DISPLAY_AD is only reserved for DisplayAds so it doesn't belong here.

**Review by maestromac — APPROVED** [review]
Thank you for this @yheuhtozr !
