### PR TITLE
Fix email confirmation logic when registering via Omniauth

### LINKED ISSUE #17865: Email confirmation
**Describe the bug**
We have an error when we confirm the email address on any Forem.

**To Reproduce**

1. Register to any Forem like [the latest named Tidelift](https://community.tidelift.com/) (with GitHub in my case)
2. Go to your inbox to confirm your address email
3. Click on the link to confirm
4. See the error on the page, "Email was already confirmed, please try signing in"

**Expected behavior**
Have a confirmation message without errors like this when this is the first time I created my account on this Forem.

**Screenshots**
image

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Chrome 102

### PR DESCRIPTION
**Pull request by fdocr**
## What type of PR is this? (check all applicable)

- [x] Bug Fix

## Description

This PR ensures email confirmation is required when authenticating via 3rd party auth service providers. The only reason email confirmation isn't required is when SMTP isn't configured (can't confirm the email in that case).

## Related Tickets & Documents

- Closes #17865

## QA Instructions, Screenshots, Recordings

1. Boot app locally
   - Make sure it's configured to work with an OAuth service provider (Twitter, Facebook, etc)
   - Also make sure emails can be sent from your local environment
2. Register a new account
3. Confirmation email should be delivered if SMTP is enabled

Tests for this situation were modified/included and can be tested locally with:

`bundle exec rspec spec/services/authentication/authenticator_spec.rb`

**Complete flow using GitHub**
https://user-images.githubusercontent.com/6045239/174094827-17b67df9-1806-4219-a112-407c616c9a41.mov

**Same flow as above but with duplicated (already existing) username:**
https://user-images.githubusercontent.com/6045239/174095411-170bdb8d-5646-46d6-aab6-4d475f96a5b7.mov

**Forem Authentication registration doesn't require email confirmation:**
https://user-images.githubusercontent.com/6045239/174116995-3f2a8212-7136-4c0a-b69c-fcbac77f5869.mov

### UI accessibility concerns?

None - backend change only

## Added/updated tests?

- [x] Yes

## [Forem core team only] How will this change be communicated?

- [x] This change does not need to be communicated, and this is why not: It's a bug fix for future (new) registrations

## [optional] What gif best describes this PR or how it makes you feel?

confirm?

### CODE REVIEW

**Review by Ridhwana — APPROVED** [review]
Looks good to me ✨

**Comment by fdocr** [comment]
Back to draft as we resolve a internal question that came up regarding to account confirmations to avoid accidental merge

File: app/controllers/confirmations_controller.rb [hunk 1]
```diff
@@ -6,8 +6,9 @@ def show
 
     if resource.errors.empty?
       set_flash_message!(:notice, :confirmed)
+      sign_in(resource)
+
       if resource.creator?
-        sign_in(resource)
```
Comment (fdocr) [inline app/controllers/confirmations_controller.rb:10]: Ensure users are signed in after email confirmation so registration flow goes smoothly not just for creator email confirmation. Users are redirected to onboarding (see video recording in PR description)

**Review by fdocr — COMMENTED** [review]
Based on product discussion ([here](https://forem-team.slack.com/archives/CAA200SH5/p1655213748977939?thread_ts=1654884321.242109&cid=CAA200SH5)) users will be required email confirmation after registration via 3rd party auth service providers

File: spec/services/authentication/authenticator_spec.rb [hunk 2]
```diff
@@ -717,19 +975,31 @@
         ).to be(true)
       end
 
-      it "does not update their twitter_username if the user is suspended" do
+      it "increments identity.errors if any errors occur in the transaction" do
```
Comment (juliannatetreault) [inline spec/services/authentication/authenticator_spec.rb:978]: Quick, non-blocking suggestion (same as above!): Let's aggregate the failures here since we have multiple expectations within this single block:
```suggestion
      it "increments identity.errors if any errors occur in the transaction", :aggregate_failures do
```

**Review by juliannatetreault — COMMENTED** [review]
I left a few non-blocking suggestions in regards to the tests, but otherwise, the tests for this PR are 🤩 !

**Review by joshpuetz — APPROVED** [review]
