### PR TITLE
Fix bug where OAuth signups were not pulling in OAuth provider's profile image

### LINKED ISSUE #14432: Given profile image is not used on email signup
**Describe the bug**

When I sign up for a Forem via email, it does not take the image I use. It gives me a random default instead.

**To Reproduce**

- Visit https://www.rectangle.community/
- Create account
- Notice it does not use the image you put in the form

I am not sure if this problem is exclusive to self-host or also a problem on Forem Cloud — the way images are handled in these contexts is different, but this _seems_ like more application logic issues.

It doesn't seem to be affecting social sign up.

**Expected behavior**

The image I upload is the one used in my account. I can later fix this, but it's a bad initial experience.

### PR DESCRIPTION
**Pull request by Zhao-Andy**
## What type of PR is this? (check all applicable)
- [x] Bug Fix

## Description
This fixes a bug where we weren't pulling in the OAuth provider's (Twitter/GitHub/Facebook/etc) profile image, and instead were always auto generating one. The problem is partly because we take a conservative approach of when a URL is not `https`, we default to auto-generating one.

This PR makes it so it always fills in `http` profile image URLs with `https`, and if the URL is still blank, we auto generate the profile image.

## Related Tickets & Documents
Resolves #14432 

## QA Instructions, Screenshots, Recordings
1. Log in via Twitter
2. See that your profile image persisted
3. Log in via GitHub
4. See that your profile image persisted
5. (optional) Log in via Facebook (this is kind of a pain -- Forem team members feel free to DM me for instructions and necessary auth tokens)
6. See that your profile image persisted

### UI accessibility concerns?
Nope

## Added tests?

- [x] No, and this is why: I tried writing tests for this but it seemed too verbose to try to mock it, since we don't persist profile image files in the test database.
- [x] I need help with writing tests

## [Forem core team only] How will this change be communicated?

- [x] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post

## [optional] Are there any post deployment tasks we need to perform?
No

## [optional] What gif best describes this PR or how it makes you feel?

Homer Simpsons pumps his fist victoriously, and says "All right, we're back in business."

### CODE REVIEW

**Comment by Zhao-Andy** [comment]
@djuber our resident QA, in case you were wondering I tried to write a test like so:
```ruby
      it "creates a new user with their original profile image" do
        visit sign_up_path
        click_on(sign_in_link, match: :first)
        
        expect(User.first.remote_profile_image_url).to eq OmniauthHelpers::OMNIAUTH_PAYLOAD_TWITTER.info.image
      end
```

However, `User.first.remote_profile_image_url` always returned `nil` since the test user doesn't actually have a profile image. I was thinking I could do something like:
```ruby
allow_any_instance_of(User).to receive(:remote_profile_image_url).and return("the_dummy_image_url_from_the_above_payload")
```
But that doesn't feel like I'm testing anything 🤔 what do you think?

**Review by joshpuetz — APPROVED** [review]
Tested locally and works! 👍🏻

**Comment by djuber** [comment]
> However, `User.first.remote_profile_image_url` always returned `nil` since the test user doesn't actually have a profile image

I see we have an existing test about the remote profile image here https://github.com/forem/forem/blob/main/spec/services/authentication/authenticator_spec.rb#L527 - which passes on main already

I tried (I suspect you may have too) adding this to the system test at  spec/system/authentication/user_logs_in_with_twitter_spec.rb  - the omniauth payload has a remote url "https://dummyimage.com/400x400_normal.jpg" - the twitter provider removes the _normal suffix and calls the safe remote profile image url class you're changing - the created user (on main) did not have this remote url present.

I'll double check on this branch to see if that's any different.

File: app/services/users/safe_remote_profile_image_url.rb [hunk 1]
```diff
@@ -2,9 +2,9 @@ module Users
   module SafeRemoteProfileImageUrl
     # Basic check for nil and blank URLs, alongside likely incomplete URLs, such as just "image.jpg".
     def self.call(url)
-      return url if url.to_s.start_with?("https")
+      url.gsub!("http://", "https://") if url.match?(%r{https?://})
 
-      Users::ProfileImageGenerator.call
+      url.presence || Users::ProfileImageGenerator.call
```
Comment (djuber) [inline app/services/users/safe_remote_profile_image_url.rb:7]: the old logic here was
"urls that start with https:// are okay, otherwise call ProfileImageGenerator"

The new logic is 

"urls that start with http:// should start with https://, and any truthy url should be returned if provided, otherwise call the profile image generator" 

Is that correct?

Comment (Zhao-Andy) [reply app/services/users/safe_remote_profile_image_url.rb]: Those are good points. I've updated the logic to be more similar to the previous version, since I didn't think through all the edge cases the first time around.

**Review by citizen428 — APPROVED** [review]
