### PR TITLE
Remove reactions to a user when deleting the user

### LINKED ISSUE #15245: When a user is deleted - reactions to the user are not removed
**Describe the bug**

When a moderator created user flagging reactions on a user
And then the user is deleted 
The reaction to the user remains (it's still included in the moderator's reactions)
These should have been removed and can cause issues with display in some admin pages.

**To Reproduce**

As a moderator react to a user (flag user)
Delete the flagged user
List the moderators reactions - reaction to the user (reactable is not found, reactable_id was old user_id) is still in the database.

**Expected behavior**

Data referencing the user is removed from the system when they are deleted - reactions to the user should be cleared by the Users::Delete call or one of it's collaborators.

**Additional context**

#15242 was a related report, this bug report is trying to get in front of the data issue rather than protecting the view/controller.

If we fix this, a data update to remove reactions to missing entities is a reasonable follow on (once we're no longer creating dangling reactions to deleted users, remove any present in the system).

### PR DESCRIPTION
**Pull request by djuber**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

When a moderator has reacted _to_ a user, and the user is deleted, remove the (now unneeded) reaction.

We had been removing the user's reactions (created by the user, not applying to the user) already.

## Related Tickets & Documents

Fixes #15245, when combined with a data update script.

## QA Instructions, Screenshots, Recordings

Flag a user. Delete the flagged user. Visit http://localhost:3000/admin/moderation/privileged_reactions

(this had been "hidden" already by [another PR](https://github.com/forem/forem/pull/15249) so no error is expected in main either)

Ideally the added test case is sufficient demonstration.

### UI accessibility concerns?

None

## Added/updated tests?

- [x] Yes

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [x] I will share this change internally with the appropriate teams

### CODE REVIEW

File: spec/services/users/delete_spec.rb [hunk 1]
```diff
@@ -68,6 +68,14 @@
     end.to change(FieldTest::Membership, :count).by(-1)
   end
 
+  it "deletes reactions to the user" do
+    build(:vomit_reaction, reactable: user).save!
```
[the remark this answers is not in the document]
Comment (djuber) [reply spec/services/users/delete_spec.rb]: It looks like the default `user` in the vomit_reaction factory wasn't a moderator so the `permissions` error (category is not valid if negative reaction from untrusted user) was being set.

I've since updated the factory so vomit reactions will be created from a moderator/trusted user account.

File: lib/data_update_scripts/20211209213849_remove_dangling_user_reactions.rb [hunk 2]
```diff
@@ -0,0 +1,11 @@
+module DataUpdateScripts
+  class RemoveDanglingUserReactions
+    def run
+      # reactions to users who have been deleted should be removed:
+      Reaction
+        .where(reactable_type: "User")
+        .where.not(reactable_id: User.all.select(:id))
+        .delete_all
```
Comment (djuber) [inline lib/data_update_scripts/20211209213849_remove_dangling_user_reactions.rb:8]: I would be more inclined for disciplines sake to use `find_each` or a batches approach, but the count in DEV (where I expect the count to be highest) is 27.

However - we _also_ have 1000+ comment reactions that are dangling and I'll look into that next.

**Review by jgaskins — APPROVED** [review]
Nice find!

**Review by jeremyf — APPROVED** [review]

File: app/models/user.rb [hunk 3]
```diff
@@ -536,6 +536,10 @@ def subscribed_to_email_follower_notifications?
     notification_setting.email_follower_notifications
   end
 
+  def reactions_to
```
Comment (citizen428) [inline app/models/user.rb:539]: @djuber Sorry for the ping on an already merged PR. Personally, I don't find this extra method in `User` adds much (if anything) in terms of readability and `User` is big enough as is, how do you feel about removing this again?
