### PR TITLE
Fix Analytics Dashboard Page missing "Back To Dashboard" button

### LINKED ISSUE #14374: Add "Back to dashboard" button to all Analytics pages
**Suggestion**
Some Dashboard Pages have no ```Back To Main Dashboard``` button
For example:  Analytic page Only have ```Back To Main Dashboard``` when user have at least one organization
- No organization
image

- Have Organization: 
image

Others Dashboard page that also does not have ```Back To Main Dashboard```  button: Listing, Posts, and Series

**Expected behavior**

1. All Pages that can be reach through DashBoard should always have a ```Back To Main Dashboard``` instead of having user navigate back to home then dashboard or use back button from browser
2. Or we could instead fit the left sidebar in the extra space.

### PR DESCRIPTION
**Pull request by zeotuan**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Analytic page Only have ```Back To Main Dashboard``` when user have at least one organization
See #14374
Close #14374
## Related Tickets & Documents
Partially fix part of #14374
## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the
[Forem Accessibility Docs](https://docs.forem.com/frontend/accessibility)._

## Added/updated tests?

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://admin.forem.com/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Review by rhymes — COMMENTED** [review]
Hi @zeotuan, thanks for this fix! Could you add a test here?

https://github.com/forem/forem/blob/349a549dc4e5a8bb49298b8c6be794c664d307c5/spec/requests/dashboard_spec.rb#L257

File: spec/requests/dashboard_spec.rb [hunk 1]
```diff
@@ -268,6 +268,14 @@
         get "/dashboard/analytics"
         expect(response.body).to include("Analytics")
       end
+
+      it "page always contain back to dashboard button" do
+        sign_in user
+        get "/dashboard/analytics"
```
Comment (zeotuan) [inline spec/requests/dashboard_spec.rb:274]: Tried to use visit here instead of get but got undefined method.

Comment (citizen428) [reply spec/requests/dashboard_spec.rb:274]: `visit` is for system tests, this is a request spec.

**Review by citizen428 — APPROVED** [review]

**Review by rhymes — APPROVED** [review]
