### PR TITLE
Fix reply button visibility on locked discussion

### LINKED ISSUE #17891: Reply button shows even when conversation is locked
**Describe the bug**

When a conversation is locked, no new comments or replies are permitted. We hide the main comment box but "reply" buttons on existing comments are still visible, clickable, and the reply form appears. If a user attempts to submit a reply, they see an error and the comment is appropriately not posted, but the form shouldn't be there in the first place.

Given the sensitivity of locked discussion threads, the reply button should not appear to make sure authors have confidence the comments are fully locked.

**To Reproduce**

- Create a post
- Add some comments
- Lock the conversation
- Observe that the reply buttons are still visible

**Expected behavior**

Reply buttons should not be visible

**Screenshots**

Check out [this post on DEV](https://dev.to/alvaromontoro/lgbtq-flags-coded-in-css-3k1k) for an example

### PR DESCRIPTION
**Pull request by thejwuscript**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This PR fixes the issue that reply buttons are still visible on comment threads for a locked discussion. They should not appear when a discussion is locked. 

This PR also hides the new comment box for locked discussions on legacy comment threads.

## Related Tickets & Documents

- Closes #17891

## QA Instructions, Screenshots, Recordings
1. Navigate to an article that has its discussion locked.
2. Navigate to any comment thread. 
3. Observe that reply buttons are not present. Example screenshot below:
screenshot 1

4. On legacy comment threads, observe also that the new comment box is not shown. Example screenshot below:
screenshot 2

Tested on Chrome and Firefox.

### UI accessibility concerns?

None I am aware of.

## Added/updated tests?

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [[Developer Docs](https://developers.forem.com/)](https://developers.forem.com) or
      [[Storybook](https://storybook.forem.com/)](https://storybook.forem.com/) (for Crayons components)
- [ ] This PR changes the Forem platform and our documentation needs to be
      updated. I have filled out the
      [[Changes Requested](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)](https://github.com/forem/admin-docs/issues/new?assignees=&labels=&template=changes_requested.md)
      issue template so Community Success can help update the Admin Docs
      appropriately.
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`[CHANGELOG.md](https://github.com/forem/forem/tree/main/CHANGELOG.md)`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [ ] I will share this change in a [[Changelog](https://forem.dev/t/changelog)](https://forem.dev/t/changelog)
      or in a [[forem.dev](http://forem.dev/)](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

### CODE REVIEW

File: spec/system/articles/user_discussion_locks_spec.rb [hunk 1]
```diff
@@ -29,6 +33,37 @@
       visit article.path
       expect(page).to have_selector("#new_comment")
     end
+
+    it "doesn't hide reply button on each comment on the Article page" do
+      visit article.path
+      expect(page).to have_selector("[data-tracking-name='comment_reply_button']").twice
```
Comment (fdocr) [inline spec/system/articles/user_discussion_locks_spec.rb:39]: **Nitpick/non-blocking suggestion:** I wish we could avoid using the `data-tracking-name` attribute in these tests. I'm not sure if this attribute will stay in the codebase for the long term, but that's a personal preference/opinion of mine.

If someone else feels strongly about this I think an alternative that might work here would be to add a `data-testid` to the reply element. We use this pattern in certain areas of the app for these types of scenarios, [for example here](https://github.com/forem/forem/blob/main/app/javascript/article-form/components/ArticleCoverImage.jsx#L49)

**Review by fdocr — APPROVED** [review]
Thank you for the fix and also for the patience here @thejwuscript. I just pushed and empty commit to trigger the CI build that seemed stuck. 

I tested this locally and works great.

File: spec/system/articles/user_discussion_locks_spec.rb (hunk 1 above)
Comment (jeremyf) [reply spec/system/articles/user_discussion_locks_spec.rb:39]: @aitchiss might have some thoughts; I know a lot of Cypress tests are around the `aria-label` and `aria-role`, that might make sense for this as well.

Comment (aitchiss) [reply spec/system/articles/user_discussion_locks_spec.rb:39]: I think we should steer away from the tracking name, as @fdocr mentions it's very likely to be removed in the near future. I think using a `data-testid` for these kind of specs would be fine, but it would be nice to also add to the existing Cypress E2E tests so that we check the integrated user flow too.

@thejwuscript how do you feel about adding Cypress specs? (we have existing ones that could be added to at `cypress/integration/seededFlows/articleFlows/manageFlows/lockDiscussion.spec.js`). If you'd need assistance with that, just let me know.

Comment (thejwuscript) [reply spec/system/articles/user_discussion_locks_spec.rb]: I've changed the system specs to use `data-testid` instead and added some cypress specs. 
The specs are very similar to what I wrote for the system specs.

File: cypress/support/commands.js [hunk 2]
```diff
@@ -324,6 +324,30 @@ Cypress.Commands.add(
...
+ * Creates a comment.
+ *
+ * @param {string} content The content of the comment.
+ * @param {number} commentableId The ID of either Article or PodcastEpisode.
+ * @param {string} commentableType The model that the comment belongs to.
+ * @param {number} [parentId=null] The ID of the parent comment if it exists.
+ *
+ * @returns {Cypress.Chainable<Cypress.Response>} A cypress request for creating a comment.
+ */
+Cypress.Commands.add(
```
Comment (aitchiss) [inline cypress/support/commands.js:337]: Awesome work adding this helper! 🔥

**Review by aitchiss — APPROVED** [review]
Great job tackling this one and thank you for adding the additional tests!
