### PR TITLE
[15 min fix] Initialize follow button on podcast page

### LINKED ISSUE #14553: Podcast page's follow button not showing text
**Describe the bug**
The podcast button on any podcast's page is not showing any text. I can't tell whether or not I am following a podcast.

**To Reproduce**
visit any podcast's page, _signed in or signed out_, ie https://dev.to/practicaloperations

**Expected behavior**
Should be showing me status

**Screenshots**
Notice that the button is just empty.
image

**Desktop (please complete the following information):**
It's happening on all browsers and all operating systems.

**Additional context**
/a

### PR DESCRIPTION
**Pull request by aitchiss**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

The podcast page was missed in the refactor of follow button initialization - this PR makes sure the correct pack runs on this page and the follow button behaviour is reinstated.

## Related Tickets & Documents

Fixes #14553

## QA Instructions, Screenshots, Recordings

When logged in:
- Visit a podcast page e.g. '/codenewbie'
- Check the Follow button in the header has the correct 'Follow' text
- Check that when you click the button it changes to 'Following' and the 'follows' network request is triggered in the dev tools
- Refresh the page to make sure the Following state is persisted properly
- Repeat the process and check it turns back to 'Follow'

When logged out:
- Visit a podcast page e.g. '/codenewbie'
- Check the Follow button in the header has the correct 'Follow' text
- Check that when you click the button, the login modal appears

https://user-images.githubusercontent.com/20773163/130211955-41a7d209-92ee-408d-9c3a-8249a96b3aa1.mp4

### UI accessibility concerns?

N/A

## Added/updated tests?

- [X] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [Forem core team only] How will this change be communicated?

_Will this PR introduce a change that impacts Forem members or creators, the
development process, or any of our internal teams? If so, please note how you
will share this change with the people who need to know about it._

- [ ] I've updated the [Developer Docs](https://docs.forem.com) and/or
      [Admin Guide](https://admin.forem.com/), or
      [Storybook](https://storybook.forem.com/) (for Crayons components)
- [ ] I've updated the README or added inline documentation
- [ ] I've added an entry to
      [`CHANGELOG.md`](https://github.com/forem/forem/tree/main/CHANGELOG.md)
- [X] I will share this change in a [Changelog](https://forem.dev/t/changelog)
      or in a [forem.dev](http://forem.dev) post
- [ ] I will share this change internally with the appropriate teams
- [ ] I'm not sure how best to communicate this change and need help
- [ ] This change does not need to be communicated, and this is why not: _please
      replace this line with details on why this change doesn't need to be
      shared_

### CODE REVIEW

File: spec/support/seeds/seeds_e2e.rb [hunk 1]
```diff
@@ -563,3 +563,42 @@
     category: :bug,
   )
 end
+
+##############################################################################
+
+seeder.create_if_doesnt_exist(Podcast, "title", "Test podcast") do
```
Comment (aitchiss) [inline spec/support/seeds/seeds_e2e.rb:569]: Creating a seeded podcast for E2E testing was discussed in https://github.com/forem/forem/pull/14139 - this is purely a copy/paste of what has been added in that PR 🙂

**Review by rhymes — COMMENTED** [review]
Looks awesome, I'm not accepting to give priority to https://github.com/forem/forem/pull/14139 as I'm quite sure that git will create a conflict on spec/support/seeds/seeds_e2e.rb so I'd rather solve it on our ends than in the contributor's PR

 (hopefully not)

**Review by rhymes — APPROVED** [review]
LGTM!

**Review by djuber — APPROVED** [review]
