### PR TITLE
Ensuring reading list excludes unpublished articles

### LINKED ISSUE #14796: Reading list doesen't update when a post unpublished (Deleted also ?)
**Describe the bug**
The reading list doesn't update when a post deleted

**To Reproduce**

Make a post.
Save it to the reading list.
Delete that post.
Go to the reading list.
The saved post is still there, but when clicking it this page comes (Because the post was deleted)

**Expected behaviour**
The item should be removed when the post is deleted/unpublished.

**Screenshots**
image
image

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

### PR DESCRIPTION
**Pull request by jeremyf**
## What type of PR is this? (check all applicable)

- [x] Bug Fix

## Description

Prior to this commit, if a given user adds an article to their reading
list then the author unpublishes the article, the article remains in the
reading list.  When the given user would then "click" on the now
unpublished article, they would get a 404 Not Found notice.

With this commit, we now exclude unpublished articles from the search
results for the reading list.

This should also address the issue of attempting to archive the reading
list item (because it won't be visible in the listing).

One of the behaviors that is expected is if, in the above scenario, the
author again publishes the article, that article will again "appear" on
the reading list for the given user.

## Related Tickets & Documents

Closes #14796

## QA Instructions, Screenshots, Recordings

To test this in the UI:

- Sign in
- Create and publish an article
- Add it to your reading list
- Unpublish the article
- Revisit your reading list.

### UI accessibility concerns?

None.

## Added/updated tests?

- [x] Yes

## [Forem core team only] How will this change be communicated?

- [X] This change does not need to be communicated, and this is why not: when we merge the PR, the issue will close

### CODE REVIEW

File: app/services/search/reading_list.rb [hunk 1]
```diff
@@ -75,6 +86,8 @@ def self.find_articles(user:, term:, statuses:, tags:, page:, per_page:)
         "INNER JOIN (#{reaction_query_sql}) reactions ON reactions.reactable_id = articles.id",
       )
 
+      relation = relation.where(published: true) if only_published.present?
```
Comment (jgaskins) [inline app/services/search/reading_list.rb:89]: Do we need `.present?` if this is not expected to treat empty arrays, strings, and hashes equivalently to `false` and `nil`?

Also, nitpick: [scope](https://github.com/forem/forem/blob/6e275a12fc5aa3db79887441cdbeee2901112032/app/models/article.rb#L180-L183). 😄 

```suggestion
      relation = relation.published if only_published
```

File: spec/services/search/reading_list_spec.rb [hunk 2]
```diff
@@ -6,11 +6,20 @@
...
   let(:article_1) { create(:article, with_tags: false) }
   let(:article_2) { create(:article, with_tags: false) }
+  let(:unpublished_article) { create(:article) }
 
   def extract_from_results(result, attribute)
     result[:items].pluck(:reactable).pluck(attribute)
   end
 
+  def count_of_published_readling_items_for(user:)
+    Article.where(published: true).where(id: user.reactions.readinglist.map(&:reactable_id)).count
```
Comment (jgaskins) [inline spec/services/search/reading_list_spec.rb:16]: Nitpick: scope

```suggestion
    Article.published.where(id: user.reactions.readinglist.map(&:reactable_id)).count
```

**Review by jgaskins — APPROVED** [review]
Nice!

**Review by msarit — APPROVED** [review]
Small by mighty user-experience improvement! 🚀
